// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package emitter

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"strings"

	"github.com/lemon4ksan/aoni/internal/codegen/ir"
)

// Emitter generates pure Go code from a normalized IR.
type Emitter struct{}

// NewEmitter creates a new Emitter instance.
func NewEmitter() *Emitter {
	return &Emitter{}
}

// Emit compiles RootIR into formatted Go source code bytes.
func (e *Emitter) Emit(root *ir.RootIR) ([]byte, error) {
	if root == nil {
		return nil, errors.New("aoni/codegen/emitter: root IR is nil")
	}

	var buf bytes.Buffer

	// 1. File header & Package
	buf.WriteString("// Code generated by aoni-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package ")
	buf.WriteString(root.PackageName)
	buf.WriteString("\n\n")

	// 2. Imports block
	e.emitImports(&buf, root)

	// 3. Services (Client struct, Constructor, Methods)
	for _, svc := range root.Services {
		e.emitService(&buf, svc)
	}

	// 4. DTO Structs & Encoders
	for _, strct := range root.Structs {
		e.emitStruct(&buf, strct)
	}

	// 5. Tuples UnmarshalJSON
	for _, tuple := range root.Tuples {
		e.emitTuple(&buf, tuple)
	}

	// Format generated Go source
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("aoni/codegen/emitter: go/format error: %w\nSource:\n%s", err, buf.String())
	}

	return formatted, nil
}

func (e *Emitter) emitImports(buf *bytes.Buffer, root *ir.RootIR) {
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"errors\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"io\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString("\t\"strconv\"\n")
	buf.WriteString("\t\"time\"\n\n")

	buf.WriteString("\t\"github.com/lemon4ksan/aoni\"\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni/fast\"\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni/internal/bytesconv\"\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni/internal/urlutil\"\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni/mod\"\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni/option\"\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni/request\"\n")

	// User custom imports (exclude standard imports already emitted)
	stdImports := map[string]bool{
		"context": true, "encoding/json": true, "errors": true,
		"fmt": true, "io": true, "net/http": true, "net/url": true,
		"strconv": true, "strings": true, "time": true,
	}

	for _, imp := range root.Imports {
		if stdImports[imp.Path] || strings.Contains(imp.Path, "github.com/lemon4ksan/aoni") {
			continue
		}

		if imp.Alias != "" {
			fmt.Fprintf(buf, "\t%s \"%s\"\n", imp.Alias, imp.Path)
		} else {
			fmt.Fprintf(buf, "\t\"%s\"\n", imp.Path)
		}
	}

	buf.WriteString(")\n\n")
}

func (e *Emitter) emitService(buf *bytes.Buffer, svc *ir.ServiceIR) {
	clientStructName := lowerFirst(svc.Name) + "Client"

	// 1. Client Struct
	fmt.Fprintf(buf, "type %s struct {\n", clientStructName)

	for _, sub := range svc.SubRequesters {
		fmt.Fprintf(buf, "\t%s request.Requester\n", sub.FieldName)
	}

	buf.WriteString("}\n\n")

	// 2. Factory Constructor
	constructorName := "New"
	if svc.Name != "Client" && svc.Name != "API" {
		constructorName = "New" + svc.Name
	}

	fmt.Fprintf(
		buf,
		"// %s creates a new %s client instance with preconfigured execution pipelines.\n",
		constructorName,
		svc.Name,
	)
	fmt.Fprintf(buf, "func %s(doer aoni.RequestDoer, opts ...aoni.ClientOption) %s {\n", constructorName, svc.Name)
	buf.WriteString("\tif doer == nil {\n")

	switch svc.Engine {
	case ir.EngineNetHTTP:
		buf.WriteString("\t\tdoer = aoni.NewClient(nil)\n")
	case ir.EngineCustom:
		fmt.Fprintf(buf, "\t\tpanic(\"aoni: custom RequestDoer is required to initialize %s\")\n", svc.Name)
	default:
		buf.WriteString("\t\tdoer = fast.NewClient()\n")
	}

	buf.WriteString("\t}\n\n")

	// Base options
	buf.WriteString("\tvar baseOpts []aoni.ClientOption\n")

	for _, h := range svc.Headers {
		if h.DynamicTemplate == nil && h.StaticValue != "" {
			if strings.EqualFold(h.Key, "User-Agent") {
				fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithUserAgent(%q))\n", h.StaticValue)
			} else {
				fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithHeader(%q, %q))\n", h.Key, h.StaticValue)
			}
		}
	}

	if svc.Persona != "" {
		fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithPersona(%q))\n", svc.Persona)
	}

	if svc.Timeout != "" {
		fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithTimeoutString(%q))\n", svc.Timeout)
	}

	buf.WriteString("\tbaseOpts = append(baseOpts, opts...)\n\n")

	// Instantiate SubRequesters
	fmt.Fprintf(buf, "\treturn &%s{\n", clientStructName)

	for _, sub := range svc.SubRequesters {
		fmt.Fprintf(buf, "\t\t%s: request.AsRequester(\n", sub.FieldName)
		fmt.Fprintf(
			buf,
			"\t\t\taoni.Configure(doer, append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...),\n",
			sub.BaseURL,
		)
		buf.WriteString("\t\t),\n")
	}

	buf.WriteString("\t}\n}\n\n")

	// 3. Methods
	for _, m := range svc.Methods {
		e.emitMethod(buf, clientStructName, m)
	}
}

func (e *Emitter) emitMethod(buf *bytes.Buffer, clientStructName string, m *ir.MethodIR) {
	paramsStr := formatMethodParams(m.Params)
	returnsStr := formatMethodReturns(m.Return)

	fmt.Fprintf(buf, "func (c *%s) %s(%s) %s {\n", clientStructName, m.Name, paramsStr, returnsStr)

	// Stack modifiers buffer
	stackSize := m.StackModsSize
	if stackSize < 4 {
		stackSize = 4
	}

	fmt.Fprintf(buf, "\tvar stackMods [%d]aoni.RequestModifier\n", stackSize)
	buf.WriteString("\tallMods := stackMods[:0]\n\n")

	// Build dynamic headers (e.g. Referer)
	for _, h := range m.Headers {
		if h.DynamicTemplate != nil {
			e.emitDynamicHeader(buf, h)
		} else if h.StaticValue != "" {
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, %q))\n", h.Key, h.StaticValue)
		}
	}

	// Build Query String on Stack Buffer if there are query parameters
	var (
		queryParams   []*ir.ParamIR
		pathParams    []*ir.ParamIR
		formParams    []*ir.ParamIR
		bodyParam     *ir.ParamIR
		userModsParam *ir.ParamIR
	)

	for _, p := range m.Params {
		switch p.Location {
		case ir.LocQuery, ir.LocQueryStruct:
			queryParams = append(queryParams, p)
		case ir.LocPath:
			pathParams = append(pathParams, p)
		case ir.LocFormFields:
			formParams = append(formParams, p)
		case ir.LocBody:
			bodyParam = p
		case ir.LocModifiers:
			userModsParam = p
		}
	}

	// Query buffer serialization
	if len(queryParams) > 0 {
		e.emitQueryBuffer(buf, queryParams, m.StackBufSize)
	}

	// Form body serialization
	if m.PayloadKind == ir.PayloadForm && len(formParams) > 0 {
		e.emitFormBuffer(buf, formParams, m.StackBufSize)
	}

	// Path variables
	for _, p := range pathParams {
		fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithVar(%q, %s))\n", p.WireKey, p.GoName)
	}

	// Append user variadic modifiers if provided
	if userModsParam != nil {
		fmt.Fprintf(buf, "\tif len(%s) > 0 {\n", userModsParam.GoName)
		fmt.Fprintf(buf, "\t\tallMods = append(allMods, %s...)\n", userModsParam.GoName)
		buf.WriteString("\t}\n")
	}

	buf.WriteString("\n")

	// Custom Decoder / Encoder modifiers
	if m.Decoder != "" {
		switch strings.ToLower(m.Decoder) {
		case "json", "xml", "proto", "grpc-web":
			// Handled natively by aoni codecs
		default:
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithDecoder(%s))\n", m.Decoder)
		}
	}

	if m.Encoder != "" {
		fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithEncoder(%s))\n", m.Encoder)
	}

	// Target requester
	targetReq := m.TargetRequester
	if targetReq == "" {
		targetReq = "c.r"
	}

	rawPath := ""
	if m.Path != nil {
		rawPath = m.Path.RawTemplate
	}

	// Execute call
	e.emitExecution(buf, m, targetReq, rawPath, bodyParam)

	buf.WriteString("}\n\n")
}

func (e *Emitter) emitDynamicHeader(buf *bytes.Buffer, h ir.HeaderIR) {
	buf.WriteString("\tvar refBuf [128]byte\n")
	buf.WriteString("\tref := refBuf[:0]\n")

	for _, seg := range h.DynamicTemplate.Segments {
		if !seg.IsVariable {
			fmt.Fprintf(buf, "\tref = append(ref, %q...)\n", seg.Literal)
		} else {
			if seg.Transform == ir.TransformPathEscape {
				fmt.Fprintf(buf, "\tref = append(ref, url.PathEscape(%s)...)\n", seg.VarName)
			} else {
				fmt.Fprintf(buf, "\tref = strconv.AppendUint(ref, uint64(%s), 10)\n", seg.VarName)
			}
		}
	}

	fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, bytesconv.B2S(ref)))\n\n", h.Key)
}

func (e *Emitter) emitQueryBuffer(buf *bytes.Buffer, params []*ir.ParamIR, bufSize int) {
	if bufSize <= 0 {
		bufSize = 256
	}

	fmt.Fprintf(buf, "\tvar qBuf [%d]byte\n", bufSize)
	buf.WriteString("\tqBytes := qBuf[:0]\n")

	for i, p := range params {
		if p.Location == ir.LocQueryStruct || p.Formatter == ir.FormatCompiledEncode {
			fmt.Fprintf(buf, "\tqBytes = %s.AppendQuery(qBytes)\n", p.GoName)
			continue
		}

		prefix := p.WireKey + "="
		if i > 0 {
			prefix = fmt.Sprintf("&%s=", p.WireKey)
		}

		fmt.Fprintf(buf, "\tqBytes = append(qBytes, %q...)\n", prefix)

		elemType := p.GoType.ElemType
		if elemType == "" {
			elemType = strings.TrimPrefix(p.GoType.Name, "[]")
		}

		switch p.Formatter {
		case ir.FormatIntAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, int64(%s), 10)\n", p.GoName)
		case ir.FormatUintAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendUint(qBytes, uint64(%s), 10)\n", p.GoName)
		case ir.FormatBoolAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendBool(qBytes, %s)\n", p.GoName)
		case ir.FormatBoolInt:
			fmt.Fprintf(
				buf,
				"\tif %s {\n\t\tqBytes = append(qBytes, '1')\n\t} else {\n\t\tqBytes = append(qBytes, '0')\n\t}\n",
				p.GoName,
			)

		case ir.FormatTimeRFC3339:
			fmt.Fprintf(buf, "\tqBytes = urlutil.AppendQueryEscapeString(qBytes, %s.Format(time.RFC3339))\n", p.GoName)
		case ir.FormatTimeUnixS:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, %s.Unix(), 10)\n", p.GoName)
		case ir.FormatTimeUnixMS:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, %s.UnixMilli(), 10)\n", p.GoName)
		case ir.FormatTimeLayout:
			layout := p.TimeLayout
			if layout == "" {
				layout = "2006-01-02"
			}

			fmt.Fprintf(buf, "\tqBytes = urlutil.AppendQueryEscapeString(qBytes, %s.Format(%q))\n", p.GoName, layout)

		case ir.FormatSliceComma:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, ',')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatSliceSpace:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, '+')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatSlicePipe:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, '|')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatBufferAppender:
			fmt.Fprintf(buf, "\tqBytes = %s.AppendBytes(qBytes)\n", p.GoName)
		case ir.FormatCustomStringer:
			fmt.Fprintf(buf, "\tqBytes = urlutil.AppendQueryEscapeString(qBytes, %s.String())\n", p.GoName)
		case ir.FormatQueryEscaped, ir.FormatDirectString:
			fallthrough
		default:
			fmt.Fprintf(buf, "\tqBytes = urlutil.AppendQueryEscapeString(qBytes, %s)\n", p.GoName)
		}
	}

	buf.WriteString("\tallMods = append(allMods, mod.WithRawQuery(bytesconv.B2S(qBytes)))\n\n")
}

func (e *Emitter) emitFormBuffer(buf *bytes.Buffer, params []*ir.ParamIR, bufSize int) {
	if bufSize <= 0 {
		bufSize = 256
	}

	buf.WriteString(
		"\tallMods = append(allMods, mod.WithHeader(\"Content-Type\", \"application/x-www-form-urlencoded\"))\n",
	)

	// If single struct argument with compiled encoder
	if len(params) == 1 && params[0].Formatter == ir.FormatCompiledEncode {
		p := params[0]

		fmt.Fprintf(buf, "\tvar formBuf [%d]byte\n", bufSize)
		fmt.Fprintf(buf, "\tformBytes := %s.AppendFormData(formBuf[:0])\n", p.GoName)
		buf.WriteString("\tallMods = append(allMods, mod.WithBodyBytes(formBytes))\n\n")

		return
	}

	fmt.Fprintf(buf, "\tvar formBuf [%d]byte\n", bufSize)
	buf.WriteString("\tformBytes := formBuf[:0]\n")

	for i, p := range params {
		prefix := p.WireKey + "="
		if i > 0 {
			prefix = fmt.Sprintf("&%s=", p.WireKey)
		}

		fmt.Fprintf(buf, "\tformBytes = append(formBytes, %q...)\n", prefix)

		switch p.Formatter {
		case ir.FormatIntAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendInt(formBytes, int64(%s), 10)\n", p.GoName)
		case ir.FormatUintAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendUint(formBytes, uint64(%s), 10)\n", p.GoName)
		case ir.FormatBoolAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendBool(formBytes, %s)\n", p.GoName)
		default:
			fmt.Fprintf(buf, "\tformBytes = urlutil.AppendQueryEscapeString(formBytes, %s)\n", p.GoName)
		}
	}

	buf.WriteString("\tallMods = append(allMods, mod.WithBodyBytes(formBytes))\n\n")
}

func (e *Emitter) emitExecution(buf *bytes.Buffer, m *ir.MethodIR, targetReq, rawPath string, bodyParam *ir.ParamIR) {
	methodVerb := m.HTTPMethod
	if methodVerb == "" {
		methodVerb = "GET"
	}

	genericType := "request.NoResponse"
	if m.Return != nil && !m.Return.IsVoid && m.Return.SuccessType.Name != "" {
		genericType = strings.TrimPrefix(m.Return.SuccessType.Name, "*")
	}

	// Handle Envelope unwrapping (@unwrap data)
	if m.UnwrapField != "" {
		e.emitEnvelopeUnwrap(buf, m, targetReq, rawPath, bodyParam)
		return
	}

	bodyArg := "nil"
	if bodyParam != nil {
		bodyArg = bodyParam.GoName
	}

	switch methodVerb {
	case "GET":
		switch {
		case m.Return.IsVoid:
			fmt.Fprintf(
				buf,
				"\t_, err := request.GetTo[%s](ctx, %s, %q, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
			)
			buf.WriteString("\treturn err\n")

		case m.Return.IsDirectBytes:
			fmt.Fprintf(buf, "\tresp, err := request.GetTo[[]byte](ctx, %s, %q, allMods...)\n", targetReq, rawPath)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			buf.WriteString("\treturn *resp, nil\n")

		case m.Return.SuccessType.Name == "io.ReadCloser" || m.Return.SuccessType.Name == "io.Reader":
			fmt.Fprintf(buf, "\tresp, err := %s.Request(ctx, http.MethodGet, %q, allMods...)\n", targetReq, rawPath)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			buf.WriteString("\treturn resp.Body, nil\n")
		default:
			fmt.Fprintf(
				buf,
				"\tresp, err := request.GetTo[%s](ctx, %s, %q, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
			)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)

			if m.Return.SuccessType.IsPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

	case "POST":
		if m.Return.IsVoid {
			fmt.Fprintf(
				buf,
				"\t_, err := request.PostTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			buf.WriteString("\treturn err\n")
		} else {
			fmt.Fprintf(
				buf,
				"\tresp, err := request.PostTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)

			if m.Return.SuccessType.IsPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

	case "PUT":
		fmt.Fprintf(
			buf,
			"\tresp, err := request.PutTo[%s](ctx, %s, %q, %s, allMods...)\n",
			genericType,
			targetReq,
			rawPath,
			bodyArg,
		)

		if m.Return.IsVoid {
			buf.WriteString("\treturn err\n")
		} else {
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)
			buf.WriteString("\treturn resp, nil\n")
		}

	case "DELETE":
		fmt.Fprintf(
			buf,
			"\tresp, err := request.DeleteTo[%s](ctx, %s, %q, allMods...)\n",
			genericType,
			targetReq,
			rawPath,
		)

		if m.Return.IsVoid {
			buf.WriteString("\treturn err\n")
		} else {
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)
			buf.WriteString("\treturn resp, nil\n")
		}
	}
}

func (e *Emitter) emitEnvelopeUnwrap(
	buf *bytes.Buffer,
	m *ir.MethodIR,
	targetReq, rawPath string,
	bodyParam *ir.ParamIR,
) {
	successType := m.Return.SuccessType.Name

	fieldName := strings.ToUpper(m.UnwrapField[:1]) + m.UnwrapField[1:]

	buf.WriteString("\ttype envelope struct {\n")
	buf.WriteString("\t\tSuccess bool `json:\"success\"`\n")
	fmt.Fprintf(buf, "\t\t%s %s `json:\"%s\"`\n", fieldName, successType, m.UnwrapField)
	buf.WriteString("\t\tErrorMsg string `json:\"error,omitempty\"`\n")
	buf.WriteString("\t}\n\n")

	if m.HTTPMethod == "POST" {
		bodyArg := "nil"
		if bodyParam != nil {
			bodyArg = bodyParam.GoName
		}

		fmt.Fprintf(
			buf,
			"\tresp, err := request.PostTo[envelope](ctx, %s, %q, %s, allMods...)\n",
			targetReq,
			rawPath,
			bodyArg,
		)
	} else {
		fmt.Fprintf(buf, "\tresp, err := request.GetTo[envelope](ctx, %s, %q, allMods...)\n", targetReq, rawPath)
	}

	buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	buf.WriteString("\tif !resp.Success && resp.ErrorMsg != \"\" {\n\t\treturn nil, errors.New(resp.ErrorMsg)\n\t}\n")
	fmt.Fprintf(buf, "\treturn resp.%s, nil\n", fieldName)
}

func (e *Emitter) emitChecks(buf *bytes.Buffer, m *ir.MethodIR) {
	for _, chk := range m.Checks {
		fieldGoName := toPascalCase(chk.Field)

		cond := "!resp." + fieldGoName
		if chk.ExpectedVal != "true" {
			switch chk.Operator {
			case ir.OpEqual:
				cond = fmt.Sprintf("resp.%s != %s", fieldGoName, chk.ExpectedVal)
			case ir.OpNotEqual:
				cond = fmt.Sprintf("resp.%s == %s", fieldGoName, chk.ExpectedVal)
			default:
				cond = fmt.Sprintf("!(resp.%s %s %s)", fieldGoName, chk.Operator, chk.ExpectedVal)
			}
		}

		fmt.Fprintf(buf, "\tif %s {\n", cond)
		fmt.Fprintf(buf, "\t\treturn nil, errors.New(%q)\n", chk.ErrorMsg)
		buf.WriteString("\t}\n")
	}
}

func (e *Emitter) emitStruct(buf *bytes.Buffer, s *ir.StructIR) {
	fmt.Fprintf(buf, "type %s struct {\n", s.Name)

	for _, f := range s.Fields {
		tag := f.CustomTag
		if tag == "" {
			if f.IsOmitEmpty {
				tag = fmt.Sprintf("json:\"%s,omitempty\"", f.WireName)
			} else {
				tag = fmt.Sprintf("json:\"%s\"", f.WireName)
			}
		}

		fmt.Fprintf(buf, "\t%s %s `%s`\n", f.GoName, f.Type.Name, tag)
	}

	buf.WriteString("}\n\n")

	// Emit AppendFormData & AppendQuery methods for zero-alloc serialization
	if s.GenValueEncoder {
		fmt.Fprintf(
			buf,
			"// AppendFormData serializes %s into url-encoded form bytes on dst buffer (0 B/op).\n",
			s.Name,
		)
		fmt.Fprintf(buf, "func (r *%s) AppendFormData(dst []byte) []byte {\n", s.Name)
		buf.WriteString("\tif r == nil {\n\t\treturn dst\n\t}\n\n")

		for _, f := range s.Fields {
			switch f.Type.Name {
			case "string":
				fmt.Fprintf(buf, "\tif r.%s != \"\" {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = urlutil.AppendQueryEscapeString(dst, r.%s)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "int", "int64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "uint", "uint32", "uint64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendUint(dst, uint64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "time.Time":
				fmt.Fprintf(buf, "\tif !r.%s.IsZero() {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(
					buf,
					"\t\tdst = urlutil.AppendQueryEscapeString(dst, r.%s.Format(time.RFC3339))\n",
					f.GoName,
				)
				buf.WriteString("\t}\n")

			case "bool":
				fmt.Fprintf(buf, "\tif r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")

				switch f.Formatter {
				case ir.FormatBoolInt:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=1")
				case ir.FormatBoolFlag:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName)
				default:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=true")
				}

				buf.WriteString("\t}\n")

			case "[]int", "[]int64":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(v), 10)\n")
				buf.WriteString("\t}\n")

			case "[]string":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = urlutil.AppendQueryEscapeString(dst, v)\n")
				buf.WriteString("\t}\n")

			case "any", "interface{}":
				fmt.Fprintf(buf, "\tif r.%s != nil {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = append(dst, fmt.Sprint(r.%s)...)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "values.Int64String", "values.Uint64String", "values.Float64String", "values.BoolInt":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			default:
				if strings.HasPrefix(f.Type.Name, "[]") || strings.HasPrefix(f.Type.Name, "map[") {
					continue
				}

				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")
			}
		}

		buf.WriteString("\n\treturn dst\n}\n\n")

		fmt.Fprintf(buf, "// AppendQuery serializes %s into query string bytes on dst buffer (0 B/op).\n", s.Name)
		fmt.Fprintf(buf, "func (r *%s) AppendQuery(dst []byte) []byte {\n", s.Name)
		buf.WriteString("\treturn r.AppendFormData(dst)\n}\n\n")

		// Also emit EncodeValues for url.Values interoperability
		fmt.Fprintf(buf, "// EncodeValues serializes %s into url.Values without reflection.\n", s.Name)
		fmt.Fprintf(buf, "func (r *%s) EncodeValues(vals url.Values) {\n", s.Name)
		buf.WriteString("\tif r == nil {\n\t\treturn\n\t}\n")

		for _, f := range s.Fields {
			switch f.Type.Name {
			case "string":
				fmt.Fprintf(buf, "\tif r.%s != \"\" {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, r.%s)\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "int", "int64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatInt(int64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "uint", "uint32", "uint64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatUint(uint64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "bool":
				fmt.Fprintf(buf, "\tif r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, \"true\")\n", f.WireName)
				buf.WriteString("\t}\n")
			case "[]int", "[]int64":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Add(%q, strconv.FormatInt(int64(v), 10))\n", f.WireName)
				buf.WriteString("\t}\n")
			case "[]string":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Add(%q, v)\n", f.WireName)
				buf.WriteString("\t}\n")
			case "any", "interface{}":
				fmt.Fprintf(buf, "\tif r.%s != nil {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, fmt.Sprint(r.%s))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "values.Int64String", "values.Uint64String", "values.Float64String", "values.BoolInt":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatInt(int64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			default:
				if strings.HasPrefix(f.Type.Name, "[]") || strings.HasPrefix(f.Type.Name, "map[") {
					continue
				}

				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatInt(int64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			}
		}

		buf.WriteString("}\n\n")
	}
}

func (e *Emitter) emitTuple(buf *bytes.Buffer, t *ir.TupleIR) {
	n := len(t.Fields)
	fmt.Fprintf(buf, "// UnmarshalJSON decodes a heterogeneous JSON array tuple into %s.\n", t.Name)
	fmt.Fprintf(buf, "func (t *%s) UnmarshalJSON(data []byte) error {\n", t.Name)
	fmt.Fprintf(buf, "\tvar raw [%d]json.RawMessage\n", n)
	buf.WriteString("\tif err := json.Unmarshal(data, &raw); err != nil {\n\t\treturn err\n\t}\n")

	for i, f := range t.Fields {
		fmt.Fprintf(buf, "\t_ = json.Unmarshal(raw[%d], &t.%s)\n", i, f.GoName)
	}

	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")
}

func emitSliceElementFormat(buf *bytes.Buffer, elemType, targetBuf, valVar string) {
	elemType = strings.TrimPrefix(elemType, "*")
	switch elemType {
	case "string":
		fmt.Fprintf(buf, "\t\t%s = urlutil.AppendQueryEscapeString(%s, %s)\n", targetBuf, targetBuf, valVar)
	case "int", "int8", "int16", "int32", "int64":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendInt(%s, int64(%s), 10)\n", targetBuf, targetBuf, valVar)
	case "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendUint(%s, uint64(%s), 10)\n", targetBuf, targetBuf, valVar)
	case "bool":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendBool(%s, %s)\n", targetBuf, targetBuf, valVar)
	default:
		fmt.Fprintf(buf, "\t\t%s = urlutil.AppendQueryEscapeString(%s, fmt.Sprint(%s))\n", targetBuf, targetBuf, valVar)
	}
}
