// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package emitter

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"strings"

	"github.com/lemon4ksan/aoni/internal/codegen/ir"
)

// Emitter generates pure Go code from a normalized IR.
type Emitter struct{}

// NewEmitter creates a new Emitter instance.
func NewEmitter() *Emitter {
	return &Emitter{}
}

// Emit compiles RootIR into formatted Go source code bytes.
func (e *Emitter) Emit(root *ir.RootIR) ([]byte, error) {
	if root == nil {
		return nil, errors.New("aoni/codegen/emitter: root IR is nil")
	}

	var buf bytes.Buffer

	// 1. File header & Package
	buf.WriteString("// Code generated by aoni-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package ")
	buf.WriteString(root.PackageName)
	buf.WriteString("\n\n")

	// 2. Imports block
	e.emitImports(&buf, root)

	// 3. Services (Client struct, Constructor, Methods)
	for _, svc := range root.Services {
		e.emitService(&buf, svc)
	}

	// 4. DTO Structs & Encoders
	for _, strct := range root.Structs {
		e.emitStruct(&buf, strct)
	}

	// 5. Tuples UnmarshalJSON
	for _, tuple := range root.Tuples {
		e.emitTuple(&buf, tuple)
	}

	// Format generated Go source
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("aoni/codegen/emitter: go/format error: %w\nSource:\n%s", err, buf.String())
	}

	return formatted, nil
}

func (e *Emitter) emitImports(buf *bytes.Buffer, root *ir.RootIR) {
	buf.WriteString("import (\n")

	stdList := collectStdImports(root)
	for _, pkg := range stdList {
		fmt.Fprintf(buf, "\t\"%s\"\n", pkg)
	}

	hasFastClient := false
	if root != nil {
		for _, svc := range root.Services {
			isStrict := svc.Engine == ir.EngineRequired || svc.RequesterType != ""
			if !isStrict && svc.Engine != ir.EngineNetHTTP && svc.Engine != ir.EngineCustom {
				hasFastClient = true
			}
		}
	}

	buf.WriteString("\n\t\"github.com/lemon4ksan/aoni\"\n")

	if hasFastClient {
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/fast\"\n")
	}

	buf.WriteString("\t\"github.com/lemon4ksan/aoni/mod\"\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni/option\"\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni/request\"\n")

	// User custom imports (exclude standard imports already emitted)
	stdImports := map[string]bool{
		"bytes": true, "context": true, "encoding/json": true, "errors": true,
		"fmt": true, "io": true, "mime/multipart": true, "net/http": true,
		"net/textproto": true, "net/url": true, "os": true, "regexp": true,
		"strconv": true, "strings": true, "time": true,
	}

	for _, imp := range root.Imports {
		if stdImports[imp.Path] || strings.Contains(imp.Path, "github.com/lemon4ksan/aoni") {
			continue
		}

		if imp.Alias != "" {
			fmt.Fprintf(buf, "\t%s \"%s\"\n", imp.Alias, imp.Path)
		} else {
			fmt.Fprintf(buf, "\t\"%s\"\n", imp.Path)
		}
	}

	buf.WriteString(")\n\n")
}

func collectStdImports(root *ir.RootIR) []string {
	needed := map[string]bool{
		"context":  true,
		"net/http": true,
	}

	for _, svc := range root.Services {
		if svc.Engine == ir.EngineRequired || svc.RequesterType != "" {
			needed["errors"] = true
		}

		for _, m := range svc.Methods {
			if m.Extract != nil {
				needed["bytes"] = true
				needed["errors"] = true
				needed["io"] = true

				needed["encoding/json"] = true
				if m.Extract.Kind == ir.ExtractRegex {
					needed["regexp"] = true
				}

				if m.Extract.Kind == ir.ExtractHTMLToken {
					needed["fmt"] = true
				}
			}

			if m.PayloadKind == ir.PayloadMultipart {
				needed["bytes"] = true
				needed["mime/multipart"] = true
				needed["net/textproto"] = true
				needed["fmt"] = true
			}

			if m.PayloadKind == ir.PayloadForm {
				needed["net/url"] = true
			}

			if m.SignHMAC != nil && m.SignHMAC.KeyEnv != "" {
				needed["os"] = true
			}

			if m.UnwrapField != "" {
				needed["encoding/json"] = true
				needed["errors"] = true
			}

			for _, p := range m.Params {
				if p.Location == ir.LocQuery || p.Location == ir.LocFormFields {
					needed["net/url"] = true
					if p.Formatter == ir.FormatJSONString {
						needed["encoding/json"] = true
					}

					if p.Formatter == ir.FormatIntAppend || p.Formatter == ir.FormatUintAppend ||
						p.Formatter == ir.FormatBoolAppend {
						needed["strconv"] = true
					}

					if p.Formatter == ir.FormatTimeRFC3339 || p.Formatter == ir.FormatTimeUnixS ||
						p.Formatter == ir.FormatTimeUnixMS ||
						p.Formatter == ir.FormatTimeLayout {
						needed["time"] = true
						needed["strconv"] = true
					}
				}
			}
		}
	}

	for _, s := range root.Structs {
		for _, f := range s.Fields {
			if f.Type.Name == "time.Time" {
				needed["time"] = true
			}

			if strings.HasPrefix(f.Type.Name, "int") || strings.HasPrefix(f.Type.Name, "uint") {
				needed["strconv"] = true
			}

			needed["net/url"] = true
		}
	}

	for range root.Tuples {
		needed["encoding/json"] = true
		needed["fmt"] = true
	}

	order := []string{
		"bytes", "context", "encoding/json", "errors", "fmt", "io",
		"mime/multipart", "net/http", "net/textproto", "net/url", "os", "regexp",
		"strconv", "time",
	}

	var res []string
	for _, pkg := range order {
		if needed[pkg] {
			res = append(res, pkg)
		}
	}

	return res
}

func (e *Emitter) emitService(buf *bytes.Buffer, svc *ir.ServiceIR) {
	clientStructName := lowerFirst(svc.Name) + "Client"

	// 1. Client Struct
	fmt.Fprintf(buf, "type %s struct {\n", clientStructName)

	for _, sub := range svc.SubRequesters {
		fmt.Fprintf(buf, "\t%s request.Requester\n", sub.FieldName)
	}

	buf.WriteString("}\n\n")

	// 2. Factory Constructor
	constructorName := "New"
	if svc.Name != "Client" && svc.Name != "API" {
		constructorName = "New" + svc.Name
	}

	mustConstructorName := "Must" + constructorName

	isStrict := svc.Engine == ir.EngineRequired || svc.RequesterType != ""

	reqArgType := "aoni.RequestDoer"
	if svc.RequesterType != "" {
		reqArgType = svc.RequesterType
	}

	if isStrict {
		fmt.Fprintf(
			buf,
			"// %s creates a new %s client instance backed by an authenticated %s.\n",
			constructorName,
			svc.Name,
			reqArgType,
		)
		fmt.Fprintf(
			buf,
			"func %s(client %s, opts ...aoni.ClientOption) (%s, error) {\n",
			constructorName,
			reqArgType,
			svc.Name,
		)
		fmt.Fprintf(
			buf,
			"\tif client == nil {\n\t\treturn nil, errors.New(\"aoni: client (%s) is required to initialize %s\")\n\t}\n\n",
			reqArgType,
			svc.Name,
		)

		// Base options
		buf.WriteString("\tvar baseOpts []aoni.ClientOption\n")

		for _, h := range svc.Headers {
			if h.DynamicTemplate == nil && h.StaticValue != "" {
				if strings.EqualFold(h.Key, "User-Agent") {
					fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithUserAgent(%q))\n", h.StaticValue)
				} else {
					fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithHeader(%q, %q))\n", h.Key, h.StaticValue)
				}
			}
		}

		if svc.Persona != "" {
			fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithPersona(%q))\n", svc.Persona)
		}

		if svc.Timeout != "" {
			fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithTimeoutString(%q))\n", svc.Timeout)
		}

		buf.WriteString("\tbaseOpts = append(baseOpts, opts...)\n\n")

		// If preconfigured requester is passed without new options, reuse directly
		buf.WriteString("\tif req, ok := any(client).(request.Requester); ok && len(opts) == 0 {\n")
		fmt.Fprintf(buf, "\t\treturn &%s{\n", clientStructName)

		for _, sub := range svc.SubRequesters {
			fmt.Fprintf(buf, "\t\t\t%s: req,\n", sub.FieldName)
		}

		buf.WriteString("\t\t}, nil\n\t}\n\n")

		// Target requester resolution
		buf.WriteString("\tvar targetReq request.Requester\n")
		buf.WriteString("\tif d, ok := any(client).(aoni.RequestDoer); ok {\n")
		fmt.Fprintf(
			buf,
			"\t\ttargetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...))\n",
			svc.BaseURL,
		)
		buf.WriteString("\t} else if req, ok := any(client).(request.Requester); ok {\n")
		buf.WriteString("\t\ttargetReq = req\n")
		buf.WriteString("\t} else {\n")
		buf.WriteString("\t\treturn nil, errors.New(\"aoni: unsupported requester interface\")\n")
		buf.WriteString("\t}\n\n")

		// Instantiate SubRequesters
		fmt.Fprintf(buf, "\treturn &%s{\n", clientStructName)

		for _, sub := range svc.SubRequesters {
			fmt.Fprintf(buf, "\t\t%s: targetReq,\n", sub.FieldName)
		}

		buf.WriteString("\t}, nil\n}\n\n")

		// MustNew helper
		fmt.Fprintf(
			buf,
			"// %s initializes %s and panics if an error occurs.\n",
			mustConstructorName,
			svc.Name,
		)
		fmt.Fprintf(
			buf,
			"func %s(client %s, opts ...aoni.ClientOption) %s {\n",
			mustConstructorName,
			reqArgType,
			svc.Name,
		)
		fmt.Fprintf(buf, "\tapi, err := %s(client, opts...)\n", constructorName)
		buf.WriteString("\tif err != nil {\n\t\tpanic(err)\n\t}\n")
		buf.WriteString("\treturn api\n}\n\n")

		// Methods
		for _, m := range svc.Methods {
			e.emitMethod(buf, clientStructName, m)
		}

		return
	}

	fmt.Fprintf(
		buf,
		"// %s creates a new %s client instance with preconfigured execution pipelines.\n",
		constructorName,
		svc.Name,
	)
	fmt.Fprintf(buf, "func %s(doer any, opts ...aoni.ClientOption) %s {\n", constructorName, svc.Name)
	buf.WriteString("\tif doer == nil {\n")

	switch svc.Engine {
	case ir.EngineNetHTTP:
		buf.WriteString("\t\tdoer = aoni.NewClient(nil)\n")
	case ir.EngineCustom:
		fmt.Fprintf(buf, "\t\tpanic(\"aoni: custom RequestDoer is required to initialize %s\")\n", svc.Name)
	default:
		buf.WriteString("\t\tdoer = fast.NewClient()\n")
	}

	buf.WriteString("\t}\n\n")

	// If preconfigured requester is passed without new options, reuse directly
	buf.WriteString("\tif req, ok := doer.(request.Requester); ok && len(opts) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn &%s{\n", clientStructName)

	for _, sub := range svc.SubRequesters {
		fmt.Fprintf(buf, "\t\t\t%s: req,\n", sub.FieldName)
	}

	buf.WriteString("\t\t}\n\t}\n\n")

	// Base options
	buf.WriteString("\tvar baseOpts []aoni.ClientOption\n")

	for _, h := range svc.Headers {
		if h.DynamicTemplate == nil && h.StaticValue != "" {
			if strings.EqualFold(h.Key, "User-Agent") {
				fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithUserAgent(%q))\n", h.StaticValue)
			} else {
				fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithHeader(%q, %q))\n", h.Key, h.StaticValue)
			}
		}
	}

	if svc.Persona != "" {
		fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithPersona(%q))\n", svc.Persona)
	}

	if svc.Timeout != "" {
		fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithTimeoutString(%q))\n", svc.Timeout)
	}

	buf.WriteString("\tbaseOpts = append(baseOpts, opts...)\n\n")

	// Target requester resolution
	buf.WriteString("\tvar targetReq request.Requester\n")
	buf.WriteString("\tif d, ok := doer.(aoni.RequestDoer); ok {\n")
	fmt.Fprintf(
		buf,
		"\t\ttargetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...))\n",
		svc.BaseURL,
	)
	buf.WriteString("\t} else if req, ok := doer.(request.Requester); ok {\n")
	buf.WriteString("\t\ttargetReq = req\n")
	buf.WriteString("\t} else {\n")
	fmt.Fprintf(
		buf,
		"\t\ttargetReq = request.AsRequester(aoni.Configure(fast.NewClient(), append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...))\n",
		svc.BaseURL,
	)
	buf.WriteString("\t}\n\n")

	// Instantiate SubRequesters
	fmt.Fprintf(buf, "\treturn &%s{\n", clientStructName)

	for _, sub := range svc.SubRequesters {
		baseURL := sub.BaseURL
		if baseURL == "" {
			baseURL = svc.BaseURL
		}

		if sub.FieldName == "r" && baseURL == svc.BaseURL {
			fmt.Fprintf(buf, "\t\t%s: targetReq,\n", sub.FieldName)
		} else {
			fmt.Fprintf(
				buf,
				"\t\t%s: request.AsRequester(aoni.Configure(fast.NewClient(), append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...)),\n",
				sub.FieldName,
				baseURL,
			)
		}
	}

	buf.WriteString("\t}\n}\n\n")

	// 3. Methods
	for _, m := range svc.Methods {
		e.emitMethod(buf, clientStructName, m)
	}
}

func (e *Emitter) emitMethod(buf *bytes.Buffer, clientStructName string, m *ir.MethodIR) {
	paramsStr := formatMethodParams(m.Params)
	returnsStr := formatMethodReturns(m.Return)

	fmt.Fprintf(buf, "func (c *%s) %s(%s) %s {\n", clientStructName, m.Name, paramsStr, returnsStr)

	// Stack modifiers buffer
	stackSize := m.StackModsSize
	if stackSize < 4 {
		stackSize = 4
	}

	fmt.Fprintf(buf, "\tvar stackMods [%d]aoni.RequestModifier\n", stackSize)
	buf.WriteString("\tallMods := stackMods[:0]\n\n")

	// Build dynamic headers (e.g. Referer)
	for _, h := range m.Headers {
		if h.DynamicTemplate != nil {
			e.emitDynamicHeader(buf, &h)
		} else if h.StaticValue != "" {
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, %q))\n", h.Key, h.StaticValue)
		}
	}

	// Build Query String on Stack Buffer if there are query parameters
	var (
		queryParams     []*ir.ParamIR
		pathParams      []*ir.ParamIR
		formParams      []*ir.ParamIR
		multipartParams []*ir.ParamIR
		bodyParam       *ir.ParamIR
		userModsParam   *ir.ParamIR
	)

	consumedFileVars := make(map[string]bool)
	for _, p := range m.Params {
		if p.Location == ir.LocMultipartFile {
			if strings.HasPrefix(p.FileName, "{") && strings.HasSuffix(p.FileName, "}") {
				v := strings.Trim(p.FileName, "{}")
				consumedFileVars[v] = true
				consumedFileVars[strings.ToLower(v)] = true
			}

			if strings.HasPrefix(p.ContentType, "{") && strings.HasSuffix(p.ContentType, "}") {
				v := strings.Trim(p.ContentType, "{}")
				consumedFileVars[v] = true
				consumedFileVars[strings.ToLower(v)] = true
			}
		}
	}

	for _, p := range m.Params {
		if consumedFileVars[p.GoName] || consumedFileVars[strings.ToLower(p.GoName)] {
			continue
		}

		switch p.Location {
		case ir.LocQuery, ir.LocQueryStruct:
			queryParams = append(queryParams, p)
		case ir.LocPath:
			pathParams = append(pathParams, p)
		case ir.LocFormFields:
			formParams = append(formParams, p)
		case ir.LocMultipartField, ir.LocMultipartFile:
			multipartParams = append(multipartParams, p)
		case ir.LocBody:
			bodyParam = p
		case ir.LocModifiers:
			userModsParam = p
		}
	}

	// Query buffer serialization
	if len(queryParams) > 0 {
		e.emitQueryBuffer(buf, queryParams, m.StackBufSize)
	}

	// Form body serialization
	if m.PayloadKind == ir.PayloadForm && len(formParams) > 0 {
		e.emitFormBuffer(buf, m, formParams, m.StackBufSize)
	}

	// Multipart body serialization
	if m.PayloadKind == ir.PayloadMultipart && len(multipartParams) > 0 {
		e.emitMultipartBuffer(buf, multipartParams)
	}

	// Path variables
	for _, p := range pathParams {
		fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithVar(%q, %s))\n", p.WireKey, p.GoName)
	}

	// Append user variadic modifiers if provided
	if userModsParam != nil {
		fmt.Fprintf(buf, "\tif len(%s) > 0 {\n", userModsParam.GoName)
		fmt.Fprintf(buf, "\t\tallMods = append(allMods, %s...)\n", userModsParam.GoName)
		buf.WriteString("\t}\n")
	}

	buf.WriteString("\n")

	// Custom Decoder / Encoder modifiers
	if m.Decoder != "" {
		switch strings.ToLower(m.Decoder) {
		case "json", "xml", "proto", "grpc-web":
			// Handled natively by aoni codecs
		default:
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithDecoder(%s))\n", m.Decoder)
		}
	}

	if m.Encoder != "" {
		fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithEncoder(%s))\n", m.Encoder)
	}

	if m.Idempotent {
		buf.WriteString("\tallMods = append(allMods, mod.WithIdempotencyKey())\n")
	}

	if m.Coalesce {
		buf.WriteString("\tallMods = append(allMods, mod.WithCoalesce())\n")
	}

	if m.ETag {
		buf.WriteString("\tallMods = append(allMods, mod.WithETag())\n")
	}

	if m.SignHMAC != nil {
		if m.SignHMAC.KeyEnv != "" {
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithSignHMAC(os.Getenv(%q)))\n", m.SignHMAC.KeyEnv)
		} else {
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithSignHMAC(%q))\n", m.SignHMAC.SecretKey)
		}
	}

	// Target requester
	targetReq := m.TargetRequester
	if targetReq == "" {
		targetReq = "c.r"
	}

	rawPath := ""
	if m.Path != nil {
		rawPath = m.Path.RawTemplate
	}

	// Execute call
	e.emitExecution(buf, m, targetReq, rawPath, bodyParam)

	buf.WriteString("}\n\n")
}

func (e *Emitter) emitDynamicHeader(buf *bytes.Buffer, h *ir.HeaderIR) {
	buf.WriteString("\tvar refBuf [128]byte\n")
	buf.WriteString("\tref := refBuf[:0]\n")

	for _, seg := range h.DynamicTemplate.Segments {
		if !seg.IsVariable {
			fmt.Fprintf(buf, "\tref = append(ref, %q...)\n", seg.Literal)
		} else {
			if seg.Transform == ir.TransformPathEscape {
				fmt.Fprintf(buf, "\tref = append(ref, url.PathEscape(%s)...)\n", seg.VarName)
			} else {
				fmt.Fprintf(buf, "\tref = strconv.AppendUint(ref, uint64(%s), 10)\n", seg.VarName)
			}
		}
	}

	fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, string(ref)))\n\n", h.Key)
}

func (e *Emitter) emitQueryBuffer(buf *bytes.Buffer, params []*ir.ParamIR, bufSize int) {
	if bufSize <= 0 {
		bufSize = 256
	}

	fmt.Fprintf(buf, "\tvar qBuf [%d]byte\n", bufSize)
	buf.WriteString("\tqBytes := qBuf[:0]\n")

	for i, p := range params {
		if p.Location == ir.LocQueryStruct || p.Formatter == ir.FormatCompiledEncode {
			fmt.Fprintf(buf, "\tqBytes = %s.AppendQuery(qBytes)\n", p.GoName)
			continue
		}

		prefix := p.WireKey + "="
		if i > 0 {
			prefix = fmt.Sprintf("&%s=", p.WireKey)
		}

		fmt.Fprintf(buf, "\tqBytes = append(qBytes, %q...)\n", prefix)

		elemType := p.GoType.ElemType
		if elemType == "" {
			elemType = strings.TrimPrefix(p.GoType.Name, "[]")
		}

		switch p.Formatter {
		case ir.FormatIntAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, int64(%s), 10)\n", p.GoName)
		case ir.FormatUintAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendUint(qBytes, uint64(%s), 10)\n", p.GoName)
		case ir.FormatBoolAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendBool(qBytes, %s)\n", p.GoName)
		case ir.FormatBoolInt:
			fmt.Fprintf(
				buf,
				"\tif %s {\n\t\tqBytes = append(qBytes, '1')\n\t} else {\n\t\tqBytes = append(qBytes, '0')\n\t}\n",
				p.GoName,
			)

		case ir.FormatTimeRFC3339:
			fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(%s.Format(time.RFC3339))...)\n", p.GoName)
		case ir.FormatTimeUnixS:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, %s.Unix(), 10)\n", p.GoName)
		case ir.FormatTimeUnixMS:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, %s.UnixMilli(), 10)\n", p.GoName)
		case ir.FormatTimeLayout:
			layout := p.TimeLayout
			if layout == "" {
				layout = "2006-01-02"
			}

			fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(%s.Format(%q))...)\n", p.GoName, layout)

		case ir.FormatSliceComma:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, ',')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatSliceSpace:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, '+')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatSlicePipe:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, '|')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatBufferAppender:
			fmt.Fprintf(buf, "\tqBytes = %s.AppendBytes(qBytes)\n", p.GoName)
		case ir.FormatCustomStringer:
			fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(%s.String())...)\n", p.GoName)
		case ir.FormatQueryEscaped, ir.FormatDirectString:
			fallthrough
		default:
			fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(%s)...)\n", p.GoName)
		}
	}

	buf.WriteString("\tallMods = append(allMods, mod.WithRawQuery(string(qBytes)))\n\n")
}

func (e *Emitter) emitFormBuffer(buf *bytes.Buffer, m *ir.MethodIR, params []*ir.ParamIR, bufSize int) {
	if bufSize <= 0 {
		bufSize = 256
	}

	buf.WriteString(
		"\tallMods = append(allMods, mod.WithHeader(\"Content-Type\", \"application/x-www-form-urlencoded\"))\n",
	)

	// If single struct argument with compiled encoder
	if len(params) == 1 && params[0].Formatter == ir.FormatCompiledEncode {
		p := params[0]

		fmt.Fprintf(buf, "\tvar formBuf [%d]byte\n", bufSize)
		fmt.Fprintf(buf, "\tformBytes := %s.AppendFormData(formBuf[:0])\n", p.GoName)
		buf.WriteString("\tallMods = append(allMods, mod.WithBodyBytes(formBytes))\n\n")

		return
	}

	fmt.Fprintf(buf, "\tvar formBuf [%d]byte\n", bufSize)
	buf.WriteString("\tformBytes := formBuf[:0]\n")

	for i, p := range params {
		prefix := p.WireKey + "="
		if i > 0 {
			prefix = fmt.Sprintf("&%s=", p.WireKey)
		}

		fmt.Fprintf(buf, "\tformBytes = append(formBytes, %q...)\n", prefix)

		switch p.Formatter {
		case ir.FormatJSONString:
			fmt.Fprintf(buf, "\t%sJSON, err := json.Marshal(%s)\n", p.GoName, p.GoName)

			errRet := "\tif err != nil {\n\t\treturn err\n\t}\n"
			if m != nil && m.Return != nil && !m.Return.IsVoid {
				errRet = "\tif err != nil {\n\t\treturn nil, err\n\t}\n"
			}

			buf.WriteString(errRet)
			fmt.Fprintf(buf, "\tformBytes = append(formBytes, url.QueryEscape(string(%sJSON))...)\n", p.GoName)

		case ir.FormatIntAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendInt(formBytes, int64(%s), 10)\n", p.GoName)
		case ir.FormatUintAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendUint(formBytes, uint64(%s), 10)\n", p.GoName)
		case ir.FormatBoolAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendBool(formBytes, %s)\n", p.GoName)
		default:
			fmt.Fprintf(buf, "\tformBytes = append(formBytes, url.QueryEscape(%s)...)\n", p.GoName)
		}
	}

	buf.WriteString("\tallMods = append(allMods, mod.WithBodyBytes(formBytes))\n\n")
}

func (e *Emitter) emitMultipartBuffer(buf *bytes.Buffer, params []*ir.ParamIR) {
	buf.WriteString("\tvar bodyBuf bytes.Buffer\n")
	buf.WriteString("\tmw := multipart.NewWriter(&bodyBuf)\n")

	for _, p := range params {
		switch p.Location {
		case ir.LocMultipartField:
			fmt.Fprintf(buf, "\t_ = mw.WriteField(%q, fmt.Sprint(%s))\n", p.WireKey, p.GoName)
		case ir.LocMultipartFile:
			fn := p.FileName
			switch {
			case fn == "" || fn == "{filename}":
				fn = "filename"
			case strings.HasPrefix(fn, "{") && strings.HasSuffix(fn, "}"):
				fn = strings.Trim(fn, "{}")
			case !strings.HasPrefix(fn, `"`):
				fn = fmt.Sprintf("%q", fn)
			}

			ct := p.ContentType
			switch {
			case ct == "" || ct == "{content_type}":
				ct = "contentType"
			case strings.HasPrefix(ct, "{") && strings.HasSuffix(ct, "}"):
				ct = strings.Trim(ct, "{}")
			case !strings.HasPrefix(ct, `"`):
				ct = fmt.Sprintf("%q", ct)
			}

			fmt.Fprintf(buf, "\thdr := make(textproto.MIMEHeader)\n")
			fmt.Fprintf(
				buf,
				"\thdr.Set(\"Content-Disposition\", fmt.Sprintf(`form-data; name=%%q; filename=%%q`, %q, %s))\n",
				p.WireKey,
				fn,
			)
			fmt.Fprintf(buf, "\thdr.Set(\"Content-Type\", %s)\n", ct)
			fmt.Fprintf(buf, "\tpw, err := mw.CreatePart(hdr)\n")
			fmt.Fprintf(buf, "\tif err == nil {\n\t\t_, _ = pw.Write(%s)\n\t}\n", p.GoName)
		}
	}

	buf.WriteString("\t_ = mw.Close()\n")
	buf.WriteString(
		"\tallMods = append(allMods, mod.WithHeader(\"Content-Type\", mw.FormDataContentType()), mod.WithBodyBytes(bodyBuf.Bytes()))\n\n",
	)
}

func (e *Emitter) emitExecution(buf *bytes.Buffer, m *ir.MethodIR, targetReq, rawPath string, bodyParam *ir.ParamIR) {
	if m.Extract != nil {
		e.emitExtractExecution(buf, m, targetReq, rawPath)
		return
	}

	methodVerb := m.HTTPMethod
	if methodVerb == "" {
		methodVerb = "GET"
	}

	genericType := "request.NoResponse"
	if m.Return != nil && !m.Return.IsVoid && m.Return.SuccessType.Name != "" {
		genericType = strings.TrimPrefix(m.Return.SuccessType.Name, "*")
	}

	// Handle Envelope unwrapping (@unwrap data)
	if m.UnwrapField != "" {
		e.emitEnvelopeUnwrap(buf, m, targetReq, rawPath, bodyParam)
		return
	}

	bodyArg := "nil"
	if bodyParam != nil {
		bodyArg = bodyParam.GoName
	}

	// Escape hatch for custom package-level helper (@call custom.Func)
	if m.CallFunc != "" {
		callArgs := fmt.Sprintf("ctx, %s, %q", targetReq, rawPath)
		if bodyParam != nil {
			callArgs = fmt.Sprintf("ctx, %s, %q, %s", targetReq, rawPath, bodyArg)
		}

		switch {
		case m.Return.IsVoid:
			fmt.Fprintf(buf, "\t_, err := %s[%s](%s, allMods...)\n", m.CallFunc, genericType, callArgs)
			buf.WriteString("\treturn err\n")

		case m.Return.SuccessType.Name == "io.ReadCloser" || m.Return.SuccessType.Name == "io.Reader":
			fmt.Fprintf(buf, "\treturn %s(%s, allMods...)\n", m.CallFunc, callArgs)

		default:
			fmt.Fprintf(buf, "\tresp, err := %s[%s](%s, allMods...)\n", m.CallFunc, genericType, callArgs)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)

			if m.Return.SuccessType.IsPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

		return
	}

	switch methodVerb {
	case "GET":
		switch {
		case m.Return.IsVoid:
			fmt.Fprintf(
				buf,
				"\t_, err := request.GetTo[%s](ctx, %s, %q, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
			)
			buf.WriteString("\treturn err\n")

		case m.Return.IsDirectBytes:
			fmt.Fprintf(buf, "\tresp, err := request.GetTo[[]byte](ctx, %s, %q, allMods...)\n", targetReq, rawPath)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			buf.WriteString("\treturn *resp, nil\n")

		case m.Return.SuccessType.Name == "io.ReadCloser" || m.Return.SuccessType.Name == "io.Reader":
			fmt.Fprintf(buf, "\tresp, err := %s.Request(ctx, http.MethodGet, %q, allMods...)\n", targetReq, rawPath)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			buf.WriteString("\treturn resp.Body, nil\n")
		default:
			fmt.Fprintf(
				buf,
				"\tresp, err := request.GetTo[%s](ctx, %s, %q, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
			)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)

			if m.Return.SuccessType.IsPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

	case "POST":
		if m.Return.IsVoid {
			fmt.Fprintf(
				buf,
				"\t_, err := request.PostTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			buf.WriteString("\treturn err\n")
		} else {
			fmt.Fprintf(
				buf,
				"\tresp, err := request.PostTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)

			if m.Return.SuccessType.IsPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

	case "PUT":
		fmt.Fprintf(
			buf,
			"\tresp, err := request.PutTo[%s](ctx, %s, %q, %s, allMods...)\n",
			genericType,
			targetReq,
			rawPath,
			bodyArg,
		)

		if m.Return.IsVoid {
			buf.WriteString("\treturn err\n")
		} else {
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)
			buf.WriteString("\treturn resp, nil\n")
		}

	case "DELETE":
		fmt.Fprintf(
			buf,
			"\tresp, err := request.DeleteTo[%s](ctx, %s, %q, allMods...)\n",
			genericType,
			targetReq,
			rawPath,
		)

		if m.Return.IsVoid {
			buf.WriteString("\treturn err\n")
		} else {
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)
			buf.WriteString("\treturn resp, nil\n")
		}
	}
}

func (e *Emitter) emitExtractExecution(buf *bytes.Buffer, m *ir.MethodIR, targetReq, rawPath string) {
	methodVerb := m.HTTPMethod
	if methodVerb == "" {
		methodVerb = "GET"
	}

	resultType := "any"
	if m.Return != nil && m.Return.SuccessType.Name != "" {
		resultType = strings.TrimPrefix(m.Return.SuccessType.Name, "*")
	}

	httpVerb := "MethodGet"
	switch methodVerb {
	case "POST":
		httpVerb = "MethodPost"
	case "PUT":
		httpVerb = "MethodPut"
	case "DELETE":
		httpVerb = "MethodDelete"
	}

	fmt.Fprintf(buf, "\tresp, err := %s.Request(ctx, http.%s, %q, allMods...)\n", targetReq, httpVerb, rawPath)
	buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	buf.WriteString("\tdefer resp.Body.Close()\n\n")

	ext := m.Extract
	switch ext.Kind {
	case ir.ExtractCustom:
		fmt.Fprintf(buf, "\treturn %s(resp.Body)\n", ext.CustomFunc)

	case ir.ExtractRegex:
		buf.WriteString("\tbodyBytes, err := io.ReadAll(resp.Body)\n")
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")
		fmt.Fprintf(buf, "\trx := regexp.MustCompile(`%s`)\n", ext.RegexPattern)
		buf.WriteString("\tmatches := rx.FindSubmatch(bodyBytes)\n")
		buf.WriteString(
			"\tif len(matches) < 2 {\n\t\treturn nil, errors.New(\"extract: regex pattern not matched\")\n\t}\n\n",
		)
		fmt.Fprintf(buf, "\tvar result %s\n", resultType)
		buf.WriteString(
			"\tif err := json.Unmarshal(matches[1], &result); err != nil {\n\t\treturn nil, fmt.Errorf(\"extract: failed to unmarshal payload: %w\", err)\n\t}\n\n",
		)
		buf.WriteString("\treturn &result, nil\n")

	case ir.ExtractBetween:
		buf.WriteString("\tbodyBytes, err := io.ReadAll(resp.Body)\n")
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")
		fmt.Fprintf(buf, "\tprefix := []byte(%q)\n", ext.Prefix)
		buf.WriteString("\tstart := bytes.Index(bodyBytes, prefix)\n")
		buf.WriteString("\tif start == -1 {\n\t\treturn nil, errors.New(\"extract: prefix not found\")\n\t}\n")
		buf.WriteString("\tstart += len(prefix)\n\n")

		if ext.Suffix != "" {
			fmt.Fprintf(buf, "\tsuffix := []byte(%q)\n", ext.Suffix)
			buf.WriteString("\tvar end int\n")
			buf.WriteString(
				"\tif len(suffix) == 1 {\n\t\tend = bytes.IndexByte(bodyBytes[start:], suffix[0])\n\t} else {\n\t\tend = bytes.Index(bodyBytes[start:], suffix)\n\t}\n",
			)
			buf.WriteString("\tif end == -1 {\n\t\treturn nil, errors.New(\"extract: suffix not found\")\n\t}\n\n")
			fmt.Fprintf(buf, "\tvar result %s\n", resultType)
			buf.WriteString(
				"\tif err := json.Unmarshal(bodyBytes[start:start+end], &result); err != nil {\n\t\treturn nil, fmt.Errorf(\"extract: failed to unmarshal payload: %w\", err)\n\t}\n\n",
			)
		} else {
			fmt.Fprintf(buf, "\tvar result %s\n", resultType)
			buf.WriteString(
				"\tif err := json.Unmarshal(bodyBytes[start:], &result); err != nil {\n\t\treturn nil, fmt.Errorf(\"extract: failed to unmarshal payload: %w\", err)\n\t}\n\n",
			)
		}

		buf.WriteString("\treturn &result, nil\n")

	case ir.ExtractHTMLToken:
		buf.WriteString("\tbodyBytes, err := io.ReadAll(resp.Body)\n")
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")

		if ext.ID != "" {
			fmt.Fprintf(buf, "\tstart := bytes.Index(bodyBytes, []byte(%q))\n", ext.ID)
			buf.WriteString(
				"\tif start == -1 {\n\t\treturn nil, errors.New(\"extract: target element not found\")\n\t}\n",
			)

			if ext.Attr != "" {
				fmt.Fprintf(buf, "\tattrIdx := bytes.Index(bodyBytes[start:], []byte(%q))\n", ext.Attr+"=")
				buf.WriteString(
					"\tif attrIdx == -1 {\n\t\treturn nil, errors.New(\"extract: attribute not found\")\n\t}\n",
				)
				fmt.Fprintf(buf, "\tstart = start + attrIdx + len(%q)\n", ext.Attr+"=")
				buf.WriteString(
					"\tif start >= len(bodyBytes) {\n\t\treturn nil, errors.New(\"extract: unexpected EOF\")\n\t}\n",
				)
				buf.WriteString("\tquote := bodyBytes[start]\n")
				buf.WriteString("\tstart++\n")
				buf.WriteString("\tend := bytes.IndexByte(bodyBytes[start:], quote)\n")
				buf.WriteString(
					"\tif end == -1 {\n\t\treturn nil, errors.New(\"extract: attribute boundary not found\")\n\t}\n\n",
				)
			} else {
				fmt.Fprintf(buf, "\tstart += len(%q)\n", ext.ID)
				buf.WriteString("\tend := bytes.IndexByte(bodyBytes[start:], '\"')\n")
				buf.WriteString("\tif end == -1 { end = bytes.IndexByte(bodyBytes[start:], 0x27) }\n")
				buf.WriteString(
					"\tif end == -1 {\n\t\treturn nil, errors.New(\"extract: attribute boundary not found\")\n\t}\n\n",
				)
			}
		} else if ext.Attr != "" {
			fmt.Fprintf(buf, "\tstart := bytes.Index(bodyBytes, []byte(%q))\n", ext.Attr+"=")
			buf.WriteString("\tif start == -1 {\n\t\treturn nil, errors.New(\"extract: attribute not found\")\n\t}\n")
			fmt.Fprintf(buf, "\tstart += len(%q)\n", ext.Attr+"=")
			buf.WriteString(
				"\tif start >= len(bodyBytes) {\n\t\treturn nil, errors.New(\"extract: unexpected EOF\")\n\t}\n",
			)
			buf.WriteString("\tquote := bodyBytes[start]\n")
			buf.WriteString("\tstart++\n")
			buf.WriteString("\tend := bytes.IndexByte(bodyBytes[start:], quote)\n")
			buf.WriteString(
				"\tif end == -1 {\n\t\treturn nil, errors.New(\"extract: attribute boundary not found\")\n\t}\n\n",
			)
		}

		fmt.Fprintf(buf, "\tvar result %s\n", resultType)
		buf.WriteString(
			"\tunescaped := bytes.ReplaceAll(bodyBytes[start:start+end], []byte(\"&quot;\"), []byte(\"\\\"\"))\n",
		)
		buf.WriteString(
			"\tif err := json.Unmarshal(unescaped, &result); err != nil {\n\t\treturn nil, fmt.Errorf(\"extract: failed to unmarshal payload: %w\", err)\n\t}\n\n",
		)
		buf.WriteString("\treturn &result, nil\n")
	}
}

func (e *Emitter) emitEnvelopeUnwrap(
	buf *bytes.Buffer,
	m *ir.MethodIR,
	targetReq, rawPath string,
	bodyParam *ir.ParamIR,
) {
	successType := m.Return.SuccessType.Name

	fieldName := strings.ToUpper(m.UnwrapField[:1]) + m.UnwrapField[1:]

	buf.WriteString("\ttype envelope struct {\n")
	buf.WriteString("\t\tSuccess bool `json:\"success\"`\n")
	fmt.Fprintf(buf, "\t\t%s %s `json:\"%s\"`\n", fieldName, successType, m.UnwrapField)
	buf.WriteString("\t\tErrorMsg string `json:\"error,omitempty\"`\n")
	buf.WriteString("\t}\n\n")

	if m.HTTPMethod == "POST" {
		bodyArg := "nil"
		if bodyParam != nil {
			bodyArg = bodyParam.GoName
		}

		fmt.Fprintf(
			buf,
			"\tresp, err := request.PostTo[envelope](ctx, %s, %q, %s, allMods...)\n",
			targetReq,
			rawPath,
			bodyArg,
		)
	} else {
		fmt.Fprintf(buf, "\tresp, err := request.GetTo[envelope](ctx, %s, %q, allMods...)\n", targetReq, rawPath)
	}

	buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	buf.WriteString("\tif !resp.Success && resp.ErrorMsg != \"\" {\n\t\treturn nil, errors.New(resp.ErrorMsg)\n\t}\n")
	fmt.Fprintf(buf, "\treturn resp.%s, nil\n", fieldName)
}

func (e *Emitter) emitChecks(buf *bytes.Buffer, m *ir.MethodIR) {
	for _, chk := range m.Checks {
		fieldGoName := toPascalCase(chk.Field)

		cond := "!resp." + fieldGoName
		if chk.ExpectedVal != "true" {
			switch chk.Operator {
			case ir.OpEqual:
				cond = fmt.Sprintf("resp.%s != %s", fieldGoName, chk.ExpectedVal)
			case ir.OpNotEqual:
				cond = fmt.Sprintf("resp.%s == %s", fieldGoName, chk.ExpectedVal)
			default:
				cond = fmt.Sprintf("!(resp.%s %s %s)", fieldGoName, chk.Operator, chk.ExpectedVal)
			}
		}

		fmt.Fprintf(buf, "\tif %s {\n", cond)
		fmt.Fprintf(buf, "\t\treturn nil, errors.New(%q)\n", chk.ErrorMsg)
		buf.WriteString("\t}\n")
	}
}

func (e *Emitter) emitStruct(buf *bytes.Buffer, s *ir.StructIR) {
	// Emit AppendFormData & AppendQuery methods for zero-alloc serialization
	if s.GenValueEncoder {
		fmt.Fprintf(
			buf,
			"// AppendFormData serializes %s into url-encoded form bytes on dst buffer (0 B/op).\n",
			s.Name,
		)
		fmt.Fprintf(buf, "func (r *%s) AppendFormData(dst []byte) []byte {\n", s.Name)
		buf.WriteString("\tif r == nil {\n\t\treturn dst\n\t}\n\n")

		for _, f := range s.Fields {
			switch f.Type.Name {
			case "string":
				fmt.Fprintf(buf, "\tif r.%s != \"\" {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = append(dst, url.QueryEscape(r.%s)...)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "int", "int64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "uint", "uint32", "uint64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendUint(dst, uint64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "time.Time":
				fmt.Fprintf(buf, "\tif !r.%s.IsZero() {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(
					buf,
					"\t\tdst = append(dst, url.QueryEscape(r.%s.Format(time.RFC3339))...)\n",
					f.GoName,
				)
				buf.WriteString("\t}\n")

			case "bool":
				fmt.Fprintf(buf, "\tif r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")

				switch f.Formatter {
				case ir.FormatBoolInt:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=1")
				case ir.FormatBoolFlag:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName)
				default:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=true")
				}

				buf.WriteString("\t}\n")

			case "[]int", "[]int64":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(v), 10)\n")
				buf.WriteString("\t}\n")

			case "[]string":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = append(dst, url.QueryEscape(v)...)\n")
				buf.WriteString("\t}\n")

			case "any", "interface{}":
				fmt.Fprintf(buf, "\tif r.%s != nil {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = append(dst, fmt.Sprint(r.%s)...)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "values.Int64String", "values.Uint64String", "values.Float64String", "values.BoolInt":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			default:
				if strings.HasPrefix(f.Type.Name, "[]") || strings.HasPrefix(f.Type.Name, "map[") {
					continue
				}

				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")
			}
		}

		buf.WriteString("\n\treturn dst\n}\n\n")

		fmt.Fprintf(buf, "// AppendQuery serializes %s into query string bytes on dst buffer (0 B/op).\n", s.Name)
		fmt.Fprintf(buf, "func (r *%s) AppendQuery(dst []byte) []byte {\n", s.Name)
		buf.WriteString("\treturn r.AppendFormData(dst)\n}\n\n")

		// Also emit EncodeValues for url.Values interoperability
		fmt.Fprintf(buf, "// EncodeValues serializes %s into url.Values without reflection.\n", s.Name)
		fmt.Fprintf(buf, "func (r *%s) EncodeValues(vals url.Values) {\n", s.Name)
		buf.WriteString("\tif r == nil {\n\t\treturn\n\t}\n")

		for _, f := range s.Fields {
			switch f.Type.Name {
			case "string":
				fmt.Fprintf(buf, "\tif r.%s != \"\" {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, r.%s)\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "int", "int64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatInt(int64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "uint", "uint32", "uint64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatUint(uint64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "bool":
				fmt.Fprintf(buf, "\tif r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, \"true\")\n", f.WireName)
				buf.WriteString("\t}\n")
			case "[]int", "[]int64":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Add(%q, strconv.FormatInt(int64(v), 10))\n", f.WireName)
				buf.WriteString("\t}\n")
			case "[]string":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Add(%q, v)\n", f.WireName)
				buf.WriteString("\t}\n")
			case "any", "interface{}":
				fmt.Fprintf(buf, "\tif r.%s != nil {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, fmt.Sprint(r.%s))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "values.Int64String", "values.Uint64String", "values.Float64String", "values.BoolInt":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatInt(int64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			default:
				if strings.HasPrefix(f.Type.Name, "[]") || strings.HasPrefix(f.Type.Name, "map[") {
					continue
				}

				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatInt(int64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			}
		}

		buf.WriteString("}\n\n")
	}
}

func (e *Emitter) emitTuple(buf *bytes.Buffer, t *ir.TupleIR) {
	n := len(t.Fields)
	fmt.Fprintf(buf, "// UnmarshalJSON decodes a heterogeneous JSON array tuple into %s.\n", t.Name)
	fmt.Fprintf(buf, "func (t *%s) UnmarshalJSON(data []byte) error {\n", t.Name)
	fmt.Fprintf(buf, "\tvar raw [%d]json.RawMessage\n", n)
	buf.WriteString("\tif err := json.Unmarshal(data, &raw); err != nil {\n\t\treturn err\n\t}\n")

	for i, f := range t.Fields {
		fmt.Fprintf(buf, "\t_ = json.Unmarshal(raw[%d], &t.%s)\n", i, f.GoName)
	}

	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")
}

func emitSliceElementFormat(buf *bytes.Buffer, elemType, targetBuf, valVar string) {
	elemType = strings.TrimPrefix(elemType, "*")
	switch elemType {
	case "string":
		fmt.Fprintf(buf, "\t\t%s = append(%s, url.QueryEscape(%s)...)\n", targetBuf, targetBuf, valVar)
	case "int", "int8", "int16", "int32", "int64":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendInt(%s, int64(%s), 10)\n", targetBuf, targetBuf, valVar)
	case "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendUint(%s, uint64(%s), 10)\n", targetBuf, targetBuf, valVar)
	case "bool":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendBool(%s, %s)\n", targetBuf, targetBuf, valVar)
	default:
		fmt.Fprintf(buf, "\t\t%s = append(%s, url.QueryEscape(fmt.Sprint(%s))...)\n", targetBuf, targetBuf, valVar)
	}
}
