// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package emitter

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"

	"github.com/lemon4ksan/aoni/internal/codegen/ir"
)

// Emitter generates pure Go code from a normalized IR.
type Emitter struct{}

// NewEmitter creates a new Emitter instance.
func NewEmitter() *Emitter {
	return &Emitter{}
}

// Emit compiles RootIR into formatted Go source code bytes.
func (e *Emitter) Emit(root *ir.RootIR) ([]byte, error) {
	if root == nil {
		return nil, errors.New("aoni/codegen/emitter: root IR is nil")
	}

	var buf bytes.Buffer

	// 1. File header & Package
	buf.WriteString("// Code generated by vortex. DO NOT EDIT.\n")
	buf.WriteString("// versions:\n")
	buf.WriteString("// \tvortex v0.6.0\n")

	if root.SourceFile != "" {
		fmt.Fprintf(&buf, "// source: %s\n", filepath.Base(filepath.ToSlash(root.SourceFile)))
	}

	buf.WriteString("\npackage ")
	buf.WriteString(root.PackageName)
	buf.WriteString("\n\n")

	var bodyBuf bytes.Buffer

	// 3. Services (Client struct, Constructor, Methods)
	for _, svc := range root.Services {
		e.emitService(&bodyBuf, root, svc)
	}

	// 4. DTO Structs & Encoders
	for _, strct := range root.Structs {
		e.emitStruct(&bodyBuf, strct)
	}

	// 5. Tuples UnmarshalJSON
	for _, tuple := range root.Tuples {
		e.emitTuple(&bodyBuf, tuple)
	}

	bodyCode := bodyBuf.String()

	// 2. Imports block
	e.emitImports(&buf, root, bodyCode)

	buf.WriteString(bodyCode)

	// Format generated Go source
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("aoni/codegen/emitter: go/format error: %w\nSource:\n%s", err, buf.String())
	}

	return formatted, nil
}

func (e *Emitter) emitImports(buf *bytes.Buffer, root *ir.RootIR, bodyCode string) {
	buf.WriteString("import (\n")

	stdList := collectStdImports(root, bodyCode)
	for _, pkg := range stdList {
		fmt.Fprintf(buf, "\t\"%s\"\n", pkg)
	}

	hasHTTP := false

	hasFastClient := false
	if root != nil {
		for _, svc := range root.Services {
			if svc.Protocol != ir.ProtocolRPC && svc.Protocol != ir.ProtocolChannel &&
				svc.Protocol != ir.ProtocolSocket {
				hasHTTP = true

				isStrict := svc.Engine == ir.EngineRequired || svc.RequesterType != ""
				if !isStrict && svc.Engine != ir.EngineNetHTTP && svc.Engine != ir.EngineCustom {
					hasFastClient = true
				}
			}
		}
	}

	if hasHTTP {
		buf.WriteString("\n\t\"github.com/lemon4ksan/aoni\"\n")

		if hasFastClient {
			buf.WriteString("\t\"github.com/lemon4ksan/aoni/fast\"\n")
		}
	} else {
		buf.WriteString("\n")
	}

	hasDecode := false

	hasCodec := false
	if root != nil {
		for _, svc := range root.Services {
			for _, m := range svc.Methods {
				if m.Decoder != "" {
					hasDecode = true
				}

				if m.ReturnPipeline != nil {
					for _, st := range m.ReturnPipeline.Stages {
						if st.Type == ir.StageJSON || st.Type == ir.StageAttr || st.Type == ir.StageBetween ||
							st.Type == ir.StageHTMLUnescape {
							hasDecode = true
						}
					}
				}

				if m.Codec != "" {
					hasCodec = true
				}
			}
		}
	}

	if hasCodec {
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/codec\"\n")
	}

	if hasDecode {
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/codec/decode\"\n")
	}

	if hasHTTP {
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/mod\"\n")
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/option\"\n")
	}

	hasRequest := false
	if root != nil {
		for _, svc := range root.Services {
			if svc.Protocol != ir.ProtocolRPC && svc.Protocol != ir.ProtocolChannel &&
				svc.Protocol != ir.ProtocolSocket {
				hasRequest = true
			} else if svc.Protocol != ir.ProtocolSocket &&
				(svc.RequesterType == "" || strings.Contains(svc.RequesterType, "request.")) {
				hasRequest = true
			}
		}
	}

	if hasRequest {
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/request\"\n")
	}

	hasProto := false
	if root != nil {
		for _, svc := range root.Services {
			for _, m := range svc.Methods {
				for _, p := range m.Params {
					if strings.Contains(p.GoType.ElemType, "pb.") || strings.Contains(p.GoType.ElemType, "CMsg") ||
						strings.Contains(p.GoType.ElemType, "proto.") ||
						strings.Contains(p.GoType.Name, "pb.") ||
						strings.Contains(p.GoType.Name, "CMsg") ||
						strings.Contains(p.GoType.Name, "proto.") {
						hasProto = true
					}
				}

				if m.Return != nil &&
					(strings.Contains(m.Return.SuccessType.Name, "pb.") || strings.Contains(m.Return.SuccessType.Name, "CMsg")) {
					hasProto = true
				}

				if m.ReturnPipeline != nil {
					for _, st := range m.ReturnPipeline.Stages {
						if st.Type == ir.StageProto {
							hasProto = true
						}
					}
				}

				if m.BodyPipeline != nil {
					for _, st := range m.BodyPipeline.Stages {
						if st.Type == ir.StageProto {
							hasProto = true
						}
					}
				}
			}
		}
	}

	if hasProto {
		buf.WriteString("\t\"google.golang.org/protobuf/proto\"\n")
	}

	hasSocket := false
	if root != nil {
		for _, svc := range root.Services {
			if svc.Protocol == ir.ProtocolSocket {
				hasSocket = true
				break
			}
		}
	}

	if hasSocket {
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/realtime/socket\"\n")
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/realtime/socket/connector\"\n")
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/realtime/socket/dispatcher\"\n")
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/realtime/socket/processor\"\n")
	}

	// User custom imports (exclude standard imports already emitted)
	stdImports := map[string]bool{
		"bytes": true, "context": true, "encoding/json": true, "errors": true,
		"fmt": true, "io": true, "mime/multipart": true, "net/http": true,
		"net/textproto": true, "net/url": true, "os": true, "regexp": true,
		"strconv": true, "strings": true, "sync": true, "sync/atomic": true, "time": true,
	}

	for _, imp := range root.Imports {
		if stdImports[imp.Path] || strings.Contains(imp.Path, "github.com/lemon4ksan/aoni") {
			continue
		}

		ref := imp.Alias
		if ref == "" {
			parts := strings.Split(imp.Path, "/")
			ref = parts[len(parts)-1]
		}

		if !strings.Contains(bodyCode, ref+".") {
			continue
		}

		if imp.Alias != "" {
			fmt.Fprintf(buf, "\t%s \"%s\"\n", imp.Alias, imp.Path)
		} else {
			fmt.Fprintf(buf, "\t\"%s\"\n", imp.Path)
		}
	}

	buf.WriteString(")\n\n")
}

func collectStdImports(root *ir.RootIR, bodyCode string) []string {
	needed := make(map[string]bool)

	hasContext := false
	hasEvents := false
	hasExplicitClose := false

	if root != nil {
		for _, svc := range root.Services {
			if svc.Engine == ir.EngineNetHTTP {
				needed["net/http"] = true
			}

			if svc.Protocol == ir.ProtocolSocket {
				needed["context"] = true
				needed["errors"] = true
				needed["sync"] = true
				needed["sync/atomic"] = true
				needed["time"] = true
			}

			if svc.Protocol == ir.ProtocolRPC || svc.Protocol == ir.ProtocolChannel {
				for _, m := range svc.Methods {
					if m.IsEvent || m.Operation == ir.OpEvent {
						hasEvents = true
					}

					if m.Name == "Close" {
						hasExplicitClose = true
					}
				}
			}

			for _, m := range svc.Methods {
				if m.Return != nil && m.Return.HasRawResponse {
					needed["net/http"] = true
				}

				if m.Return != nil && (m.Return.IsDirectBytes || m.Return.SuccessType.Name == "[]byte") {
					needed["net/http"] = true
					needed["io"] = true
				}

				if m.Return != nil &&
					(m.Return.SuccessType.Name == "io.ReadCloser" || m.Return.SuccessType.Name == "io.Reader") {
					needed["net/http"] = true
				}

				if m.ReturnPipeline != nil && m.Operation != ir.OpRPC && m.Operation != ir.OpEvent &&
					m.Operation != ir.OpNotify {
					needed["net/http"] = true
				}

				for _, p := range m.Params {
					if p.Location == ir.LocContext || p.GoType.Name == "context.Context" {
						hasContext = true
					}

					if strings.Contains(p.GoType.Name, "http.") {
						needed["net/http"] = true
					}
				}
			}
		}
	}

	if hasEvents || hasExplicitClose {
		needed["sync"] = true
	}

	if hasContext {
		needed["context"] = true
	}

	for _, svc := range root.Services {
		if svc.Protocol == ir.ProtocolSocket {
			continue
		}

		if svc.Engine == ir.EngineRequired ||
			(svc.Protocol != ir.ProtocolRPC && svc.Protocol != ir.ProtocolChannel && svc.RequesterType != "") {
			needed["errors"] = true
		}

		for _, m := range svc.Methods {
			if m.Return != nil {
				if strings.Contains(m.Return.SuccessType.Name, "io.") || m.Return.IsStreamChan {
					needed["io"] = true
				}

				if strings.Contains(m.Return.SuccessType.Name, "json.") {
					needed["encoding/json"] = true
				}
			}

			if m.ReturnPipeline != nil && m.Operation != ir.OpRPC && m.Operation != ir.OpEvent &&
				m.Operation != ir.OpNotify {
				needed["io"] = true
				needed["fmt"] = true
				needed["errors"] = true
			}

			for _, p := range m.Params {
				if p.Pipeline != nil || p.Formatter == ir.FormatJSONString || strings.Contains(p.GoType.Name, "json.") {
					needed["encoding/json"] = true
				}
			}

			if m.PayloadKind == ir.PayloadMultipart {
				needed["bytes"] = true
				needed["mime/multipart"] = true
				needed["net/textproto"] = true
				needed["fmt"] = true
			}

			hasFieldInject := false
			for _, inj := range m.Injects {
				if inj.Target == ir.InjectField {
					hasFieldInject = true
				}

				needed["net/url"] = true
			}

			if m.PayloadKind == ir.PayloadForm || hasFieldInject {
				needed["net/url"] = true
			}

			for _, h := range m.Headers {
				if h.DynamicTemplate != nil {
					needed["net/url"] = true

					needed["strconv"] = true
					for _, seg := range h.DynamicTemplate.Segments {
						if seg.IsVariable {
							if seg.Transform == ir.TransformLower || seg.Transform == ir.TransformUpper {
								needed["strings"] = true
							}
						}
					}
				}
			}

			if m.SignHMAC != nil && m.SignHMAC.KeyEnv != "" {
				needed["os"] = true
			}

			if m.UnwrapField != "" {
				needed["errors"] = true
			}

			for _, p := range m.Params {
				if p.Location == ir.LocQuery || p.Location == ir.LocFormFields {
					needed["net/url"] = true
					if p.Formatter == ir.FormatJSONString {
						needed["encoding/json"] = true
					}

					if p.Formatter == ir.FormatIntAppend || p.Formatter == ir.FormatUintAppend ||
						p.Formatter == ir.FormatBoolAppend {
						needed["strconv"] = true
					}

					if p.Formatter != ir.FormatCompiledEncode && p.GoType.Name != "string" && !p.GoType.IsSlice &&
						p.GoType.Name != "" {
						needed["fmt"] = true
					}

					if p.Formatter == ir.FormatTimeRFC3339 || p.Formatter == ir.FormatTimeUnixS ||
						p.Formatter == ir.FormatTimeUnixMS ||
						p.Formatter == ir.FormatTimeLayout {
						needed["time"] = true
						needed["strconv"] = true
					}
				}
			}
		}
	}

	hasSocketOnly := len(root.Services) > 0
	for _, svc := range root.Services {
		if svc.Protocol != ir.ProtocolSocket {
			hasSocketOnly = false
		}
	}

	if !hasSocketOnly {
		for _, s := range root.Structs {
			for _, f := range s.Fields {
				if f.Type.Name == "time.Time" {
					needed["time"] = true
				}

				if strings.HasPrefix(f.Type.Name, "int") || strings.HasPrefix(f.Type.Name, "uint") {
					needed["strconv"] = true
				}

				needed["net/url"] = true
			}
		}

		for range root.Tuples {
			needed["encoding/json"] = true
			needed["fmt"] = true
		}
	}

	qualifiers := map[string]string{
		"bytes":          "bytes.",
		"context":        "context.",
		"encoding/json":  "json.",
		"errors":         "errors.",
		"fmt":            "fmt.",
		"io":             "io.",
		"mime/multipart": "multipart.",
		"net/http":       "http.",
		"net/textproto":  "textproto.",
		"net/url":        "url.",
		"os":             "os.",
		"regexp":         "regexp.",
		"strconv":        "strconv.",
		"sync":           "sync.",
		"sync/atomic":    "atomic.",
		"time":           "time.",
	}

	for pkg, qual := range qualifiers {
		if strings.Contains(bodyCode, qual) {
			needed[pkg] = true
		}
	}

	order := []string{
		"bytes", "context", "encoding/json", "errors", "fmt", "io",
		"mime/multipart", "net/http", "net/textproto", "net/url", "os", "regexp",
		"strconv", "sync", "sync/atomic", "time",
	}

	var res []string
	for _, pkg := range order {
		if needed[pkg] {
			if q, ok := qualifiers[pkg]; ok && !strings.Contains(bodyCode, q) {
				continue
			}

			res = append(res, pkg)
		}
	}

	return res
}

func zeroValueOf(ret *ir.ReturnIR) string {
	if ret == nil || ret.IsVoid {
		return ""
	}

	t := ret.SuccessType.Name
	switch {
	case strings.HasPrefix(t, "*") || strings.HasPrefix(t, "[]") || strings.HasPrefix(t, "map[") || t == "any" || t == "interface{}":
		return "nil"
	case t == "string":
		return `""`
	case t == "bool":
		return "false"
	case t == "int", t == "int8", t == "int16", t == "int32", t == "int64",
		t == "uint", t == "uint8", t == "uint16", t == "uint32", t == "uint64", t == "uintptr",
		t == "float32", t == "float64", t == "byte", t == "rune":
		return "0"
	default:
		return t + "{}"
	}
}

func isCompiledDTO(root *ir.RootIR, typeName string) bool {
	if root == nil {
		return false
	}

	typeName = strings.TrimPrefix(typeName, "*")
	for _, s := range root.Structs {
		if s.Name == typeName {
			return true
		}
	}

	return false
}

func (e *Emitter) emitService(buf *bytes.Buffer, root *ir.RootIR, svc *ir.ServiceIR) {
	if svc.Protocol == ir.ProtocolSocket {
		e.emitSocketService(buf, root, svc)
		return
	}

	clientStructName := lowerFirst(svc.Name) + "Client"

	if svc.Protocol == ir.ProtocolRPC || svc.Protocol == ir.ProtocolChannel {
		reqArgType := "request.Transport"
		if svc.RequesterType != "" {
			reqArgType = svc.RequesterType
		}

		hasEvents := false

		hasExplicitClose := false
		for _, m := range svc.Methods {
			if m.IsEvent || m.Operation == ir.OpEvent {
				hasEvents = true
			}

			if m.Name == "Close" {
				hasExplicitClose = true
			}
		}

		fmt.Fprintf(buf, "type %s struct {\n", clientStructName)
		fmt.Fprintf(buf, "\ttransport %s\n", reqArgType)

		if hasEvents || hasExplicitClose {
			buf.WriteString("\tmu        sync.Mutex\n")
			buf.WriteString("\tunregs    []func()\n")
		}

		buf.WriteString("}\n\n")

		constructorName := "New" + svc.Name
		if svc.Name == "Client" || svc.Name == "API" {
			constructorName = "New"
		}

		mustConstructorName := "Must" + constructorName

		fmt.Fprintf(
			buf,
			"// %s creates a new %s client instance backed by a transport.\n",
			constructorName,
			svc.Name,
		)
		fmt.Fprintf(
			buf,
			"func %s(transport %s) %s {\n",
			constructorName,
			reqArgType,
			svc.Name,
		)
		fmt.Fprintf(buf, "\treturn &%s{\n\t\ttransport: transport,\n\t}\n}\n\n", clientStructName)

		fmt.Fprintf(
			buf,
			"// %s initializes %s.\n",
			mustConstructorName,
			svc.Name,
		)
		fmt.Fprintf(
			buf,
			"func %s(transport %s) %s {\n",
			mustConstructorName,
			reqArgType,
			svc.Name,
		)
		fmt.Fprintf(buf, "\treturn %s(transport)\n}\n\n", constructorName)

		for _, m := range svc.Methods {
			if m.Name != "Close" {
				e.emitMethod(buf, root, svc, clientStructName, m)
			}
		}

		if hasEvents || hasExplicitClose {
			fmt.Fprintf(buf, "// Close unsubscribes all active event listeners.\n")
			fmt.Fprintf(buf, "func (c *%s) Close() error {\n", clientStructName)
			buf.WriteString("\tc.mu.Lock()\n")
			buf.WriteString("\tfor _, unreg := range c.unregs {\n")
			buf.WriteString("\t\tunreg()\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\tc.unregs = nil\n")
			buf.WriteString("\tc.mu.Unlock()\n")
			buf.WriteString("\treturn nil\n")
			buf.WriteString("}\n\n")
		}

		return
	}

	// 1. Client Struct
	fmt.Fprintf(buf, "type %s struct {\n", clientStructName)

	for _, sub := range svc.SubRequesters {
		fmt.Fprintf(buf, "\t%s request.Requester\n", sub.FieldName)
	}

	buf.WriteString("}\n\n")

	// 2. Factory Constructor
	constructorName := "New" + svc.Name
	mustConstructorName := "Must" + constructorName

	isStrict := svc.Engine == ir.EngineRequired || svc.RequesterType != ""

	reqArgType := "aoni.RequestDoer"
	if svc.RequesterType != "" {
		reqArgType = svc.RequesterType
	}

	if isStrict {
		fmt.Fprintf(
			buf,
			"// %s creates a new %s client instance backed by an authenticated %s.\n",
			constructorName,
			svc.Name,
			reqArgType,
		)
		fmt.Fprintf(
			buf,
			"func %s(client %s, opts ...aoni.ClientOption) (%s, error) {\n",
			constructorName,
			reqArgType,
			svc.Name,
		)
		fmt.Fprintf(
			buf,
			"\tif client == nil {\n\t\treturn nil, errors.New(\"aoni: client (%s) is required to initialize %s\")\n\t}\n\n",
			reqArgType,
			svc.Name,
		)

		// Base options
		buf.WriteString("\tvar baseOpts []aoni.ClientOption\n")

		for _, h := range svc.Headers {
			if h.DynamicTemplate == nil && h.StaticValue != "" {
				if strings.EqualFold(h.Key, "User-Agent") {
					fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithUserAgent(%q))\n", h.StaticValue)
				} else {
					fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithHeader(%q, %q))\n", h.Key, h.StaticValue)
				}
			}
		}

		if svc.Persona != "" {
			fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithPersona(%q))\n", svc.Persona)
		}

		if svc.Timeout != "" {
			fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithTimeoutString(%q))\n", svc.Timeout)
		}

		buf.WriteString("\tbaseOpts = append(baseOpts, opts...)\n\n")

		// If preconfigured requester is passed without new options, reuse directly
		buf.WriteString("\tif req, ok := any(client).(request.Requester); ok && len(opts) == 0 {\n")
		fmt.Fprintf(buf, "\t\treturn &%s{\n", clientStructName)

		for _, sub := range svc.SubRequesters {
			fmt.Fprintf(buf, "\t\t\t%s: req,\n", sub.FieldName)
		}

		buf.WriteString("\t\t}, nil\n\t}\n\n")

		// Target requester resolution
		buf.WriteString("\tvar targetReq request.Requester\n")
		buf.WriteString("\tif d, ok := any(client).(aoni.RequestDoer); ok {\n")
		fmt.Fprintf(
			buf,
			"\t\ttargetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...))\n",
			svc.BaseURL,
		)
		buf.WriteString("\t} else if req, ok := any(client).(request.Requester); ok {\n")
		buf.WriteString("\t\ttargetReq = req\n")
		buf.WriteString(
			"\t} else if rd, ok := any(client).(interface{ Rest() request.Requester }); ok && rd.Rest() != nil {\n",
		)
		buf.WriteString("\t\ttargetReq = rd.Rest()\n")
		buf.WriteString(
			"\t} else if rd, ok := any(client).(interface{ Requester() request.Requester }); ok && rd.Requester() != nil {\n",
		)
		buf.WriteString("\t\ttargetReq = rd.Requester()\n")
		buf.WriteString("\t} else {\n")
		buf.WriteString("\t\treturn nil, errors.New(\"aoni: unsupported requester interface\")\n")
		buf.WriteString("\t}\n\n")

		// Instantiate SubRequesters
		fmt.Fprintf(buf, "\treturn &%s{\n", clientStructName)

		for _, sub := range svc.SubRequesters {
			fmt.Fprintf(buf, "\t\t%s: targetReq,\n", sub.FieldName)
		}

		buf.WriteString("\t}, nil\n}\n\n")

		// MustNew helper
		fmt.Fprintf(
			buf,
			"// %s initializes %s and panics if an error occurs.\n",
			mustConstructorName,
			svc.Name,
		)
		fmt.Fprintf(
			buf,
			"func %s(client %s, opts ...aoni.ClientOption) %s {\n",
			mustConstructorName,
			reqArgType,
			svc.Name,
		)
		fmt.Fprintf(buf, "\tapi, err := %s(client, opts...)\n", constructorName)
		buf.WriteString("\tif err != nil {\n\t\tpanic(err)\n\t}\n")
		buf.WriteString("\treturn api\n}\n\n")

		// Underlying requester getter
		fmt.Fprintf(buf, "// R returns the underlying request.Requester used by the client.\n")
		fmt.Fprintf(buf, "func (c *%s) R() request.Requester {\n\treturn c.r\n}\n\n", clientStructName)

		// Methods
		for _, m := range svc.Methods {
			e.emitMethod(buf, root, svc, clientStructName, m)
		}

		return
	}

	internalConstructorName := "new" + svc.Name

	fmt.Fprintf(buf, "func %s(doer any, opts ...aoni.ClientOption) *%s {\n", internalConstructorName, clientStructName)
	buf.WriteString("\tif doer == nil {\n")

	switch svc.Engine {
	case ir.EngineNetHTTP:
		buf.WriteString("\t\tdoer = aoni.NewClient(nil)\n")
	case ir.EngineCustom:
		fmt.Fprintf(buf, "\t\tpanic(\"aoni: custom RequestDoer is required to initialize %s\")\n", svc.Name)
	default:
		buf.WriteString("\t\tdoer = fast.NewClient()\n")
	}

	buf.WriteString("\t}\n\n")

	// Base options
	buf.WriteString("\tvar baseOpts []aoni.ClientOption\n")

	for _, h := range svc.Headers {
		if h.DynamicTemplate == nil && h.StaticValue != "" {
			if strings.EqualFold(h.Key, "User-Agent") {
				fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithUserAgent(%q))\n", h.StaticValue)
			} else {
				fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithHeader(%q, %q))\n", h.Key, h.StaticValue)
			}
		}
	}

	if svc.Persona != "" {
		fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithPersona(%q))\n", svc.Persona)
	}

	if svc.Timeout != "" {
		fmt.Fprintf(buf, "\tbaseOpts = append(baseOpts, option.WithTimeoutString(%q))\n", svc.Timeout)
	}

	buf.WriteString("\tbaseOpts = append(baseOpts, opts...)\n\n")

	// Target requester resolution
	buf.WriteString("\tvar targetReq request.Requester\n")
	buf.WriteString("\tif d, ok := doer.(aoni.RequestDoer); ok {\n")
	fmt.Fprintf(
		buf,
		"\t\ttargetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...))\n",
		svc.BaseURL,
	)
	buf.WriteString("\t} else if req, ok := doer.(request.Requester); ok {\n")
	fmt.Fprintf(
		buf,
		"\t\ttargetReq = request.AsRequester(aoni.Configure(req, append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...))\n",
		svc.BaseURL,
	)
	buf.WriteString("\t} else if rd, ok := doer.(interface{ Rest() request.Requester }); ok && rd.Rest() != nil {\n")
	buf.WriteString("\t\ttargetReq = rd.Rest()\n")
	buf.WriteString(
		"\t} else if rd, ok := doer.(interface{ Requester() request.Requester }); ok && rd.Requester() != nil {\n",
	)
	buf.WriteString("\t\ttargetReq = rd.Requester()\n")
	buf.WriteString("\t} else {\n")
	fmt.Fprintf(
		buf,
		"\t\ttargetReq = request.AsRequester(aoni.Configure(fast.NewClient(), append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...))\n",
		svc.BaseURL,
	)
	buf.WriteString("\t}\n\n")

	// Instantiate SubRequesters
	fmt.Fprintf(buf, "\treturn &%s{\n", clientStructName)

	for _, sub := range svc.SubRequesters {
		baseURL := sub.BaseURL
		if baseURL == "" {
			baseURL = svc.BaseURL
		}

		if sub.FieldName == "r" && baseURL == svc.BaseURL {
			fmt.Fprintf(buf, "\t\t%s: targetReq,\n", sub.FieldName)
		} else {
			fmt.Fprintf(
				buf,
				"\t\t%s: request.AsRequester(aoni.Configure(fast.NewClient(), append([]aoni.ClientOption{option.WithBaseURL(%q)}, baseOpts...)...)),\n",
				sub.FieldName,
				baseURL,
			)
		}
	}

	buf.WriteString("\t}\n}\n\n")

	// Public constructor
	fmt.Fprintf(
		buf,
		"// %s creates a new %s client instance with preconfigured execution pipelines.\n",
		constructorName,
		svc.Name,
	)
	fmt.Fprintf(buf, "func %s(doer any, opts ...aoni.ClientOption) %s {\n", constructorName, svc.Name)
	fmt.Fprintf(buf, "\treturn %s(doer, opts...)\n}\n\n", internalConstructorName)

	if svc.Name == "API" || svc.Name == "Client" {
		aliasName := "New"
		fmt.Fprintf(
			buf,
			"// %s creates a new %s client instance (alias for %s).\n",
			aliasName,
			svc.Name,
			constructorName,
		)
		fmt.Fprintf(buf, "func %s(doer any, opts ...aoni.ClientOption) %s {\n", aliasName, svc.Name)
		fmt.Fprintf(buf, "\treturn %s(doer, opts...)\n}\n\n", internalConstructorName)
	}

	// Underlying requester getter
	fmt.Fprintf(buf, "// R returns the underlying request.Requester used by the client.\n")
	fmt.Fprintf(buf, "func (c *%s) R() request.Requester {\n\treturn c.r\n}\n\n", clientStructName)

	// 3. Methods
	for _, m := range svc.Methods {
		e.emitMethod(buf, root, svc, clientStructName, m)
	}
}

func (e *Emitter) emitMethod(
	buf *bytes.Buffer,
	root *ir.RootIR,
	svc *ir.ServiceIR,
	clientStructName string,
	m *ir.MethodIR,
) {
	if m.Operation == ir.OpEvent || m.IsEvent {
		e.emitEventMethod(buf, root, svc, clientStructName, m)
		return
	}

	if m.Operation == ir.OpRPC || m.Operation == ir.OpNotify || m.OpID != "" {
		e.emitRPCMethod(buf, root, svc, clientStructName, m)
		return
	}

	paramsStr := formatMethodParams(m.Params)
	returnsStr := formatMethodReturns(m.Return)

	fmt.Fprintf(buf, "func (c *%s) %s(%s) %s {\n", clientStructName, m.Name, paramsStr, returnsStr)

	// Stack modifiers buffer
	stackSize := m.StackModsSize
	if stackSize < 4 {
		stackSize = 4
	}

	fmt.Fprintf(buf, "\tvar stackMods [%d]aoni.RequestModifier\n", stackSize)
	buf.WriteString("\tallMods := stackMods[:0]\n\n")

	// Build dynamic headers (e.g. Referer)
	for _, h := range m.Headers {
		switch {
		case h.DynamicTemplate != nil:
			e.emitDynamicHeader(buf, svc, m, &h)
		case strings.HasPrefix(h.StaticValue, ":"):
			e.emitKeywordHeader(buf, svc, m, &h)
		case h.StaticValue != "":
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, %q))\n", h.Key, h.StaticValue)
		}
	}

	// Build Query String on Stack Buffer if there are query parameters
	var (
		queryParams     []*ir.ParamIR
		pathParams      []*ir.ParamIR
		formParams      []*ir.ParamIR
		multipartParams []*ir.ParamIR
		bodyParam       *ir.ParamIR
		userModsParam   *ir.ParamIR
	)

	consumedFileVars := make(map[string]bool)
	for _, p := range m.Params {
		if p.Location == ir.LocMultipartFile {
			if strings.HasPrefix(p.FileName, "{") && strings.HasSuffix(p.FileName, "}") {
				v := strings.Trim(p.FileName, "{}")
				consumedFileVars[v] = true
				consumedFileVars[strings.ToLower(v)] = true
			}

			if strings.HasPrefix(p.ContentType, "{") && strings.HasSuffix(p.ContentType, "}") {
				v := strings.Trim(p.ContentType, "{}")
				consumedFileVars[v] = true
				consumedFileVars[strings.ToLower(v)] = true
			}
		}
	}

	for _, p := range m.Params {
		if consumedFileVars[p.GoName] || consumedFileVars[strings.ToLower(p.GoName)] {
			continue
		}

		switch p.Location {
		case ir.LocQuery, ir.LocQueryStruct:
			queryParams = append(queryParams, p)
		case ir.LocPath:
			pathParams = append(pathParams, p)
		case ir.LocFormFields:
			formParams = append(formParams, p)
		case ir.LocMultipartField, ir.LocMultipartFile:
			multipartParams = append(multipartParams, p)
		case ir.LocBody:
			bodyParam = p
		case ir.LocModifiers:
			userModsParam = p
		}
	}

	// Query buffer serialization
	var (
		stackQueryParams  []*ir.ParamIR
		structQueryParams []*ir.ParamIR
	)

	for _, p := range queryParams {
		if (p.Location == ir.LocQueryStruct || p.Formatter == ir.FormatCompiledEncode) &&
			!isCompiledDTO(root, p.GoType.Name) {
			structQueryParams = append(structQueryParams, p)
		} else {
			stackQueryParams = append(stackQueryParams, p)
		}
	}

	if len(stackQueryParams) > 0 {
		e.emitQueryBuffer(buf, m, stackQueryParams, m.StackBufSize)
	}

	for _, p := range structQueryParams {
		fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithQuery(%s))\n\n", p.GoName)
	}

	// Form body serialization
	hasFieldInject := false
	for _, inj := range m.Injects {
		if inj.Target == ir.InjectField {
			hasFieldInject = true
			break
		}
	}

	if m.PayloadKind == ir.PayloadForm && (len(formParams) > 0 || hasFieldInject) {
		e.emitFormBuffer(buf, m, formParams, m.StackBufSize)
	}

	// Multipart body serialization
	if m.PayloadKind == ir.PayloadMultipart && len(multipartParams) > 0 {
		e.emitMultipartBuffer(buf, multipartParams)
	}

	// Path variables
	for _, p := range pathParams {
		fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithVar(%q, %s))\n", p.WireKey, p.GoName)
	}

	// Append user variadic modifiers if provided
	if userModsParam != nil {
		fmt.Fprintf(buf, "\tif len(%s) > 0 {\n", userModsParam.GoName)
		fmt.Fprintf(buf, "\t\tallMods = append(allMods, %s...)\n", userModsParam.GoName)
		buf.WriteString("\t}\n")
	}

	buf.WriteString("\n")

	// Custom Decoder / Encoder modifiers
	if m.Decoder != "" {
		switch strings.ToLower(m.Decoder) {
		case "json", "xml", "proto", "grpc-web":
			// Handled natively by aoni codecs
		default:
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithDecoder(%s))\n", m.Decoder)
		}
	}

	if m.Encoder != "" {
		fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithEncoder(%s))\n", m.Encoder)
	}

	if m.Idempotent {
		buf.WriteString("\tallMods = append(allMods, mod.WithIdempotencyKey())\n")
	}

	if m.Coalesce {
		buf.WriteString("\tallMods = append(allMods, mod.WithCoalesce())\n")
	}

	if m.ETag {
		buf.WriteString("\tallMods = append(allMods, mod.WithETag())\n")
	}

	if m.SignHMAC != nil {
		if m.SignHMAC.KeyEnv != "" {
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithSignHMAC(os.Getenv(%q)))\n", m.SignHMAC.KeyEnv)
		} else {
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithSignHMAC(%q))\n", m.SignHMAC.SecretKey)
		}
	}

	// Target requester
	targetReq := m.TargetRequester
	if targetReq == "" {
		targetReq = "c.r"
	}

	rawPath := ""
	if m.Path != nil {
		rawPath = m.Path.RawTemplate
	}

	// Execute call
	e.emitExecution(buf, m, targetReq, rawPath, bodyParam)

	buf.WriteString("}\n\n")
}

func (e *Emitter) emitKeywordHeader(buf *bytes.Buffer, svc *ir.ServiceIR, m *ir.MethodIR, h *ir.HeaderIR) {
	kw := strings.ToLower(strings.TrimPrefix(h.StaticValue, ":"))

	baseURL := ""
	if svc != nil {
		baseURL = strings.TrimRight(svc.BaseURL, "/")
	}

	switch kw {
	case "origin", "base":
		if baseURL != "" {
			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, %q))\n", h.Key, baseURL+"/")
		} else {
			buf.WriteString("\tif buGetter, ok := any(c.r).(interface{ BaseURL() string }); ok {\n")
			fmt.Fprintf(buf, "\t\tallMods = append(allMods, mod.WithHeader(%q, buGetter.BaseURL()))\n", h.Key)
			buf.WriteString("\t}\n")
		}

	case "self":
		if m.Path != nil {
			targetURL := m.Path.RawTemplate
			if baseURL != "" && !strings.HasPrefix(targetURL, "http://") && !strings.HasPrefix(targetURL, "https://") {
				targetURL = baseURL + "/" + targetURL
			}

			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, %q))\n", h.Key, targetURL)
		}

	case "page":
		if m.Path != nil {
			pagePath := cleanPagePath(m.Path.RawTemplate)
			if baseURL != "" && !strings.HasPrefix(pagePath, "http://") && !strings.HasPrefix(pagePath, "https://") {
				pagePath = baseURL + "/" + pagePath
			}

			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, %q))\n", h.Key, pagePath)
		}

	case "parent":
		if m.Path != nil {
			parentPath := cleanParentPath(m.Path.RawTemplate)
			if baseURL != "" && !strings.HasPrefix(parentPath, "http://") &&
				!strings.HasPrefix(parentPath, "https://") {
				parentPath = baseURL + "/" + parentPath
			}

			fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, %q))\n", h.Key, parentPath)
		}
	}
}

func cleanPagePath(raw string) string {
	raw = strings.TrimSuffix(raw, "/render")

	raw = strings.TrimSuffix(raw, "/json")
	if idx := strings.Index(raw, "?"); idx != -1 {
		raw = raw[:idx]
	}

	return raw
}

func cleanParentPath(raw string) string {
	if idx := strings.LastIndex(raw, "/"); idx != -1 {
		return raw[:idx]
	}

	return raw
}

func (e *Emitter) emitDynamicHeader(buf *bytes.Buffer, svc *ir.ServiceIR, m *ir.MethodIR, h *ir.HeaderIR) {
	buf.WriteString("\tvar refBuf [128]byte\n")
	buf.WriteString("\tref := refBuf[:0]\n")

	baseURL := ""
	if svc != nil {
		baseURL = strings.TrimRight(svc.BaseURL, "/")
	}

	for i, seg := range h.DynamicTemplate.Segments {
		if !seg.IsVariable {
			lit := seg.Literal
			if i == 0 && baseURL != "" && !strings.HasPrefix(lit, "http://") && !strings.HasPrefix(lit, "https://") {
				lit = baseURL + "/" + lit
			}

			fmt.Fprintf(buf, "\tref = append(ref, %q...)\n", lit)

			continue
		}

		// Find matching parameter
		var matchedParam *ir.ParamIR
		for _, p := range m.Params {
			if p.GoName == seg.VarName || strings.EqualFold(p.GoName, seg.VarName) {
				matchedParam = p
				break
			}
		}

		if matchedParam != nil {
			typeName := matchedParam.GoType.Name
			switch typeName {
			case "int", "int8", "int16", "int32", "int64":
				fmt.Fprintf(buf, "\tref = strconv.AppendInt(ref, int64(%s), 10)\n", matchedParam.GoName)
			case "uint", "uint8", "uint16", "uint32", "uint64", "uintptr":
				fmt.Fprintf(buf, "\tref = strconv.AppendUint(ref, uint64(%s), 10)\n", matchedParam.GoName)
			case "bool":
				fmt.Fprintf(buf, "\tref = strconv.AppendBool(ref, %s)\n", matchedParam.GoName)
			case "string":
				switch seg.Transform {
				case ir.TransformQueryEscape:
					fmt.Fprintf(buf, "\tref = append(ref, url.QueryEscape(%s)...)\n", matchedParam.GoName)
				case ir.TransformLower:
					fmt.Fprintf(buf, "\tref = append(ref, strings.ToLower(%s)...)\n", matchedParam.GoName)
				case ir.TransformUpper:
					fmt.Fprintf(buf, "\tref = append(ref, strings.ToUpper(%s)...)\n", matchedParam.GoName)
				default:
					fmt.Fprintf(buf, "\tref = append(ref, url.PathEscape(%s)...)\n", matchedParam.GoName)
				}

			default:
				// Custom type, enum, or id.ID
				switch {
				case strings.HasSuffix(typeName, "ID") || strings.HasSuffix(typeName, "Code") || strings.Contains(typeName, "uint"):
					fmt.Fprintf(buf, "\tref = strconv.AppendUint(ref, uint64(%s), 10)\n", matchedParam.GoName)
				case strings.Contains(typeName, "int"):
					fmt.Fprintf(buf, "\tref = strconv.AppendInt(ref, int64(%s), 10)\n", matchedParam.GoName)
				default:
					fmt.Fprintf(buf, "\tref = append(ref, url.PathEscape(fmt.Sprint(%s))...)\n", matchedParam.GoName)
				}
			}
		} else {
			// Variable is struct field or expression
			switch seg.Transform {
			case ir.TransformQueryEscape:
				fmt.Fprintf(buf, "\tref = append(ref, url.QueryEscape(fmt.Sprint(%s))...)\n", seg.VarName)
			case ir.TransformLower:
				fmt.Fprintf(buf, "\tref = append(ref, strings.ToLower(fmt.Sprint(%s))...)\n", seg.VarName)
			case ir.TransformUpper:
				fmt.Fprintf(buf, "\tref = append(ref, strings.ToUpper(fmt.Sprint(%s))...)\n", seg.VarName)
			default:
				fmt.Fprintf(buf, "\tref = append(ref, url.PathEscape(fmt.Sprint(%s))...)\n", seg.VarName)
			}
		}
	}

	fmt.Fprintf(buf, "\tallMods = append(allMods, mod.WithHeader(%q, string(ref)))\n\n", h.Key)
}

func (e *Emitter) emitQueryBuffer(buf *bytes.Buffer, m *ir.MethodIR, params []*ir.ParamIR, bufSize int) {
	if bufSize <= 0 {
		bufSize = 256
	}

	fmt.Fprintf(buf, "\tvar qBuf [%d]byte\n", bufSize)
	buf.WriteString("\tqBytes := qBuf[:0]\n")

	for i, p := range params {
		if p.Location == ir.LocQueryStruct || p.Formatter == ir.FormatCompiledEncode {
			fmt.Fprintf(buf, "\tqBytes = %s.AppendQuery(qBytes)\n", p.GoName)
			continue
		}

		prefix := p.WireKey + "="
		if i > 0 {
			prefix = fmt.Sprintf("&%s=", p.WireKey)
		}

		fmt.Fprintf(buf, "\tqBytes = append(qBytes, %q...)\n", prefix)

		elemType := p.GoType.ElemType
		if elemType == "" {
			elemType = strings.TrimPrefix(p.GoType.Name, "[]")
		}

		if p.Pipeline != nil {
			fmt.Fprintf(buf, "\t%sBytes, err := json.Marshal(%s)\n", p.GoName, p.GoName)

			errRet := "\tif err != nil {\n\t\treturn err\n\t}\n"
			if m != nil && m.Return != nil && !m.Return.IsVoid {
				errRet = "\tif err != nil {\n\t\treturn nil, err\n\t}\n"
			}

			buf.WriteString(errRet)
			fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(string(%sBytes))...)\n", p.GoName)

			continue
		}

		switch p.Formatter {
		case ir.FormatIntAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, int64(%s), 10)\n", p.GoName)
		case ir.FormatUintAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendUint(qBytes, uint64(%s), 10)\n", p.GoName)
		case ir.FormatBoolAppend:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendBool(qBytes, %s)\n", p.GoName)
		case ir.FormatBoolInt:
			fmt.Fprintf(
				buf,
				"\tif %s {\n\t\tqBytes = append(qBytes, '1')\n\t} else {\n\t\tqBytes = append(qBytes, '0')\n\t}\n",
				p.GoName,
			)

		case ir.FormatTimeRFC3339:
			fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(%s.Format(time.RFC3339))...)\n", p.GoName)
		case ir.FormatTimeUnixS:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, %s.Unix(), 10)\n", p.GoName)
		case ir.FormatTimeUnixMS:
			fmt.Fprintf(buf, "\tqBytes = strconv.AppendInt(qBytes, %s.UnixMilli(), 10)\n", p.GoName)
		case ir.FormatTimeLayout:
			layout := p.TimeLayout
			if layout == "" {
				layout = "2006-01-02"
			}

			fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(%s.Format(%q))...)\n", p.GoName, layout)

		case ir.FormatSliceComma:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, ',')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatSliceSpace:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, '+')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatSlicePipe:
			fmt.Fprintf(buf, "\tfor idx, v := range %s {\n", p.GoName)
			buf.WriteString("\t\tif idx > 0 {\n\t\t\tqBytes = append(qBytes, '|')\n\t\t}\n")
			emitSliceElementFormat(buf, elemType, "qBytes", "v")
			buf.WriteString("\t}\n")

		case ir.FormatBufferAppender:
			fmt.Fprintf(buf, "\tqBytes = %s.AppendBytes(qBytes)\n", p.GoName)
		case ir.FormatCustomStringer:
			fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(%s.String())...)\n", p.GoName)
		case ir.FormatQueryEscaped, ir.FormatDirectString:
			fallthrough
		default:
			if p.GoType.Name == "string" {
				fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(%s)...)\n", p.GoName)
			} else {
				fmt.Fprintf(buf, "\tqBytes = append(qBytes, url.QueryEscape(fmt.Sprint(%s))...)\n", p.GoName)
			}
		}
	}

	buf.WriteString("\tallMods = append(allMods, mod.WithQuery(string(qBytes)))\n\n")
}

func (e *Emitter) emitFormBuffer(buf *bytes.Buffer, m *ir.MethodIR, params []*ir.ParamIR, bufSize int) {
	if bufSize <= 0 {
		bufSize = 256
	}

	buf.WriteString(
		"\tallMods = append(allMods, mod.WithHeader(\"Content-Type\", \"application/x-www-form-urlencoded\"))\n",
	)

	// If single struct argument with compiled encoder without explicit field pipeline
	if len(params) == 1 && params[0].Formatter == ir.FormatCompiledEncode && params[0].Pipeline == nil {
		p := params[0]

		fmt.Fprintf(buf, "\tvar formBuf [%d]byte\n", bufSize)
		fmt.Fprintf(buf, "\tformBytes := %s.AppendFormData(formBuf[:0])\n", p.GoName)

		if m != nil {
			for _, inj := range m.Injects {
				if inj.Target == ir.InjectField {
					fnName := inj.ProviderFn
					if fnName == "" {
						fnName = "SessionID"
					}

					fmt.Fprintf(buf, "\tif getter, ok := any(c.r).(interface{ %s(string) string }); ok {\n", fnName)
					fmt.Fprintf(buf, "\t\tif val := getter.%s(\"\"); val != \"\" {\n", fnName)
					buf.WriteString("\t\t\tif len(formBytes) > 0 {\n")
					fmt.Fprintf(buf, "\t\t\t\tformBytes = append(formBytes, \"&%s=\"...)\n", inj.WireKey)
					buf.WriteString("\t\t\t} else {\n")
					fmt.Fprintf(buf, "\t\t\t\tformBytes = append(formBytes, \"%s=\"...)\n", inj.WireKey)
					buf.WriteString("\t\t\t}\n")
					buf.WriteString("\t\t\tformBytes = append(formBytes, url.QueryEscape(val)...)\n")
					buf.WriteString("\t\t}\n")
					fmt.Fprintf(buf, "\t} else if getter, ok := any(c.r).(interface{ %s() string }); ok {\n", fnName)
					fmt.Fprintf(buf, "\t\tif val := getter.%s(); val != \"\" {\n", fnName)
					buf.WriteString("\t\t\tif len(formBytes) > 0 {\n")
					fmt.Fprintf(buf, "\t\t\t\tformBytes = append(formBytes, \"&%s=\"...)\n", inj.WireKey)
					buf.WriteString("\t\t\t} else {\n")
					fmt.Fprintf(buf, "\t\t\t\tformBytes = append(formBytes, \"%s=\"...)\n", inj.WireKey)
					buf.WriteString("\t\t\t}\n")
					buf.WriteString("\t\t\tformBytes = append(formBytes, url.QueryEscape(val)...)\n")
					buf.WriteString("\t\t}\n")
					buf.WriteString("\t}\n")
				}
			}
		}

		buf.WriteString("\tallMods = append(allMods, mod.WithBodyBytes(formBytes))\n\n")

		return
	}

	fmt.Fprintf(buf, "\tvar formBuf [%d]byte\n", bufSize)
	buf.WriteString("\tformBytes := formBuf[:0]\n")

	for i, p := range params {
		if p.Formatter == ir.FormatCompiledEncode && p.Pipeline == nil {
			fmt.Fprintf(buf, "\tformBytes = %s.AppendFormData(formBytes)\n", p.GoName)
			continue
		}

		prefix := p.WireKey + "="
		if i > 0 {
			prefix = fmt.Sprintf("&%s=", p.WireKey)
		}

		fmt.Fprintf(buf, "\tformBytes = append(formBytes, %q...)\n", prefix)

		if p.Pipeline != nil {
			fmt.Fprintf(buf, "\t%sBytes, err := json.Marshal(%s)\n", p.GoName, p.GoName)

			errRet := "\tif err != nil {\n\t\treturn err\n\t}\n"
			if m != nil && m.Return != nil && !m.Return.IsVoid {
				errRet = "\tif err != nil {\n\t\treturn nil, err\n\t}\n"
			}

			buf.WriteString(errRet)
			fmt.Fprintf(buf, "\tformBytes = append(formBytes, url.QueryEscape(string(%sBytes))...)\n", p.GoName)

			continue
		}

		switch p.Formatter {
		case ir.FormatJSONString:
			fmt.Fprintf(buf, "\t%sJSON, err := json.Marshal(%s)\n", p.GoName, p.GoName)

			errRet := "\tif err != nil {\n\t\treturn err\n\t}\n"
			if m != nil && m.Return != nil && !m.Return.IsVoid {
				errRet = "\tif err != nil {\n\t\treturn nil, err\n\t}\n"
			}

			buf.WriteString(errRet)
			fmt.Fprintf(buf, "\tformBytes = append(formBytes, url.QueryEscape(string(%sJSON))...)\n", p.GoName)

		case ir.FormatIntAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendInt(formBytes, int64(%s), 10)\n", p.GoName)
		case ir.FormatUintAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendUint(formBytes, uint64(%s), 10)\n", p.GoName)
		case ir.FormatBoolAppend:
			fmt.Fprintf(buf, "\tformBytes = strconv.AppendBool(formBytes, %s)\n", p.GoName)
		default:
			if p.GoType.Name == "string" {
				fmt.Fprintf(buf, "\tformBytes = append(formBytes, url.QueryEscape(%s)...)\n", p.GoName)
			} else {
				fmt.Fprintf(buf, "\tformBytes = append(formBytes, url.QueryEscape(fmt.Sprint(%s))...)\n", p.GoName)
			}
		}
	}

	if m != nil {
		for _, inj := range m.Injects {
			if inj.Target == ir.InjectField {
				fnName := inj.ProviderFn
				if fnName == "" {
					fnName = "SessionID"
				}

				fmt.Fprintf(buf, "\tif getter, ok := any(c.r).(interface{ %s(string) string }); ok {\n", fnName)
				fmt.Fprintf(buf, "\t\tif val := getter.%s(\"\"); val != \"\" {\n", fnName)
				buf.WriteString("\t\t\tif len(formBytes) > 0 {\n")
				fmt.Fprintf(buf, "\t\t\t\tformBytes = append(formBytes, \"&%s=\"...)\n", inj.WireKey)
				buf.WriteString("\t\t\t} else {\n")
				fmt.Fprintf(buf, "\t\t\t\tformBytes = append(formBytes, \"%s=\"...)\n", inj.WireKey)
				buf.WriteString("\t\t\t}\n")
				buf.WriteString("\t\t\tformBytes = append(formBytes, url.QueryEscape(val)...)\n")
				buf.WriteString("\t\t}\n")
				fmt.Fprintf(buf, "\t} else if getter, ok := any(c.r).(interface{ %s() string }); ok {\n", fnName)
				fmt.Fprintf(buf, "\t\tif val := getter.%s(); val != \"\" {\n", fnName)
				buf.WriteString("\t\t\tif len(formBytes) > 0 {\n")
				fmt.Fprintf(buf, "\t\t\t\tformBytes = append(formBytes, \"&%s=\"...)\n", inj.WireKey)
				buf.WriteString("\t\t\t} else {\n")
				fmt.Fprintf(buf, "\t\t\t\tformBytes = append(formBytes, \"%s=\"...)\n", inj.WireKey)
				buf.WriteString("\t\t\t}\n")
				buf.WriteString("\t\t\tformBytes = append(formBytes, url.QueryEscape(val)...)\n")
				buf.WriteString("\t\t}\n")
				buf.WriteString("\t}\n")
			}
		}
	}

	buf.WriteString("\tallMods = append(allMods, mod.WithBodyBytes(formBytes))\n\n")
}

func (e *Emitter) emitMultipartBuffer(buf *bytes.Buffer, params []*ir.ParamIR) {
	buf.WriteString("\tvar bodyBuf bytes.Buffer\n")
	buf.WriteString("\tmw := multipart.NewWriter(&bodyBuf)\n")

	for _, p := range params {
		switch p.Location {
		case ir.LocMultipartField:
			fmt.Fprintf(buf, "\t_ = mw.WriteField(%q, fmt.Sprint(%s))\n", p.WireKey, p.GoName)
		case ir.LocMultipartFile:
			fn := p.FileName
			switch {
			case fn == "" || fn == "{filename}":
				fn = "filename"
			case strings.HasPrefix(fn, "{") && strings.HasSuffix(fn, "}"):
				fn = strings.Trim(fn, "{}")
			case !strings.HasPrefix(fn, `"`):
				fn = fmt.Sprintf("%q", fn)
			}

			ct := p.ContentType
			switch {
			case ct == "" || ct == "{content_type}":
				ct = "contentType"
			case strings.HasPrefix(ct, "{") && strings.HasSuffix(ct, "}"):
				ct = strings.Trim(ct, "{}")
			case !strings.HasPrefix(ct, `"`):
				ct = fmt.Sprintf("%q", ct)
			}

			fmt.Fprintf(buf, "\thdr := make(textproto.MIMEHeader)\n")
			fmt.Fprintf(
				buf,
				"\thdr.Set(\"Content-Disposition\", fmt.Sprintf(`form-data; name=%%q; filename=%%q`, %q, %s))\n",
				p.WireKey,
				fn,
			)
			fmt.Fprintf(buf, "\thdr.Set(\"Content-Type\", %s)\n", ct)
			fmt.Fprintf(buf, "\tpw, err := mw.CreatePart(hdr)\n")
			fmt.Fprintf(buf, "\tif err == nil {\n\t\t_, _ = pw.Write(%s)\n\t}\n", p.GoName)
		}
	}

	buf.WriteString("\t_ = mw.Close()\n")
	buf.WriteString(
		"\tallMods = append(allMods, mod.WithHeader(\"Content-Type\", mw.FormDataContentType()), mod.WithBodyBytes(bodyBuf.Bytes()))\n\n",
	)
}

func (e *Emitter) emitExecution(buf *bytes.Buffer, m *ir.MethodIR, targetReq, rawPath string, bodyParam *ir.ParamIR) {
	if m.ReturnPipeline != nil {
		e.emitReturnPipeline(buf, m, targetReq, rawPath)
		return
	}

	methodVerb := m.HTTPMethod
	if methodVerb == "" {
		methodVerb = "GET"
	}

	genericType := "request.NoResponse"
	if m.Return != nil && !m.Return.IsVoid && m.Return.SuccessType.Name != "" {
		genericType = strings.TrimPrefix(m.Return.SuccessType.Name, "*")
	}

	// Handle Envelope unwrapping (@unwrap data)
	if m.UnwrapField != "" {
		e.emitEnvelopeUnwrap(buf, m, targetReq, rawPath, bodyParam)
		return
	}

	bodyArg := "nil"
	if bodyParam != nil {
		bodyArg = bodyParam.GoName
	}

	// Escape hatch for custom package-level helper (@call custom.Func)
	if m.CallFunc != "" {
		callArgs := fmt.Sprintf("ctx, %s, %q", targetReq, rawPath)
		if bodyParam != nil {
			callArgs = fmt.Sprintf("ctx, %s, %q, %s", targetReq, rawPath, bodyArg)
		}

		isPointer := strings.HasPrefix(m.Return.SuccessType.Name, "*")

		switch {
		case m.Return.IsVoid:
			fmt.Fprintf(buf, "\t_, err := %s[%s](%s, allMods...)\n", m.CallFunc, genericType, callArgs)
			buf.WriteString("\treturn err\n")

		case m.Return.SuccessType.Name == "io.ReadCloser" || m.Return.SuccessType.Name == "io.Reader":
			fmt.Fprintf(buf, "\treturn %s(%s, allMods...)\n", m.CallFunc, callArgs)

		default:
			fmt.Fprintf(buf, "\tresp, err := %s[%s](%s, allMods...)\n", m.CallFunc, genericType, callArgs)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			e.emitChecks(buf, m)

			if isPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

		return
	}

	isPointer := strings.HasPrefix(m.Return.SuccessType.Name, "*")
	zeroVal := zeroValueOf(m.Return)

	switch methodVerb {
	case "GET":
		switch {
		case m.Return.IsVoid:
			fmt.Fprintf(
				buf,
				"\t_, err := request.GetTo[%s](ctx, %s, %q, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
			)
			buf.WriteString("\treturn err\n")

		case m.Return.IsDirectBytes:
			fmt.Fprintf(buf, "\tresp, err := %s.Request(ctx, http.MethodGet, %q, allMods...)\n", targetReq, rawPath)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			buf.WriteString("\tdefer aoni.CloseResponse(resp)\n")
			buf.WriteString("\treturn io.ReadAll(resp.Body)\n")

		case m.Return.SuccessType.Name == "io.ReadCloser" || m.Return.SuccessType.Name == "io.Reader":
			fmt.Fprintf(buf, "\tresp, err := %s.Request(ctx, http.MethodGet, %q, allMods...)\n", targetReq, rawPath)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			buf.WriteString("\treturn resp.Body, nil\n")
		default:
			fmt.Fprintf(
				buf,
				"\tresp, err := request.GetTo[%s](ctx, %s, %q, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
			)
			fmt.Fprintf(buf, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", zeroVal)
			e.emitChecks(buf, m)

			if isPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

	case "POST":
		if m.Return.IsVoid {
			fmt.Fprintf(
				buf,
				"\t_, err := request.PostTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			buf.WriteString("\treturn err\n")
		} else {
			fmt.Fprintf(
				buf,
				"\tresp, err := request.PostTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			fmt.Fprintf(buf, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", zeroVal)
			e.emitChecks(buf, m)

			if isPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

	case "PUT":
		if m.Return.IsVoid {
			fmt.Fprintf(
				buf,
				"\t_, err := request.PutTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			buf.WriteString("\treturn err\n")
		} else {
			fmt.Fprintf(
				buf,
				"\tresp, err := request.PutTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			fmt.Fprintf(buf, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", zeroVal)
			e.emitChecks(buf, m)

			if isPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

	case "DELETE":
		if m.Return.IsVoid {
			fmt.Fprintf(
				buf,
				"\t_, err := request.DeleteTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			buf.WriteString("\treturn err\n")
		} else {
			fmt.Fprintf(
				buf,
				"\tresp, err := request.DeleteTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			fmt.Fprintf(buf, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", zeroVal)
			e.emitChecks(buf, m)

			if isPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}

	case "PATCH":
		if m.Return.IsVoid {
			fmt.Fprintf(
				buf,
				"\t_, err := request.PatchTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			buf.WriteString("\treturn err\n")
		} else {
			fmt.Fprintf(
				buf,
				"\tresp, err := request.PatchTo[%s](ctx, %s, %q, %s, allMods...)\n",
				genericType,
				targetReq,
				rawPath,
				bodyArg,
			)
			fmt.Fprintf(buf, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", zeroVal)
			e.emitChecks(buf, m)

			if isPointer {
				buf.WriteString("\treturn resp, nil\n")
			} else {
				buf.WriteString("\treturn *resp, nil\n")
			}
		}
	}
}

func (e *Emitter) emitReturnPipeline(buf *bytes.Buffer, m *ir.MethodIR, targetReq, rawPath string) {
	methodVerb := m.HTTPMethod
	if methodVerb == "" {
		methodVerb = "GET"
	}

	resultType := "any"

	isPointer := true
	if m.Return != nil && !m.Return.IsVoid && m.Return.SuccessType.Name != "" {
		resultType = strings.TrimPrefix(m.Return.SuccessType.Name, "*")
		isPointer = m.Return.SuccessType.IsPointer
	}

	p := m.ReturnPipeline

	httpMethod := "http.MethodGet"
	switch strings.ToUpper(methodVerb) {
	case "POST":
		httpMethod = "http.MethodPost"
	case "PUT":
		httpMethod = "http.MethodPut"
	case "DELETE":
		httpMethod = "http.MethodDelete"
	case "PATCH":
		httpMethod = "http.MethodPatch"
	}

	fmt.Fprintf(buf, "\tresp, err := %s.Request(ctx, %s, %q, allMods...)\n", targetReq, httpMethod, rawPath)
	buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	buf.WriteString("\tdefer resp.Body.Close()\n\n")

	if p.Source == "header" {
		fmt.Fprintf(buf, "\tstageIn := []byte(resp.Header.Get(%q))\n\n", p.SourceArg)
	} else {
		buf.WriteString("\tbodyBytes, err := io.ReadAll(resp.Body)\n")
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")
		buf.WriteString("\tstageIn := bodyBytes\n")
	}

	for i, stage := range p.Stages {
		isLast := (i == len(p.Stages)-1)

		switch stage.Type {
		case ir.StageRegex:
			pattern := ""
			if len(stage.Args) > 0 {
				pattern = stage.Args[0]
			} else if pat, ok := stage.NamedArgs["pattern"]; ok {
				pattern = pat
			}

			fmt.Fprintf(buf, "\tstageOut%d, err := decode.ExtractRegex(stageIn, %q)\n", i, pattern)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			fmt.Fprintf(buf, "\tstageIn = stageOut%d\n\n", i)

		case ir.StageBetween:
			prefix := stage.NamedArgs["prefix"]

			suffix := stage.NamedArgs["suffix"]
			if suffix == "" {
				suffix = stage.NamedArgs["and"]
			}

			if len(stage.Args) >= 1 && prefix == "" {
				prefix = stage.Args[0]
			}

			if len(stage.Args) >= 2 && suffix == "" {
				suffix = stage.Args[1]
			}

			fmt.Fprintf(buf, "\tstageOut%d, err := decode.ExtractBetween(stageIn, %q, %q)\n", i, prefix, suffix)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			fmt.Fprintf(buf, "\tstageIn = stageOut%d\n\n", i)

		case ir.StageAttr:
			css := stage.NamedArgs["css"]

			attr := stage.NamedArgs["name"]
			if attr == "" {
				attr = stage.NamedArgs["attr"]
			}

			if len(stage.Args) >= 1 && css == "" {
				css = stage.Args[0]
			}

			if len(stage.Args) >= 2 && attr == "" {
				attr = stage.Args[1]
			}

			fmt.Fprintf(buf, "\tstageOut%d, err := decode.ExtractAttr(stageIn, %q, %q)\n", i, css, attr)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			fmt.Fprintf(buf, "\tstageIn = stageOut%d\n\n", i)

		case ir.StageHTMLUnescape:
			fmt.Fprintf(buf, "\tstageIn = decode.HTMLUnescape(stageIn)\n\n")

		case ir.StageCustom:
			if isLast {
				fmt.Fprintf(buf, "\treturn %s(stageIn)\n", stage.FuncExpr)
				return
			}

			fmt.Fprintf(buf, "\tstageOut%d, err := %s(stageIn)\n", i, stage.FuncExpr)
			buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			fmt.Fprintf(buf, "\tstageIn = stageOut%d\n\n", i)

		case ir.StageJSON:
			fmt.Fprintf(buf, "\tvar result %s\n", resultType)
			buf.WriteString("\tif err := decode.UnmarshalJSON(stageIn, &result); err != nil {\n")
			buf.WriteString("\t\treturn nil, fmt.Errorf(\"pipeline json unmarshal: %w\", err)\n")
			buf.WriteString("\t}\n")
			e.emitChecks(buf, m)

			if isPointer {
				buf.WriteString("\treturn &result, nil\n")
			} else {
				buf.WriteString("\treturn result, nil\n")
			}

			return
		}
	}

	switch resultType {
	case "[]byte":
		buf.WriteString("\treturn stageIn, nil\n")
	case "string":
		buf.WriteString("\treturn string(stageIn), nil\n")
	default:
		fmt.Fprintf(buf, "\tvar result %s\n", resultType)
		buf.WriteString("\tif err := decode.UnmarshalJSON(stageIn, &result); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")

		if isPointer {
			buf.WriteString("\treturn &result, nil\n")
		} else {
			buf.WriteString("\treturn result, nil\n")
		}
	}
}

func (e *Emitter) emitEnvelopeUnwrap(
	buf *bytes.Buffer,
	m *ir.MethodIR,
	targetReq, rawPath string,
	bodyParam *ir.ParamIR,
) {
	successType := m.Return.SuccessType.Name

	fieldName := strings.ToUpper(m.UnwrapField[:1]) + m.UnwrapField[1:]

	buf.WriteString("\ttype envelope struct {\n")
	buf.WriteString("\t\tSuccess bool `json:\"success\"`\n")
	fmt.Fprintf(buf, "\t\t%s %s `json:\"%s\"`\n", fieldName, successType, m.UnwrapField)
	buf.WriteString("\t\tErrorMsg string `json:\"error,omitempty\"`\n")
	buf.WriteString("\t}\n\n")

	if m.HTTPMethod == "POST" {
		bodyArg := "nil"
		if bodyParam != nil {
			bodyArg = bodyParam.GoName
		}

		fmt.Fprintf(
			buf,
			"\tresp, err := request.PostTo[envelope](ctx, %s, %q, %s, allMods...)\n",
			targetReq,
			rawPath,
			bodyArg,
		)
	} else {
		fmt.Fprintf(buf, "\tresp, err := request.GetTo[envelope](ctx, %s, %q, allMods...)\n", targetReq, rawPath)
	}

	zeroVal := zeroValueOf(m.Return)
	fmt.Fprintf(buf, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", zeroVal)
	fmt.Fprintf(
		buf,
		"\tif !resp.Success && resp.ErrorMsg != \"\" {\n\t\treturn %s, errors.New(resp.ErrorMsg)\n\t}\n",
		zeroVal,
	)
	fmt.Fprintf(buf, "\treturn resp.%s, nil\n", fieldName)
}

func (e *Emitter) emitChecks(buf *bytes.Buffer, m *ir.MethodIR) {
	zeroVal := zeroValueOf(m.Return)

	for _, chk := range m.Checks {
		fieldGoName := toPascalCase(chk.Field)

		cond := "!resp." + fieldGoName
		if chk.ExpectedVal != "true" {
			switch chk.Operator {
			case ir.OpEqual:
				cond = fmt.Sprintf("resp.%s != %s", fieldGoName, chk.ExpectedVal)
			case ir.OpNotEqual:
				cond = fmt.Sprintf("resp.%s == %s", fieldGoName, chk.ExpectedVal)
			default:
				cond = fmt.Sprintf("!(resp.%s %s %s)", fieldGoName, chk.Operator, chk.ExpectedVal)
			}
		}

		fmt.Fprintf(buf, "\tif %s {\n", cond)
		fmt.Fprintf(buf, "\t\treturn %s, errors.New(%q)\n", zeroVal, chk.ErrorMsg)
		buf.WriteString("\t}\n")
	}
}

func (e *Emitter) emitStruct(buf *bytes.Buffer, s *ir.StructIR) {
	// Emit AppendFormData & AppendQuery methods for zero-alloc serialization
	if s.GenValueEncoder {
		fmt.Fprintf(
			buf,
			"// AppendFormData serializes %s into url-encoded form bytes on dst buffer (0 B/op).\n",
			s.Name,
		)
		fmt.Fprintf(buf, "func (r *%s) AppendFormData(dst []byte) []byte {\n", s.Name)
		buf.WriteString("\tif r == nil {\n\t\treturn dst\n\t}\n\n")

		for _, f := range s.Fields {
			switch f.Type.Name {
			case "string":
				fmt.Fprintf(buf, "\tif r.%s != \"\" {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = append(dst, url.QueryEscape(r.%s)...)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "int", "int64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "uint", "uint32", "uint64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendUint(dst, uint64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "time.Time":
				fmt.Fprintf(buf, "\tif !r.%s.IsZero() {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(
					buf,
					"\t\tdst = append(dst, url.QueryEscape(r.%s.Format(time.RFC3339))...)\n",
					f.GoName,
				)
				buf.WriteString("\t}\n")

			case "bool":
				fmt.Fprintf(buf, "\tif r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")

				switch f.Formatter {
				case ir.FormatBoolInt:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=1")
				case ir.FormatBoolFlag:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName)
				default:
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=true")
				}

				buf.WriteString("\t}\n")

			case "[]int", "[]int64":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(v), 10)\n")
				buf.WriteString("\t}\n")

			case "[]string":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = append(dst, url.QueryEscape(v)...)\n")
				buf.WriteString("\t}\n")

			case "any", "interface{}":
				fmt.Fprintf(buf, "\tif r.%s != nil {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = append(dst, fmt.Sprint(r.%s)...)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "float32", "float64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendFloat(dst, float64(r.%s), 'f', -1, 64)\n", f.GoName)
				buf.WriteString("\t}\n")

			case "values.Int64String", "values.Uint64String", "values.Float64String", "values.BoolInt":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
				fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
				fmt.Fprintf(buf, "\t\tdst = strconv.AppendInt(dst, int64(r.%s), 10)\n", f.GoName)
				buf.WriteString("\t}\n")

			default:
				if strings.HasPrefix(f.Type.Name, "[]") || strings.HasPrefix(f.Type.Name, "map[") {
					continue
				}

				if f.Type.IsPointer || strings.HasPrefix(f.Type.Name, "*") {
					fmt.Fprintf(buf, "\tif r.%s != nil {\n", f.GoName)
					buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
					fmt.Fprintf(buf, "\t\tdst = append(dst, fmt.Sprint(r.%s)...)\n", f.GoName)
					buf.WriteString("\t}\n")
				} else {
					fmt.Fprintf(buf, "\tif strVal := fmt.Sprint(r.%s); strVal != \"\" && strVal != \"0\" {\n", f.GoName)
					buf.WriteString("\t\tif len(dst) > 0 { dst = append(dst, '&') }\n")
					fmt.Fprintf(buf, "\t\tdst = append(dst, %q...)\n", f.WireName+"=")
					fmt.Fprintf(buf, "\t\tdst = append(dst, url.QueryEscape(strVal)...)\n")
					buf.WriteString("\t}\n")
				}
			}
		}

		buf.WriteString("\n\treturn dst\n}\n\n")

		fmt.Fprintf(buf, "// AppendQuery serializes %s into query string bytes on dst buffer (0 B/op).\n", s.Name)
		fmt.Fprintf(buf, "func (r *%s) AppendQuery(dst []byte) []byte {\n", s.Name)
		buf.WriteString("\treturn r.AppendFormData(dst)\n}\n\n")

		// Also emit EncodeValues for url.Values interoperability
		fmt.Fprintf(buf, "// EncodeValues serializes %s into url.Values without reflection.\n", s.Name)
		fmt.Fprintf(buf, "func (r *%s) EncodeValues(vals url.Values) {\n", s.Name)
		buf.WriteString("\tif r == nil {\n\t\treturn\n\t}\n")

		for _, f := range s.Fields {
			switch f.Type.Name {
			case "string":
				fmt.Fprintf(buf, "\tif r.%s != \"\" {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, r.%s)\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "int", "int64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatInt(int64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "uint", "uint32", "uint64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatUint(uint64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "float32", "float64":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(
					buf,
					"\t\tvals.Set(%q, strconv.FormatFloat(float64(r.%s), 'f', -1, 64))\n",
					f.WireName,
					f.GoName,
				)
				buf.WriteString("\t}\n")

			case "bool":
				fmt.Fprintf(buf, "\tif r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, \"true\")\n", f.WireName)
				buf.WriteString("\t}\n")
			case "[]int", "[]int64":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Add(%q, strconv.FormatInt(int64(v), 10))\n", f.WireName)
				buf.WriteString("\t}\n")
			case "[]string":
				fmt.Fprintf(buf, "\tfor _, v := range r.%s {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Add(%q, v)\n", f.WireName)
				buf.WriteString("\t}\n")
			case "any", "interface{}":
				fmt.Fprintf(buf, "\tif r.%s != nil {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, fmt.Sprint(r.%s))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			case "values.Int64String", "values.Uint64String", "values.Float64String", "values.BoolInt":
				fmt.Fprintf(buf, "\tif r.%s != 0 {\n", f.GoName)
				fmt.Fprintf(buf, "\t\tvals.Set(%q, strconv.FormatInt(int64(r.%s), 10))\n", f.WireName, f.GoName)
				buf.WriteString("\t}\n")
			default:
				if strings.HasPrefix(f.Type.Name, "[]") || strings.HasPrefix(f.Type.Name, "map[") {
					continue
				}

				if f.Type.IsPointer || strings.HasPrefix(f.Type.Name, "*") {
					fmt.Fprintf(buf, "\tif r.%s != nil {\n", f.GoName)
					fmt.Fprintf(buf, "\t\tvals.Set(%q, fmt.Sprint(r.%s))\n", f.WireName, f.GoName)
					buf.WriteString("\t}\n")
				} else {
					fmt.Fprintf(buf, "\tif strVal := fmt.Sprint(r.%s); strVal != \"\" && strVal != \"0\" {\n", f.GoName)
					fmt.Fprintf(buf, "\t\tvals.Set(%q, strVal)\n", f.WireName)
					buf.WriteString("\t}\n")
				}
			}
		}

		buf.WriteString("}\n\n")
	}
}

func (e *Emitter) emitTuple(buf *bytes.Buffer, t *ir.TupleIR) {
	n := len(t.Fields)
	fmt.Fprintf(buf, "// UnmarshalJSON decodes a heterogeneous JSON array tuple into %s.\n", t.Name)
	fmt.Fprintf(buf, "func (t *%s) UnmarshalJSON(data []byte) error {\n", t.Name)
	fmt.Fprintf(buf, "\tvar raw [%d]json.RawMessage\n", n)
	buf.WriteString("\tif err := json.Unmarshal(data, &raw); err != nil {\n\t\treturn err\n\t}\n")

	for i, f := range t.Fields {
		fmt.Fprintf(buf, "\t_ = json.Unmarshal(raw[%d], &t.%s)\n", i, f.GoName)
	}

	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")
}

func emitSliceElementFormat(buf *bytes.Buffer, elemType, targetBuf, valVar string) {
	elemType = strings.TrimPrefix(elemType, "*")
	switch elemType {
	case "string":
		fmt.Fprintf(buf, "\t\t%s = append(%s, url.QueryEscape(%s)...)\n", targetBuf, targetBuf, valVar)
	case "int", "int8", "int16", "int32", "int64":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendInt(%s, int64(%s), 10)\n", targetBuf, targetBuf, valVar)
	case "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendUint(%s, uint64(%s), 10)\n", targetBuf, targetBuf, valVar)
	case "bool":
		fmt.Fprintf(buf, "\t\t%s = strconv.AppendBool(%s, %s)\n", targetBuf, targetBuf, valVar)
	default:
		fmt.Fprintf(buf, "\t\t%s = append(%s, url.QueryEscape(fmt.Sprint(%s))...)\n", targetBuf, targetBuf, valVar)
	}
}

func (e *Emitter) emitEventMethod(
	buf *bytes.Buffer,
	root *ir.RootIR,
	svc *ir.ServiceIR,
	clientStructName string,
	m *ir.MethodIR,
) {
	paramsStr := formatMethodParams(m.Params)
	returnsStr := formatMethodReturns(m.Return)

	fmt.Fprintf(buf, "func (c *%s) %s(%s) %s {\n", clientStructName, m.Name, paramsStr, returnsStr)

	handlerParamName := "handler"

	handlerElemType := ""
	for _, p := range m.Params {
		if strings.HasPrefix(p.GoType.Name, "func(") {
			handlerParamName = p.GoName
			handlerElemType = p.GoType.ElemType
			break
		}
	}

	opIDExpr := formatOpID(m.OpID, m.OpIDIsQuoted)

	fmt.Fprintf(buf, "\tunsub := c.transport.Subscribe(%s, func(raw []byte) {\n", opIDExpr)

	switch {
	case m.ReturnPipeline != nil && len(m.ReturnPipeline.Stages) > 0:
		buf.WriteString("\t\tstageIn := raw\n")

		for i, stage := range m.ReturnPipeline.Stages {
			switch stage.Type {
			case ir.StageProto:
				isPtr := strings.HasPrefix(handlerElemType, "*")
				baseType := strings.TrimPrefix(handlerElemType, "*")
				fmt.Fprintf(buf, "\t\tvar msg %s\n", baseType)
				buf.WriteString("\t\tif err := proto.Unmarshal(stageIn, &msg); err != nil {\n\t\t\treturn\n\t\t}\n")

				if isPtr {
					fmt.Fprintf(buf, "\t\t%s(&msg)\n", handlerParamName)
				} else {
					fmt.Fprintf(buf, "\t\t%s(msg)\n", handlerParamName)
				}

				buf.WriteString("\t})\n\n")
				buf.WriteString("\tc.mu.Lock()\n\tc.unregs = append(c.unregs, unsub)\n\tc.mu.Unlock()\n\n")
				buf.WriteString("\treturn unsub\n}\n\n")

				return

			case ir.StageJSON:
				isPtr := strings.HasPrefix(handlerElemType, "*")
				baseType := strings.TrimPrefix(handlerElemType, "*")
				fmt.Fprintf(buf, "\t\tvar msg %s\n", baseType)
				buf.WriteString(
					"\t\tif err := decode.UnmarshalJSON(stageIn, &msg); err != nil {\n\t\t\treturn\n\t\t}\n",
				)

				if isPtr {
					fmt.Fprintf(buf, "\t\t%s(&msg)\n", handlerParamName)
				} else {
					fmt.Fprintf(buf, "\t\t%s(msg)\n", handlerParamName)
				}

				buf.WriteString("\t})\n\n")
				buf.WriteString("\tc.mu.Lock()\n\tc.unregs = append(c.unregs, unsub)\n\tc.mu.Unlock()\n\n")
				buf.WriteString("\treturn unsub\n}\n\n")

				return

			case ir.StageCustom:
				fmt.Fprintf(buf, "\t\tres, err := %s(stageIn)\n", stage.FuncExpr)
				buf.WriteString("\t\tif err != nil {\n\t\t\treturn\n\t\t}\n")
				fmt.Fprintf(buf, "\t\t%s(res)\n", handlerParamName)
				buf.WriteString("\t})\n\n")
				buf.WriteString("\tc.mu.Lock()\n\tc.unregs = append(c.unregs, unsub)\n\tc.mu.Unlock()\n\n")
				buf.WriteString("\treturn unsub\n}\n\n")

				return

			default:
				fmt.Fprintf(
					buf,
					"\t\tstageOut%d, err := decode.ExtractAttr(stageIn, %q, %q)\n",
					i,
					stage.NamedArgs["css"],
					stage.NamedArgs["name"],
				)
				buf.WriteString("\t\tif err != nil {\n\t\t\treturn\n\t\t}\n")
				fmt.Fprintf(buf, "\t\tstageIn = stageOut%d\n", i)
			}
		}

	case strings.Contains(handlerElemType, "pb.") || strings.Contains(handlerElemType, "CMsg") || strings.Contains(handlerElemType, "proto."):
		isPtr := strings.HasPrefix(handlerElemType, "*")
		baseType := strings.TrimPrefix(handlerElemType, "*")
		fmt.Fprintf(buf, "\t\tvar msg %s\n", baseType)
		buf.WriteString("\t\tif err := proto.Unmarshal(raw, &msg); err != nil {\n\t\t\treturn\n\t\t}\n")

		if isPtr {
			fmt.Fprintf(buf, "\t\t%s(&msg)\n", handlerParamName)
		} else {
			fmt.Fprintf(buf, "\t\t%s(msg)\n", handlerParamName)
		}

	default:
		fmt.Fprintf(buf, "\t\t%s(raw)\n", handlerParamName)
	}

	buf.WriteString("\t})\n\n")
	buf.WriteString("\tc.mu.Lock()\n\tc.unregs = append(c.unregs, unsub)\n\tc.mu.Unlock()\n\n")
	buf.WriteString("\treturn unsub\n}\n\n")
}

func (e *Emitter) emitRPCMethod(
	buf *bytes.Buffer,
	root *ir.RootIR,
	svc *ir.ServiceIR,
	clientStructName string,
	m *ir.MethodIR,
) {
	paramsStr := formatMethodParams(m.Params)
	returnsStr := formatMethodReturns(m.Return)

	fmt.Fprintf(buf, "func (c *%s) %s(%s) %s {\n", clientStructName, m.Name, paramsStr, returnsStr)

	reqParamName := ""

	reqParamType := ""
	for _, p := range m.Params {
		if p.GoType.Name != "context.Context" && !p.GoType.IsVariadic {
			reqParamName = p.GoName
			reqParamType = p.GoType.Name
			break
		}
	}

	opIDExpr := formatOpID(m.OpID, m.OpIDIsQuoted)

	if reqParamName != "" {
		switch {
		case m.BodyPipeline != nil && len(m.BodyPipeline.Stages) > 0:
			switch m.BodyPipeline.Stages[0].Type {
			case ir.StageProto:
				fmt.Fprintf(buf, "\tpayloadBytes, err := proto.Marshal(%s)\n", reqParamName)
			case ir.StageJSON:
				fmt.Fprintf(buf, "\tpayloadBytes, err := json.Marshal(%s)\n", reqParamName)
			case ir.StageCustom:
				fmt.Fprintf(buf, "\tpayloadBytes, err := %s(%s)\n", m.BodyPipeline.Stages[0].FuncExpr, reqParamName)
			default:
				fmt.Fprintf(buf, "\tpayloadBytes, err := json.Marshal(%s)\n", reqParamName)
			}

		case strings.Contains(reqParamType, "pb.") || strings.Contains(reqParamType, "proto.") || strings.Contains(reqParamType, "CMsg"):
			fmt.Fprintf(buf, "\tpayloadBytes, err := proto.Marshal(%s)\n", reqParamName)
		case reqParamType == "[]byte":
			fmt.Fprintf(buf, "\tpayloadBytes := %s\n", reqParamName)
		default:
			fmt.Fprintf(buf, "\tpayloadBytes, err := json.Marshal(%s)\n", reqParamName)
		}

		if reqParamType != "[]byte" {
			if m.IsNotify || m.Operation == ir.OpNotify {
				buf.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n\n")
			} else {
				buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")
			}
		}
	} else {
		buf.WriteString("\tvar payloadBytes []byte\n\n")
	}

	if m.IsNotify || m.Operation == ir.OpNotify {
		fmt.Fprintf(buf, "\treturn c.transport.Notify(ctx, %s, payloadBytes)\n}\n\n", opIDExpr)
		return
	}

	fmt.Fprintf(buf, "\trawResp, err := c.transport.Invoke(ctx, %s, payloadBytes)\n", opIDExpr)
	buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")

	// Decode response
	resultType := ""
	if m.Return != nil && m.Return.SuccessType.Name != "" {
		resultType = m.Return.SuccessType.Name
	}

	if resultType == "" || resultType == "error" || m.Return.IsVoid {
		buf.WriteString("\treturn nil\n}\n\n")
		return
	}

	switch {
	case m.ReturnPipeline != nil && len(m.ReturnPipeline.Stages) > 0:
		stage := m.ReturnPipeline.Stages[len(m.ReturnPipeline.Stages)-1]
		switch stage.Type {
		case ir.StageProto:
			isPtr := strings.HasPrefix(resultType, "*")
			baseType := strings.TrimPrefix(resultType, "*")
			fmt.Fprintf(buf, "\tvar result %s\n", baseType)
			buf.WriteString("\tif err := proto.Unmarshal(rawResp, &result); err != nil {\n\t\treturn nil, err\n\t}\n")

			if isPtr {
				buf.WriteString("\treturn &result, nil\n")
			} else {
				buf.WriteString("\treturn result, nil\n")
			}

		case ir.StageJSON:
			isPtr := strings.HasPrefix(resultType, "*")
			baseType := strings.TrimPrefix(resultType, "*")
			fmt.Fprintf(buf, "\tvar result %s\n", baseType)
			buf.WriteString(
				"\tif err := decode.UnmarshalJSON(rawResp, &result); err != nil {\n\t\treturn nil, err\n\t}\n",
			)

			if isPtr {
				buf.WriteString("\treturn &result, nil\n")
			} else {
				buf.WriteString("\treturn result, nil\n")
			}

		case ir.StageCustom:
			fmt.Fprintf(buf, "\treturn %s(rawResp)\n", stage.FuncExpr)
		default:
			buf.WriteString("\treturn rawResp, nil\n")
		}

	case strings.Contains(resultType, "pb.") || strings.Contains(resultType, "CMsg"):
		isPtr := strings.HasPrefix(resultType, "*")
		baseType := strings.TrimPrefix(resultType, "*")
		fmt.Fprintf(buf, "\tvar result %s\n", baseType)
		buf.WriteString("\tif err := proto.Unmarshal(rawResp, &result); err != nil {\n\t\treturn nil, err\n\t}\n")

		if isPtr {
			buf.WriteString("\treturn &result, nil\n")
		} else {
			buf.WriteString("\treturn result, nil\n")
		}

	case resultType == "[]byte":
		buf.WriteString("\treturn rawResp, nil\n")
	default:
		isPtr := strings.HasPrefix(resultType, "*")
		baseType := strings.TrimPrefix(resultType, "*")
		fmt.Fprintf(buf, "\tvar result %s\n", baseType)
		buf.WriteString("\tif err := decode.UnmarshalJSON(rawResp, &result); err != nil {\n\t\treturn nil, err\n\t}\n")

		if isPtr {
			buf.WriteString("\treturn &result, nil\n")
		} else {
			buf.WriteString("\treturn result, nil\n")
		}
	}

	buf.WriteString("}\n\n")
}

func isNumeric(s string) bool {
	if s == "" {
		return false
	}

	for _, r := range s {
		if !unicode.IsDigit(r) && r != '-' && r != '+' {
			return false
		}
	}

	return true
}

func formatOpID(opID string, isQuoted bool) string {
	if isQuoted {
		return strconv.Quote(opID)
	}

	if isNumeric(opID) {
		return opID
	}

	return opID
}

func (e *Emitter) emitSocketService(buf *bytes.Buffer, root *ir.RootIR, svc *ir.ServiceIR) {
	clientStructName := lowerFirst(svc.Name) + "Impl"

	endpointType := "string"
	packetType := "any"
	opCodeType := "int"
	jobIDType := "uint64"

	if svc.SocketConfig != nil {
		if svc.SocketConfig.EndpointType != "" {
			endpointType = svc.SocketConfig.EndpointType
		}

		if svc.SocketConfig.PacketType != "" {
			packetType = svc.SocketConfig.PacketType
		}

		if svc.SocketConfig.OpCodeType != "" {
			opCodeType = svc.SocketConfig.OpCodeType
		}

		if svc.SocketConfig.JobIDType != "" {
			jobIDType = svc.SocketConfig.JobIDType
		}
	}

	configTypeName := svc.Name + "Config"
	if svc.Name == "Socket" || svc.Name == "Client" {
		configTypeName = "Config"
	}

	fmt.Fprintf(buf, "// %s configures the %s socket subsystem.\n", configTypeName, svc.Name)
	fmt.Fprintf(buf, "type %s struct {\n", configTypeName)
	fmt.Fprintf(buf, "\tConnector connector.Config[%s]\n", endpointType)
	fmt.Fprintf(buf, "\tProcessor processor.Config\n")
	fmt.Fprintf(buf, "\tDispatcher dispatcher.Config\n")
	fmt.Fprintf(buf, "\tFramer socket.Framer\n")
	fmt.Fprintf(buf, "\tCipher socket.Cipher\n")
	fmt.Fprintf(buf, "\tDecode processor.DecodeFunc[%s]\n", packetType)
	fmt.Fprintf(buf, "\tExtractor dispatcher.Extractor[%s, %s, %s]\n", opCodeType, jobIDType, packetType)
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "type %s struct {\n", clientStructName)
	fmt.Fprintf(buf, "\tcfg %s\n", configTypeName)
	fmt.Fprintf(buf, "\tconn *connector.Connector[%s]\n", endpointType)
	fmt.Fprintf(buf, "\tproc *processor.Processor[%s]\n", packetType)
	fmt.Fprintf(buf, "\tdispatch *dispatcher.Dispatcher[%s, %s, %s]\n", opCodeType, jobIDType, packetType)
	fmt.Fprintf(buf, "\tclosed atomic.Bool\n")
	fmt.Fprintf(buf, "\tmu sync.RWMutex\n")
	fmt.Fprintf(buf, "\theartbeatCancel context.CancelFunc\n")
	fmt.Fprintf(buf, "}\n\n")

	constructorName := "New" + svc.Name
	if svc.Name == "Socket" || svc.Name == "Client" {
		constructorName = "New"
	}

	fmt.Fprintf(buf, "// %s initializes a new %s socket instance.\n", constructorName, svc.Name)
	fmt.Fprintf(buf, "func %s(cfg %s) %s {\n", constructorName, configTypeName, svc.Name)
	fmt.Fprintf(buf, "\ts := &%s{cfg: cfg}\n", clientStructName)
	fmt.Fprintf(buf, "\tif cfg.Framer != nil {\n\t\ts.cfg.Connector.Framer = cfg.Framer\n\t}\n")
	fmt.Fprintf(buf, "\tif cfg.Cipher != nil {\n\t\ts.cfg.Connector.Cipher = cfg.Cipher\n\t}\n")
	fmt.Fprintf(buf, "\ts.conn = connector.New[%s](s.cfg.Connector)\n", endpointType)
	fmt.Fprintf(
		buf,
		"\ts.dispatch = dispatcher.New[%s, %s, %s](s.cfg.Dispatcher, s.conn, s.cfg.Extractor)\n",
		opCodeType,
		jobIDType,
		packetType,
	)
	fmt.Fprintf(
		buf,
		"\ts.proc = processor.New[%s](s.cfg.Processor, s.conn.C(), s.dispatch, s.cfg.Decode)\n",
		packetType,
	)
	fmt.Fprintf(buf, "\treturn s\n}\n\n")

	for _, m := range svc.Methods {
		switch m.Name {
		case "Connect":
			fmt.Fprintf(
				buf,
				"func (s *%s) Connect(ctx context.Context, endpoint %s) error {\n",
				clientStructName,
				endpointType,
			)
			buf.WriteString("\tif s.closed.Load() {\n\t\treturn errors.New(\"socket: closed\")\n\t}\n")
			buf.WriteString("\ts.proc.Start()\n")
			buf.WriteString("\treturn s.conn.Connect(ctx, endpoint)\n}\n\n")

		case "Disconnect":
			fmt.Fprintf(buf, "func (s *%s) Disconnect() error {\n", clientStructName)
			buf.WriteString("\treturn s.conn.Disconnect()\n}\n\n")

		case "Close":
			fmt.Fprintf(buf, "func (s *%s) Close() error {\n", clientStructName)
			buf.WriteString("\tif s.closed.Swap(true) {\n\t\treturn nil\n\t}\n")
			buf.WriteString("\ts.mu.Lock()\n")
			buf.WriteString(
				"\tif s.heartbeatCancel != nil {\n\t\ts.heartbeatCancel()\n\t\ts.heartbeatCancel = nil\n\t}\n",
			)
			buf.WriteString("\ts.mu.Unlock()\n")
			buf.WriteString("\tvar errs []error\n")
			buf.WriteString("\terrs = append(errs, s.conn.Close())\n")
			buf.WriteString("\ts.proc.Stop()\n")
			buf.WriteString("\terrs = append(errs, s.dispatch.Close())\n")
			buf.WriteString("\treturn errors.Join(errs...)\n}\n\n")

		case "IsConnected":
			fmt.Fprintf(buf, "func (s *%s) IsConnected() bool {\n", clientStructName)
			buf.WriteString("\treturn s.conn.IsConnected() && !s.closed.Load()\n}\n\n")

		case "Connector":
			fmt.Fprintf(
				buf,
				"func (s *%s) Connector() *connector.Connector[%s] {\n\treturn s.conn\n}\n\n",
				clientStructName,
				endpointType,
			)

		case "Dispatcher":
			fmt.Fprintf(
				buf,
				"func (s *%s) Dispatcher() *dispatcher.Dispatcher[%s, %s, %s] {\n\treturn s.dispatch\n}\n\n",
				clientStructName,
				opCodeType,
				jobIDType,
				packetType,
			)

		default:
			switch {
			case m.IsEvent || m.Operation == ir.OpEvent || strings.HasPrefix(m.Name, "Register"):
				if len(m.Params) >= 2 {
					p0Type := formatType(m.Params[0].GoType)

					p1Type := formatType(m.Params[1].GoType)
					if strings.Contains(strings.ToLower(m.Name), "service") || p0Type == "string" {
						fmt.Fprintf(
							buf,
							"func (s *%s) %s(%s string, %s %s) {\n",
							clientStructName,
							m.Name,
							m.Params[0].GoName,
							m.Params[1].GoName,
							p1Type,
						)
						fmt.Fprintf(
							buf,
							"\ts.dispatch.RegisterMethodHandler(%s, %s)\n}\n\n",
							m.Params[0].GoName,
							m.Params[1].GoName,
						)
					} else {
						fmt.Fprintf(
							buf,
							"func (s *%s) %s(%s %s, %s %s) {\n",
							clientStructName,
							m.Name,
							m.Params[0].GoName,
							p0Type,
							m.Params[1].GoName,
							p1Type,
						)
						fmt.Fprintf(
							buf,
							"\ts.dispatch.RegisterHandler(%s, %s)\n}\n\n",
							m.Params[0].GoName,
							m.Params[1].GoName,
						)
					}
				}

			case m.Operation == ir.OpRPC || strings.HasSuffix(m.Name, "Sync"):
				retType := formatMethodReturns(m.Return)
				paramsStr := formatMethodParams(m.Params)
				fmt.Fprintf(buf, "func (s *%s) %s(%s) %s {\n", clientStructName, m.Name, paramsStr, retType)
				buf.WriteString("\tif s.closed.Load() {\n")

				if m.Return != nil && !m.Return.IsVoid {
					tName := formatType(m.Return.SuccessType)
					fmt.Fprintf(buf, "\t\tvar zero %s\n\t\treturn zero, errors.New(\"socket: closed\")\n", tName)
				} else {
					buf.WriteString("\t\treturn errors.New(\"socket: closed\")\n")
				}

				buf.WriteString("\t}\n")
				buf.WriteString("\tjobID := s.dispatch.NextJobID()\n")
				buf.WriteString("\treturn s.dispatch.SendSync(ctx, jobID, req)\n}\n\n")

			default:
				paramsStr := formatMethodParams(m.Params)
				retType := formatMethodReturns(m.Return)
				fmt.Fprintf(buf, "func (s *%s) %s(%s) %s {\n", clientStructName, m.Name, paramsStr, retType)
				buf.WriteString("\tif s.closed.Load() {\n\t\treturn errors.New(\"socket: closed\")\n\t}\n")
				buf.WriteString("\treturn s.conn.Send(ctx, req)\n}\n\n")
			}
		}
	}

	if svc.SocketConfig != nil && svc.SocketConfig.Heartbeat != nil {
		fmt.Fprintf(buf, "// StartHeartbeat initiates a background heartbeat loop.\n")
		fmt.Fprintf(buf, "func (s *%s) StartHeartbeat(interval time.Duration) error {\n", clientStructName)
		buf.WriteString("\tif s.closed.Load() {\n\t\treturn errors.New(\"socket: closed\")\n\t}\n")
		buf.WriteString("\ts.mu.Lock()\n")
		buf.WriteString("\tif s.heartbeatCancel != nil {\n\t\ts.heartbeatCancel()\n\t}\n")
		buf.WriteString("\tctx, cancel := context.WithCancel(context.Background())\n")
		buf.WriteString("\ts.heartbeatCancel = cancel\n")
		buf.WriteString("\ts.mu.Unlock()\n\n")
		buf.WriteString("\tgo func() {\n")
		buf.WriteString("\t\tticker := time.NewTicker(interval)\n")
		buf.WriteString("\t\tdefer ticker.Stop()\n")
		buf.WriteString("\t\tfor {\n")
		buf.WriteString("\t\t\tselect {\n")
		buf.WriteString("\t\t\tcase <-ticker.C:\n")
		buf.WriteString("\t\t\t\tif !s.IsConnected() {\n\t\t\t\t\tcontinue\n\t\t\t\t}\n")
		buf.WriteString("\t\t\tcase <-ctx.Done():\n\t\t\t\treturn\n")
		buf.WriteString("\t\t\t}\n\t\t}\n\t}()\n")
		buf.WriteString("\treturn nil\n}\n\n")
	}
}
