// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package codegen_test

import (
	"strings"
	"testing"

	"github.com/lemon4ksan/aoni/internal/codegen/emitter"
	"github.com/lemon4ksan/aoni/internal/codegen/parser"
	"github.com/stretchr/testify/require"
)

func TestSmartDirectives_RefererAndPresets(t *testing.T) {
	src := `
package testapi

type OrderResponse struct {
	Success bool ` + "`" + `json:"success"` + "`" + `
}

// @aoni:service
// @engine custom type="mockRequester" required
// @base_url "https://steamcommunity.com/"
type SteamShopAPI interface {
	// @post "market/createbuyorder"
	// @form
	// @preset :xhr
	// @inject field="sessionid" from="SessionID"
	// @referer "market/listings/{appID}/{marketHashName:escape}"
	CreateBuyOrder(
		ctx context.Context,
		// @field "appid"
		appID uint32,
		// @field "market_hash_name"
		marketHashName string,
	) (*OrderResponse, error)

	// @get "market/search/render"
	// @preset :cors
	// @referer :page
	Search(ctx context.Context) (*OrderResponse, error)

	// @get "market/listings/730/ak47"
	// @referer :parent
	GetListingParent(ctx context.Context) (*OrderResponse, error)

	// @get "market/home"
	// @referer :origin
	GetHome(ctx context.Context) (*OrderResponse, error)
}
`

	p := parser.NewParser()
	root, err := p.ParseSource("testapi.go", []byte(src))
	require.NoError(t, err)
	require.NotNil(t, root)

	em := emitter.NewEmitter()
	codeBytes, err := em.Emit(root)
	require.NoError(t, err)

	code := string(codeBytes)

	// Verify CreateBuyOrder has XHR preset, referer template, and auto sessionid
	require.Contains(t, code, `mod.WithHeader("X-Requested-With", "XMLHttpRequest")`)
	require.Contains(t, code, `mod.WithHeader("Accept", "application/json, text/javascript, */*; q=0.01")`)
	require.Contains(t, code, `ref = append(ref, "https://steamcommunity.com/market/listings/"...)`)
	require.Contains(t, code, `ref = strconv.AppendUint(ref, uint64(appID), 10)`)
	require.Contains(t, code, `ref = append(ref, url.PathEscape(marketHashName)...)`)
	require.Contains(t, code, `mod.WithHeader("Referer", string(ref))`)
	require.Contains(t, code, `getter, ok := any(c.r).(interface{ SessionID(string) string })`)
	require.Contains(t, code, `formBytes = append(formBytes, "&sessionid="...)`)

	// Verify Search has :page referer ("https://steamcommunity.com/market/search") and :cors headers
	require.Contains(t, code, `mod.WithHeader("Sec-Fetch-Dest", "empty")`)
	require.Contains(t, code, `mod.WithHeader("Sec-Fetch-Mode", "cors")`)
	require.Contains(t, code, `mod.WithHeader("Referer", "https://steamcommunity.com/market/search")`)

	// Verify GetListingParent has :parent referer ("https://steamcommunity.com/market/listings/730")
	require.Contains(t, code, `mod.WithHeader("Referer", "https://steamcommunity.com/market/listings/730")`)

	// Verify GetHome has :origin referer ("https://steamcommunity.com/")
	require.Contains(t, code, `mod.WithHeader("Referer", "https://steamcommunity.com/")`)

	// Ensure no compilation syntax issues
	require.True(t, strings.HasPrefix(code, "// Code generated by vortex. DO NOT EDIT."))
}
