// Code generated by c2plan9. DO NOT EDIT.

//go:build arm64 && !purego

#include "textflag.h"

// func crc32_ieee_update
TEXT ·crc32_ieee_update(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	CBZ R2, L_0028
	MVNW R0, R8
L_0008:
	MOVBU.P 1(R1), R9
	SUBS $1, R2, R2
	EORW R8, R9, R9
	AND $255, R9, R9
	MOVWU (R3)(R9<<2), R9
	EORW R8>>8, R9, R8
	BNE L_0008
	MVNW R8, R0
L_0028:
	MOVD R0, ret+64(FP)
	RET

