// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package project_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/lemon4ksan/aoni/internal/codegen/project"
)

func TestProject_FindRootAndAutoDiscover(t *testing.T) {
	tempDir := t.TempDir()

	// 1. Create a dummy go.mod
	goModPath := filepath.Join(tempDir, "go.mod")
	err := os.WriteFile(goModPath, []byte("module testmod\n\ngo 1.25.4\n"), 0o600)
	require.NoError(t, err)

	// 2. Create nested service folder
	serviceDir := filepath.Join(tempDir, "pkg", "services", "user")
	err = os.MkdirAll(serviceDir, 0o750)
	require.NoError(t, err)

	apiFile := filepath.Join(serviceDir, "api.go")
	apiSrc := `package user

import (
	"context"
	"github.com/lemon4ksan/aoni"
)

// @aoni:service
// @version "v1.0.0"
type UserAPI interface {
	// @get "users/{id}"
	GetUser(ctx context.Context, id string, mods ...aoni.RequestModifier) (*UserDTO, error)
}

// @aoni:dto
type UserDTO struct {
	ID string
}
`
	err = os.WriteFile(apiFile, []byte(apiSrc), 0o600)
	require.NoError(t, err)

	// 3. Test FindRoot from nested subfolder
	subDir := filepath.Join(serviceDir, "nested", "deeper")
	err = os.MkdirAll(subDir, 0o750)
	require.NoError(t, err)

	discoveredRoot, cfgPath, err := project.FindRoot(subDir)
	require.NoError(t, err)
	require.Equal(t, tempDir, discoveredRoot)
	require.Empty(t, cfgPath) // No .vortex.yml yet

	// 4. Test AutoDiscover
	cfg, err := project.AutoDiscover(tempDir)
	require.NoError(t, err)
	require.Equal(t, tempDir, cfg.RootDir)
	require.Len(t, cfg.Contracts, 1)
	require.Equal(t, "UserAPI", cfg.Contracts[0].Name)
	require.Equal(t, "user", cfg.Contracts[0].Package)

	// 5. Test Init creates .vortex.yml
	createdCfg, err := project.Init(tempDir, false)
	require.NoError(t, err)
	require.FileExists(t, filepath.Join(tempDir, ".vortex.yml"))
	require.Len(t, createdCfg.Contracts, 1)

	// 6. Test FindRoot now finds explicit .vortex.yml
	discoveredRoot2, cfgPath2, err := project.FindRoot(subDir)
	require.NoError(t, err)
	require.Equal(t, tempDir, discoveredRoot2)
	require.Equal(t, filepath.Join(tempDir, ".vortex.yml"), cfgPath2)

	// 7. Test Load parses .vortex.yml
	loadedCfg, err := project.Load(subDir)
	require.NoError(t, err)
	require.Equal(t, tempDir, loadedCfg.RootDir)
	require.Len(t, loadedCfg.Contracts, 1)
	require.Equal(t, "UserAPI", loadedCfg.Contracts[0].Name)
}

func TestProject_StatusEngine(t *testing.T) {
	tempDir := t.TempDir()

	serviceDir := filepath.Join(tempDir, "pkg", "user")
	err := os.MkdirAll(serviceDir, 0o750)
	require.NoError(t, err)

	apiFile := filepath.Join(serviceDir, "api.go")
	apiSrc := `package user

import (
	"context"
	"github.com/lemon4ksan/aoni"
)

// @aoni:service
type API interface {
	// @get "me"
	GetMe(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error)
}
`
	err = os.WriteFile(apiFile, []byte(apiSrc), 0o600)
	require.NoError(t, err)

	cfg := &project.Config{
		RootDir: tempDir,
		Contracts: []project.ContractConfig{
			{
				Name:    "API",
				Package: "user",
				File:    "pkg/user/api.go",
				Gen:     "pkg/user/api.gen.go",
			},
		},
	}

	engine := project.NewStatusEngine()

	// 1. First inspection: api.gen.go is missing -> Stale
	report := engine.Inspect(cfg, cfg.Contracts)
	require.Len(t, report.Contracts, 1)
	require.True(t, report.Contracts[0].IsGenStale)
	require.Equal(t, 1, report.StaleCount())
	require.True(t, report.HasIssues())
	require.Len(t, report.NextActions, 1)

	// 2. Create api.gen.go
	genFile := filepath.Join(serviceDir, "api.gen.go")
	err = os.WriteFile(genFile, []byte("// Code generated by vortex. DO NOT EDIT.\npackage user\n"), 0o600)
	require.NoError(t, err)

	// 3. Second inspection: up-to-date!
	report2 := engine.Inspect(cfg, cfg.Contracts)
	require.False(t, report2.Contracts[0].IsGenStale)
	require.Equal(t, 0, report2.StaleCount())
	require.False(t, report2.HasIssues())

	// 4. Test Render output
	rendered := report2.Render(false)
	require.Contains(t, rendered, "API")
	require.Contains(t, rendered, "100% in sync")
	require.Contains(t, rendered, "All systems nominal")

	// 5. Test JSON rendering
	jsonData, err := report2.RenderJSON()
	require.NoError(t, err)
	require.Contains(t, string(jsonData), "\"total_methods\": 1")
}
