// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func brotli_fill_bit_window
TEXT ·brotli_fill_bit_window(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	CMPQ 0(SI), $0x20
	JB L_0020
	MOVL 0x4(DI), AX
	MOVQ AX, 0(DI)
	XORB $0x20, 0(SI)
	MOVQ 0(CX), AX
	MOVL 0(DX)(AX*1), AX
	SHLQ $0x20, AX
	ORQ AX, 0(DI)
	ADDQ $0x4, 0(CX)
L_0020:
	MOVQ AX, ret+48(FP)
	RET

// func brotli_read_bits
TEXT ·brotli_read_bits(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	MOVQ 0(SI), R9
	CMPQ R9, $0x20
	JB L_0026
	MOVL 0x4(DI), AX
	MOVQ AX, 0(DI)
	XORB $0x20, 0(SI)
	MOVQ 0(CX), AX
	MOVL 0(DX)(AX*1), AX
	SHLQ $0x20, AX
	ORQ AX, 0(DI)
	ADDQ $0x4, 0(CX)
	MOVQ 0(SI), R9
L_0026:
	MOVQ $-0x1, DX
	MOVL R8, CX
	SHLQ CL, DX
	NOTQ DX
	MOVQ 0(DI), AX
	MOVL R9, CX
	SHRQ CL, AX
	ANDQ DX, AX
	ADDQ R8, R9
	MOVQ R9, 0(SI)
	MOVQ AX, ret+48(FP)
	RET

