// Code generated by c2plan9. DO NOT EDIT.

//go:build arm64 && !purego

#include "textflag.h"

// func brotli_fill_bit_window
TEXT ·brotli_fill_bit_window(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	MOVD (R1), R8
	CMP $32, R8
	BCC L_0040
	MOVWU 4(R0), R8
	MOVD R8, (R0)
	MOVD (R1), R8
	EOR $32, R8, R8
	MOVD R8, (R1)
	MOVD (R3), R8
	MOVD (R0), R9
	MOVWU (R2)(R8), R8
	ORR R8<<32, R9, R8
	MOVD R8, (R0)
	MOVD (R3), R8
	ADD $4, R8, R8
	MOVD R8, (R3)
L_0040:
	MOVD R0, ret+64(FP)
	RET

// func brotli_read_bits
TEXT ·brotli_read_bits(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	MOVD (R1), R8
	CMP $32, R8
	BCC L_0044
	MOVWU 4(R0), R8
	MOVD R8, (R0)
	MOVD (R1), R8
	EOR $32, R8, R8
	MOVD R8, (R1)
	MOVD (R3), R8
	MOVD (R0), R9
	MOVWU (R2)(R8), R8
	ORR R8<<32, R9, R8
	MOVD R8, (R0)
	MOVD (R3), R8
	ADD $4, R8, R8
	MOVD R8, (R3)
	MOVD (R1), R8
L_0044:
	MOVD (R0), R9
	MOVD $-1, R10
	LSL R4, R10, R10
	LSR R8, R9, R9
	ADD R4, R8, R8
	MOVD R8, (R1)
	BIC R10, R9, R0
	MOVD R0, ret+64(FP)
	RET

