// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package asyncapi

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/lemon4ksan/foundation/generic"
)

// ImportConfig configures translation of AsyncAPI specifications into declarative Go contracts.
type ImportConfig struct {
	SpecFile    string
	SpecData    []byte
	PackageName string
	ServiceName string
	OutputFile  string
}

// ImportResult captures the outcome of an AsyncAPI import pass.
type ImportResult struct {
	ContractCode  []byte
	ServicesCount int
	MethodsCount  int
	StructsCount  int
}

// Import loads an AsyncAPI specification and translates it into declarative Go contracts.
//
// Reference: AsyncAPI 3.1.0 Specification (https://www.asyncapi.com/docs/reference/specification/v3.1.0)
func Import(cfg ImportConfig) (*ImportResult, error) {
	var (
		doc *Document
		err error
	)

	if len(cfg.SpecData) > 0 {
		doc, err = ParseSpec(cfg.SpecData)
	} else {
		doc, err = LoadFile(cfg.SpecFile)
	}

	if err != nil {
		return nil, fmt.Errorf("loading asyncapi spec: %w", err)
	}

	code, err := GenerateContract(doc, cfg)
	if err != nil {
		return nil, fmt.Errorf("generating contract: %w", err)
	}

	res := &ImportResult{
		ContractCode:  code,
		ServicesCount: 1,
		MethodsCount:  len(doc.Operations),
		StructsCount:  len(doc.Components.Schemas) + len(doc.Components.Messages),
	}

	return res, nil
}

// GenerateContract translates an AsyncAPI document into a clean, declarative aoni Go contract.
//
// Reference: AsyncAPI 3.1.0 §Operations & §Channels
func GenerateContract(doc *Document, cfg ImportConfig) ([]byte, error) {
	pkgName := cfg.PackageName
	if pkgName == "" {
		pkgName = "api"
	}

	serviceName := cfg.ServiceName
	if serviceName == "" {
		if doc.Info.Title != "" {
			serviceName = sanitizeIdentifier(doc.Info.Title) + "API"
		} else {
			serviceName = "AsyncAPI"
		}
	}

	var bodyBuf bytes.Buffer

	// 1. Service Declaration Header
	bodyBuf.WriteString("// @aoni:service\n")

	// Base URL and Protocol resolution
	baseURL, protocol := resolveServerInfo(doc)
	if baseURL != "" {
		fmt.Fprintf(&bodyBuf, "// @base_url %q\n", baseURL)
	}

	if protocol != "" {
		fmt.Fprintf(&bodyBuf, "// @protocol %s\n", protocol)
	}

	fmt.Fprintf(&bodyBuf, "type %s interface {\n", serviceName)

	// 2. Methods generation
	opKeys := generic.Keys(doc.Operations)
	slices.Sort(opKeys)

	for _, opKey := range opKeys {
		op := doc.Operations[opKey]
		emitOperationMethod(&bodyBuf, doc, opKey, op)
	}

	bodyBuf.WriteString("}\n\n")

	// 3. Subscription helper type
	bodyBuf.WriteString("// Subscription represents an active real-time event listener.\n")
	bodyBuf.WriteString("type Subscription interface {\n")
	bodyBuf.WriteString("\tUnsubscribe() error\n")
	bodyBuf.WriteString("}\n\n")

	// 4. DTO Structs generation
	emitSchemas(&bodyBuf, doc)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by vortex from AsyncAPI %s. DO NOT EDIT.\n", doc.AsyncAPI)
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni\"\n")
	buf.WriteString(")\n\n")

	buf.Write(bodyBuf.Bytes())

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("formatting asyncapi contract: %w", err)
	}

	return formatted, nil
}

func resolveServerInfo(doc *Document) (baseURL, protocol string) {
	protocol = "ws"

	for _, s := range doc.Servers {
		p := strings.ToLower(s.Protocol)
		if p == "wss" || p == "ws" || p == "sse" || p == "socket.io" || p == "socketio" {
			protocol = "ws"
			if p == "sse" {
				protocol = "http"
			}
		}

		if s.Host != "" {
			if !strings.Contains(s.Host, "://") {
				baseURL = p + "://" + s.Host
			} else {
				baseURL = s.Host
			}

			if s.Pathname != "" {
				baseURL = strings.TrimSuffix(baseURL, "/") + "/" + strings.TrimPrefix(s.Pathname, "/")
			}

			return baseURL, protocol
		}
	}

	return "", protocol
}

func emitOperationMethod(buf *bytes.Buffer, doc *Document, opKey string, op Operation) {
	methodName := sanitizeIdentifier(opKey)
	if methodName == "" {
		methodName = "HandleEvent"
	}

	// Doc comment
	if op.Summary != "" {
		fmt.Fprintf(buf, "\t// %s — %s\n", methodName, op.Summary)
	}

	// Address resolution
	address := resolveChannelAddress(doc, op)
	cleanAddress := strings.TrimPrefix(address, "/")

	// Extract path parameters (e.g. {streetlightId} or {userId})
	pathParams := extractPathParams(address)

	// Determine payload DTO type
	payloadType := resolvePayloadType(doc, opKey, op)

	// Request/Reply RPC Pattern (AsyncAPI 3.1.0 §Operation Reply Object)
	if op.Reply != nil {
		replyPayloadType := resolveReplyPayloadType(doc, opKey, op)

		fmt.Fprintf(buf, "\t// @rpc %q\n", opKey)
		if cleanAddress != "" {
			fmt.Fprintf(buf, "\t// @channel %q\n", cleanAddress)
		}

		params := make([]string, 0, 3+len(pathParams))
		params = append(params, "ctx context.Context")
		for _, p := range pathParams {
			params = append(params, p+" string")
		}
		params = append(params, fmt.Sprintf("req *%s", payloadType))
		params = append(params, "mods ...aoni.RequestModifier")

		fmt.Fprintf(buf, "\t%s(%s) (*%s, error)\n\n", methodName, strings.Join(params, ", "), replyPayloadType)
		return
	}

	// Action dispatch (AsyncAPI 3.1.0 §Operation Object - action: send / receive)
	if op.Action == "send" || op.Action == "publish" {
		// Server sends -> Client listens: @event
		fmt.Fprintf(buf, "\t// @event %q\n", opKey)

		if cleanAddress != "" {
			fmt.Fprintf(buf, "\t// @ws %q\n", cleanAddress)
		}

		params := make([]string, 0, 2+len(pathParams))
		params = append(params, "ctx context.Context")
		for _, p := range pathParams {
			params = append(params, p+" string")
		}
		params = append(params, fmt.Sprintf("handler func(msg *%s)", payloadType))

		fmt.Fprintf(buf, "\t%s(%s) (Subscription, error)\n\n", methodName, strings.Join(params, ", "))
	} else {
		// Client sends -> Server receives: @ws:emit
		fmt.Fprintf(buf, "\t// @ws:emit %q\n", opKey)

		if cleanAddress != "" {
			fmt.Fprintf(buf, "\t// @ws %q\n", cleanAddress)
		}

		params := make([]string, 0, 3+len(pathParams))
		params = append(params, "ctx context.Context")
		for _, p := range pathParams {
			params = append(params, p+" string")
		}
		params = append(params, "req *"+payloadType)
		params = append(params, "mods ...aoni.RequestModifier")

		fmt.Fprintf(buf, "\t%s(%s) error\n\n", methodName, strings.Join(params, ", "))
	}
}

func resolveChannelAddress(doc *Document, op Operation) string {
	if op.ChannelRef != "" {
		if ch, ok := doc.Channels[op.ChannelRef]; ok && ch.Address != "" {
			return ch.Address
		}

		return op.ChannelRef
	}

	if op.Channel.Ref != "" {
		ref := op.Channel.Ref

		refKey := strings.TrimPrefix(ref, "#/channels/")
		if ch, ok := doc.Channels[refKey]; ok {
			if ch.Address != "" {
				return ch.Address
			}

			return refKey
		}
	}

	return ""
}

func extractPathParams(pathStr string) []string {
	var params []string

	s := pathStr
	for {
		start := strings.Index(s, "{")
		if start == -1 {
			break
		}
		end := strings.Index(s[start:], "}")
		if end == -1 {
			break
		}

		paramName := s[start+1 : start+end]
		params = append(params, paramName)
		s = s[start+end+1:]
	}

	return params
}

func resolvePayloadType(doc *Document, opKey string, op Operation) string {
	// Check operation messages
	for _, mRef := range op.Messages {
		if mRef.Ref != "" {
			refKey := strings.TrimPrefix(mRef.Ref, "#/components/messages/")
			refKey = strings.TrimPrefix(refKey, "#/channels/")
			if idx := strings.LastIndex(refKey, "/"); idx != -1 {
				refKey = refKey[idx+1:]
			}

			return sanitizeIdentifier(refKey) + "DTO"
		}
	}

	return sanitizeIdentifier(opKey) + "PayloadDTO"
}

func resolveReplyPayloadType(doc *Document, opKey string, op Operation) string {
	if op.Reply != nil {
		for _, mRef := range op.Reply.Messages {
			if mRef.Ref != "" {
				refKey := strings.TrimPrefix(mRef.Ref, "#/components/messages/")
				refKey = strings.TrimPrefix(refKey, "#/channels/")
				if idx := strings.LastIndex(refKey, "/"); idx != -1 {
					refKey = refKey[idx+1:]
				}

				return sanitizeIdentifier(refKey) + "DTO"
			}
		}
	}

	return sanitizeIdentifier(opKey) + "ReplyDTO"
}

func emitSchemas(buf *bytes.Buffer, doc *Document) {
	if doc == nil {
		return
	}

	// 1. Schemas in components
	for schemaName, schema := range doc.Components.Schemas {
		structName := sanitizeIdentifier(schemaName) + "DTO"
		fmt.Fprintf(buf, "// %s represents the %s schema.\n", structName, schemaName)
		fmt.Fprintf(buf, "type %s struct {\n", structName)

		for propName, prop := range schema.Properties {
			fieldName := sanitizeIdentifier(propName)
			fieldType := mapJSONSchemaType(prop)
			fmt.Fprintf(buf, "\t%s %s `json:\"%s,omitempty\"`\n", fieldName, fieldType, propName)
		}

		buf.WriteString("}\n\n")
	}

	// 2. Messages in components
	for msgName, msg := range doc.Components.Messages {
		structName := sanitizeIdentifier(msgName) + "DTO"
		fmt.Fprintf(buf, "// %s represents the %s event payload.\n", structName, msgName)
		fmt.Fprintf(buf, "type %s struct {\n", structName)

		if pMap, ok := msg.Payload.(map[string]any); ok {
			if props, ok := pMap["properties"].(map[string]any); ok {
				for propName, propVal := range props {
					fieldName := sanitizeIdentifier(propName)

					fieldType := "any"
					if pObj, ok := propVal.(map[string]any); ok {
						if tStr, ok := pObj["type"].(string); ok {
							fmtStr, _ := pObj["format"].(string)
							fieldType = mapScalarTypeWithFormat(tStr, fmtStr)
						}
					}

					fmt.Fprintf(buf, "\t%s %s `json:\"%s,omitempty\"`\n", fieldName, fieldType, propName)
				}
			}
		}

		buf.WriteString("}\n\n")
	}
}

func mapJSONSchemaType(s Schema) string {
	switch s.Type {
	case "string":
		return "string"
	case "integer":
		if s.Format == "int64" {
			return "int64"
		}

		return "int"

	case "number":
		if s.Format == "float" {
			return "float32"
		}
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		if s.Items != nil {
			return "[]" + mapJSONSchemaType(*s.Items)
		}

		return "[]any"

	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

func mapScalarTypeWithFormat(t, format string) string {
	switch t {
	case "string":
		return "string"
	case "integer":
		if format == "int64" {
			return "int64"
		}
		return "int"
	case "number":
		if format == "float" {
			return "float32"
		}
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}
