// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ast

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Format renders and formats the AST file as standard Go code.
func Format(f *File) ([]byte, error) {
	var buf bytes.Buffer
	if err := Print(&buf, f); err != nil {
		return nil, err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted source with syntax error for debugging
		return buf.Bytes(), fmt.Errorf("formatting go code: %w\nSource:\n%s", err, buf.String())
	}

	return formatted, nil
}

// WriteFile writes the formatted AST Go code to disk.
func WriteFile(filename string, f *File) error {
	data, err := Format(f)
	if err != nil {
		return err
	}

	dir := filepath.Dir(filename)
	if dir != "" && dir != "." {
		if mkErr := os.MkdirAll(dir, 0o755); mkErr != nil {
			return fmt.Errorf("creating directory %s: %w", dir, mkErr)
		}
	}

	return os.WriteFile(filename, data, 0o644)
}

// Print renders the unformatted AST into an io.Writer.
func Print(w io.Writer, f *File) error {
	fmt.Fprintf(w, "// Code generated by Aoni AST Builder. DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", f.PackageName)

	if len(f.Imports) > 0 {
		fmt.Fprintf(w, "import (\n")

		for _, imp := range f.Imports {
			if imp.Alias != "" {
				fmt.Fprintf(w, "\t%s %q\n", imp.Alias, imp.Path)
			} else {
				fmt.Fprintf(w, "\t%q\n", imp.Path)
			}
		}

		fmt.Fprintf(w, ")\n\n")
	}

	// Render Services
	for _, svc := range f.Services {
		renderDoc(w, svc.Doc, svc.Name, "provides client bindings")
		fmt.Fprintf(w, "//\n")
		fmt.Fprintf(w, "// @aoni:service casing=%s\n", defaultString(string(svc.Casing), "snake_case"))

		if svc.Engine != "" && svc.Engine != EngineNetHTTP {
			fmt.Fprintf(w, "// @engine %s\n", svc.Engine)
		}

		if svc.BaseURL != "" {
			fmt.Fprintf(w, "// @base_url %q\n", svc.BaseURL)
		}

		if svc.UnwrapField != "" {
			fmt.Fprintf(w, "// @unwrap %q\n", svc.UnwrapField)
		}

		for _, h := range svc.Headers {
			fmt.Fprintf(w, "// @header %q %q\n", h.Name, h.Value)
		}

		fmt.Fprintf(w, "type %s interface {\n", svc.Name)

		for _, m := range svc.Methods {
			renderMethod(w, m, f.MaxLen)
		}

		fmt.Fprintf(w, "}\n\n")
	}

	// Render Structs
	for _, st := range f.Structs {
		renderDoc(w, st.Doc, st.Name, "represents a data transfer object")

		if st.Omitempty {
			fmt.Fprintf(w, "//\n// @aoni:dto omitempty=true\n")
		}

		fmt.Fprintf(w, "type %s struct {\n", st.Name)

		for _, fld := range st.Fields {
			renderField(w, fld)
		}

		fmt.Fprintf(w, "}\n\n")
	}

	return nil
}

func renderMethod(w io.Writer, m *Method, maxLen int) {
	if maxLen <= 0 {
		maxLen = 120
	}

	for _, line := range m.Doc {
		fmt.Fprintf(w, "\t// %s\n", line)
	}

	if len(m.Doc) == 0 {
		fmt.Fprintf(w, "\t// %s calls %s.\n", m.Name, m.Path)
	}

	fmt.Fprintf(w, "\t//\n")

	httpMethod := strings.ToLower(m.HTTPMethod)
	if httpMethod == "" {
		httpMethod = "get"
	}

	fmt.Fprintf(w, "\t// @%s %q\n", httpMethod, m.Path)

	if m.Form {
		fmt.Fprintf(w, "\t// @form\n")
	}

	if m.UnwrapField != "" {
		fmt.Fprintf(w, "\t// @unwrap %q\n", m.UnwrapField)
	}

	reqPart := ""
	if len(m.Parameters) > 0 {
		parts := make([]string, 0, len(m.Parameters))
		for _, p := range m.Parameters {
			parts = append(parts, fmt.Sprintf("%s %s", p.Name, p.Type))
		}

		reqPart = strings.Join(parts, ", ") + ", "
	} else if m.RequestModel != "" {
		reqType := m.RequestModel
		if !strings.HasPrefix(reqType, "*") && !isPrimitiveOrSlice(reqType) {
			reqType = "*" + reqType
		}

		reqPart = fmt.Sprintf("req %s, ", reqType)
	}

	respType := m.ResponseModel
	if respType == "" {
		respType = "any"
	}

	singleLine := fmt.Sprintf(
		"\t%s(ctx context.Context, %smods ...aoni.RequestModifier) (%s, error)",
		m.Name,
		reqPart,
		respType,
	)

	if len(singleLine) > maxLen && (len(m.Parameters) > 0 || m.RequestModel != "") {
		// Multi-line signature
		fmt.Fprintf(w, "\t%s(\n", m.Name)
		fmt.Fprintf(w, "\t\tctx context.Context,\n")

		if len(m.Parameters) > 0 {
			for _, p := range m.Parameters {
				fmt.Fprintf(w, "\t\t%s %s,\n", p.Name, p.Type)
			}
		} else if m.RequestModel != "" {
			reqType := m.RequestModel
			if !strings.HasPrefix(reqType, "*") && !isPrimitiveOrSlice(reqType) {
				reqType = "*" + reqType
			}

			fmt.Fprintf(w, "\t\treq %s,\n", reqType)
		}

		fmt.Fprintf(w, "\t\tmods ...aoni.RequestModifier,\n")
		fmt.Fprintf(w, "\t) (%s, error)\n\n", respType)
	} else {
		fmt.Fprintf(w, "%s\n\n", singleLine)
	}
}

func renderField(w io.Writer, f *Field) {
	for _, line := range f.Doc {
		fmt.Fprintf(w, "\t// %s\n", line)
	}

	tagParts := []string{}
	if f.JSONName != "" {
		omit := ",omitempty"
		if f.Required {
			omit = ""
		}

		tagParts = append(tagParts, fmt.Sprintf("json:%q", f.JSONName+omit))
	}

	if f.URLName != "" {
		omit := ",omitempty"
		if f.Required {
			omit = ""
		}

		tagParts = append(tagParts, fmt.Sprintf("url:%q", f.URLName+omit))
	}

	if f.AoniTag != "" {
		tagParts = append(tagParts, fmt.Sprintf("aoni:%q", f.AoniTag))
	}

	if f.CustomTags != "" {
		tagParts = append(tagParts, f.CustomTags)
	}

	tagStr := ""
	if len(tagParts) > 0 {
		tagStr = fmt.Sprintf(" `%s`", strings.Join(tagParts, " "))
	}

	fmt.Fprintf(w, "\t%s %s%s\n", f.Name, f.Type, tagStr)
}

func renderDoc(w io.Writer, doc []string, defaultName, defaultDesc string) {
	if len(doc) > 0 {
		for _, line := range doc {
			fmt.Fprintf(w, "// %s\n", line)
		}
	} else {
		fmt.Fprintf(w, "// %s %s.\n", defaultName, defaultDesc)
	}
}

func isPrimitiveOrSlice(t string) bool {
	return strings.HasPrefix(t, "[]") || strings.HasPrefix(t, "map[") ||
		t == "string" || t == "int" || t == "int64" || t == "bool" || t == "float64" || t == "any"
}

func defaultString(val, def string) string {
	if val == "" {
		return def
	}

	return val
}
