// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package generator

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"strconv"

	"github.com/lemon4ksan/aoni/oracle/spec"
)

// GenerateGo compiles an OracleSpec AST into strongly-typed Go client code.
func GenerateGo(s *spec.OracleSpec, pkgName string) ([]byte, error) {
	if s == nil {
		return nil, errors.New("oracle spec is nil")
	}

	if pkgName == "" {
		pkgName = "oracle"
	}

	port := s.Port
	if port <= 0 {
		port = 64055
	}

	clientName := capitalize(s.Name) + "Oracle"

	var buf bytes.Buffer

	buf.WriteString(`// Code generated by aoni/oracle generator. DO NOT EDIT.

package ` + pkgName + `

import (
	"context"
	"fmt"

	"github.com/lemon4ksan/aoni/oracle"
)

// ` + clientName + ` is the generated typed client for the ` + s.Name + ` attestation oracle.
type ` + clientName + ` struct {
	client *oracle.Client
}

// New` + clientName + ` creates a new instance connected to the oracle sidecar.
func New` + clientName + `(baseURL string) *` + clientName + ` {
	if baseURL == "" {
		baseURL = "http://127.0.0.1:` + strconv.Itoa(port) + `"
	}
	return &` + clientName + `{
		client: oracle.NewClient(baseURL),
	}
}

// Client returns the underlying generic oracle client.
func (o *` + clientName + `) Client() *oracle.Client {
	return o.client
}

// EnsureRunning checks if the sidecar is alive, and if not, launches the sidecar script.
func (o *` + clientName + `) EnsureRunning(ctx context.Context, sidecarPath string) error {
	return o.client.EnsureRunning(ctx, sidecarPath)
}

// Init initializes the browser context with optional cookies.
func (o *` + clientName + `) Init(ctx context.Context, cookies string) error {
	return o.client.Init(ctx, cookies)
}

// Status checks the sidecar health status.
func (o *` + clientName + `) Status(ctx context.Context) (*oracle.StatusResponse, error) {
	return o.client.Status(ctx)
}
`)

	for _, flow := range s.Flows {
		methodName := capitalize(flow.Name)
		fmt.Fprintf(&buf, `
// %s executes the %s attestation flow.
func (o *%s) %s(ctx context.Context, content string) (*oracle.TokenResponse, error) {
	return o.client.GetTokenWithFlow(ctx, %q, content)
}
`, methodName, flow.Name, clientName, methodName, flow.Name)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated Go code: %w", err)
	}

	return formatted, nil
}
