// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package generator

import (
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/lemon4ksan/aoni/ast/js"
	"github.com/lemon4ksan/aoni/oracle/spec"
)

// GenerateJS compiles an OracleSpec AST into a standalone, optimized Node.js sidecar script using aoni/ast/js.
func GenerateJS(s *spec.OracleSpec) ([]byte, error) {
	if s == nil {
		return nil, errors.New("oracle spec is nil")
	}

	port := s.Port
	if port <= 0 {
		port = 64055
	}

	prog := js.NewProgram(
		js.StmtRaw("// Code generated by aoni/oracle generator. DO NOT EDIT."),
		js.StmtRaw("// Oracle Name: "+s.Name),
		js.StmtRaw("// Target URL:  "+s.TargetURL),

		// Dependencies
		js.Require("http", "path", "fs", "os"),
		js.RequireFrom("playwright", "chromium"),

		// Constants
		js.Const("PORT", js.Raw("process.env.ORACLE_PORT || "+strconv.Itoa(port))),
		js.Const("TARGET_URL", js.Raw("process.env.ORACLE_TARGET_URL || "+fmt.Sprintf("%q", s.TargetURL))),
		js.Const("HEADLESS", js.Raw("process.env.HEADLESS !== 'false' && "+strconv.FormatBool(s.Browser.Headless))),

		// State
		js.Let("browserContext", nil),
		js.Let("activePage", nil),
		js.Const("capturedTokensPool", js.Raw("[]")),

		// Browser discovery
		js.StmtRaw(`function findSystemBrowser() {
  const customPath = process.env.BROWSER_PATH || process.env.CHROME_PATH;
  if (customPath && fs.existsSync(customPath)) {
    return { path: customPath, source: 'environment variable' };
  }

  const commonPaths = [
    // Windows standard paths
    path.join(os.homedir(), 'AppData', 'Local', 'imput', 'Helium', 'Application', 'chrome.exe'),
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    path.join(os.homedir(), 'AppData', 'Local', 'Google', 'Chrome', 'Application', 'chrome.exe'),
    'C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe',
    'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',

    // macOS standard paths
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Helium.app/Contents/MacOS/Helium',
    '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',
    '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
    '/Applications/Chromium.app/Contents/MacOS/Chromium',

    // Linux standard paths
    '/usr/bin/google-chrome',
    '/usr/bin/google-chrome-stable',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/usr/bin/brave-browser',
    '/snap/bin/chromium',
  ];

  for (const p of commonPaths) {
    if (p && fs.existsSync(p)) {
      const name = p.includes('Helium') ? 'Helium' : path.basename(p);
      return { path: p, source: `+"`auto-detected (${name})`"+` };
    }
  }

  return { path: undefined, source: 'default bundled Chromium' };
}`),

		// Cookie parser helper
		js.StmtRaw(`function parseCookieHeader(headerStr) {
  if (!headerStr) return [];
  const parts = headerStr.split(';');
  const cookies = [];
  for (const part of parts) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx !== -1) {
      const name = trimmed.substring(0, eqIdx).trim();
      const value = trimmed.substring(eqIdx + 1).trim();
      cookies.push({
        name,
        value,
        domain: new URL(TARGET_URL).hostname,
        path: '/',
      });
    }
  }
  return cookies;
}`),

		// Kinetics helpers
		js.StmtRaw(`async function humanType(page, text) {
  for (const char of text) {
    await page.keyboard.type(char, { delay: 10 + Math.random() * 25 });
  }
}`),

		js.StmtRaw(`async function humanClick(page, locator) {
  const box = await locator.boundingBox();
  if (box) {
    const x = box.x + box.width / 2 + (Math.random() * 6 - 3);
    const y = box.y + box.height / 2 + (Math.random() * 6 - 3);
    await page.mouse.move(x, y, { steps: 5 });
  }
  await locator.click();
}`),

		// Dialog dismissal
		buildDismissDialogsFn(s),

		// Interceptors setup
		buildSetupInterceptorsFn(s),

		// Init browser function
		buildInitBrowserFn(s),

		// Flow execution function
		buildExecuteFlowFn(s),

		// HTTP Server
		buildHTTPServerStmt(s),
	)

	code, err := js.Format(prog)
	if err != nil {
		return nil, fmt.Errorf("formatting generated JS AST: %w", err)
	}

	return []byte(code), nil
}

func buildDismissDialogsFn(s *spec.OracleSpec) js.Stmt {
	if len(s.Browser.DismissSelectors) == 0 {
		return js.Fn("dismissDialogs").Async().Args("page").Body(
			js.StmtRaw("// No custom dismissal selectors specified"),
		)
	}

	selectorsJSON, _ := json.Marshal(s.Browser.DismissSelectors)

	return js.StmtRaw(fmt.Sprintf(`async function dismissDialogs(page) {
  const selectors = %s;
  for (const sel of selectors) {
    try {
      const btn = page.locator(sel).first();
      if (await btn.isVisible({ timeout: 1000 })) {
        await btn.click();
        console.log('[oracle] dismissed dialog: ' + sel);
        await page.waitForTimeout(300);
      }
    } catch (e) {}
  }
}`, string(selectorsJSON)))
}

func buildSetupInterceptorsFn(s *spec.OracleSpec) js.Stmt {
	var rules strings.Builder
	for _, flow := range s.Flows {
		if flow.Intercept.URLPattern != "" {
			fmt.Fprintf(&rules, `    if (url.includes(%q) && req.method() === 'POST') {
      try {
        const postData = req.postData();
        if (postData) {
          const parsed = JSON.parse(postData);
          let token = null;
          if (Array.isArray(parsed) && parsed.length > %d) {
            token = parsed[%d];
          }
          if (token && typeof token === 'string' && token.startsWith('!')) {
            capturedTokensPool.push({
              token,
              headers: req.headers(),
              url: url
            });
            if (capturedTokensPool.length > 5) capturedTokensPool.shift();
          }
        }
      } catch (e) {}
    }
`, flow.Intercept.URLPattern, flow.Intercept.TokenIndex, flow.Intercept.TokenIndex)
		}
	}

	return js.StmtRaw(fmt.Sprintf(`async function setupInterceptors(page) {
  page.on('request', async req => {
    const url = req.url();
%s  });
}`, rules.String()))
}

func buildInitBrowserFn(s *spec.OracleSpec) js.Stmt {
	return js.StmtRaw(fmt.Sprintf(`let initPromise = null;

async function initBrowser(rawCookies = null) {
  if (browserContext && activePage) {
    if (rawCookies) {
      const cookies = parseCookieHeader(rawCookies);
      await browserContext.addCookies(cookies);
      try {
        await activePage.goto(TARGET_URL, { waitUntil: 'domcontentloaded', timeout: 30000 });
      } catch (err) {}
    }
    return;
  }

  if (initPromise) return initPromise;

  initPromise = (async () => {
    try {
      const detected = findSystemBrowser();
      console.log('[oracle] using browser at: ' + (detected.path || 'bundled') + ' [' + detected.source + ']');
      
      const tmpDir = path.join(os.tmpdir(), 'aoni_oracle_%s');
      browserContext = await chromium.launchPersistentContext(tmpDir, {
        headless: HEADLESS,
        executablePath: detected.path,
        viewport: { width: 1280, height: 800 },
        args: [
          '--disable-blink-features=AutomationControlled',
          '--disable-infobars',
          '--no-sandbox',
          '--disable-setuid-sandbox'
        ]
      });

      if (rawCookies) {
        const cookies = parseCookieHeader(rawCookies);
        await browserContext.addCookies(cookies);
      }

      const pages = browserContext.pages();
      activePage = pages.length > 0 ? pages[0] : await browserContext.newPage();
      await setupInterceptors(activePage);

      await activePage.goto(TARGET_URL, { waitUntil: 'domcontentloaded', timeout: 45000 });
      await activePage.waitForTimeout(1500);
      await dismissDialogs(activePage);
      console.log('[oracle] browser ready on ' + TARGET_URL);
    } finally {
      initPromise = null;
    }
  })();

  return initPromise;
}`, s.Name))
}

func buildExecuteFlowFn(s *spec.OracleSpec) js.Stmt {
	var flowBlocks strings.Builder

	for _, flow := range s.Flows {
		fmt.Fprintf(&flowBlocks, `  if (!flowName || flowName === %q) {
    capturedTokensPool.length = 0;
    try {
      const input = activePage.locator(%q).first();
      if (await input.isVisible({ timeout: 3000 })) {
        await humanClick(activePage, input);
        await activePage.keyboard.press('Control+A');
        await activePage.keyboard.press('Backspace');
        await activePage.waitForTimeout(60);

        await humanType(activePage, content || 'hello');
        await activePage.waitForTimeout(150);

        const submit = activePage.locator(%q).first();
        if (await submit.isVisible({ timeout: 1000 })) {
          await humanClick(activePage, submit);
        } else {
          await activePage.keyboard.press(%q);
        }

        for (let i = 0; i < 50; i++) {
          await activePage.waitForTimeout(150);
          if (capturedTokensPool.length > 0) {
            return capturedTokensPool.pop();
          }
        }
      }
    } catch (e) {
      console.warn('[oracle] flow execution warning:', e.message);
    }
    if (capturedTokensPool.length > 0) return capturedTokensPool.pop();
  }
`, flow.Name, flow.InputSelector, flow.SubmitSelector, flow.FallbackShortcut)
	}

	return js.StmtRaw(fmt.Sprintf(`async function executeFlow(flowName, content) {
  await initBrowser();
  if (!activePage) throw new Error('browser session not ready');
  await dismissDialogs(activePage);

%s
  throw new Error('failed to capture token for flow: ' + flowName);
}`, flowBlocks.String()))
}

func buildHTTPServerStmt(s *spec.OracleSpec) js.Stmt {
	return js.StmtRaw(fmt.Sprintf(`const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `+"`http://${req.headers.host}`"+`);

  if (req.method === 'POST' && url.pathname === '/init') {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', async () => {
      try {
        const data = JSON.parse(body || '{}');
        await initBrowser(data.cookies);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'ok' }));
      } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: err.message }));
      }
    });
    return;
  }

  if (req.method === 'POST' && url.pathname === '/token' || req.method === 'GET' && url.pathname === '/token') {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', async () => {
      try {
        let content = '';
        let flowName = '';
        if (body) {
          try {
            const data = JSON.parse(body);
            content = data.content || '';
            flowName = data.flow || '';
          } catch (e) {}
        }
        const item = await executeFlow(flowName, content);
        const token = typeof item === 'object' ? item.token : item;
        const reqHeaders = typeof item === 'object' ? (item.headers || {}) : {};

        let cookieHeader = '';
        if (browserContext) {
          try {
            const cList = await browserContext.cookies();
            cookieHeader = cList.map(c => `+"`${c.name}=${c.value}`"+`).join('; ');
          } catch (e) {}
        }

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'ok', token, headers: reqHeaders, cookies: cookieHeader }));
      } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: err.message }));
      }
    });
    return;
  }

  if (req.method === 'GET' && url.pathname === '/status') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: 'ok',
      ready: !!activePage,
      pageUrl: activePage ? activePage.url() : null
    }));
    return;
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Not found' }));
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`+"`🤖 Oracle Sidecar [%q] listening on http://127.0.0.1:${PORT}`"+`);
  initBrowser().catch(err => {
    console.log('[oracle] background init notice:', err.message);
  });
});`, s.Name))
}
