// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: 01_basic_http.go

package golden01

import (
	"context"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"
)

type userAPIClient struct {
	r request.Requester
}

func newUserAPI(doer any, opts ...aoni.ClientOption) *userAPIClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	targetReq := request.Configure(doer, append([]aoni.ClientOption{option.WithBaseURL("")}, baseOpts...)...)

	return &userAPIClient{
		r: targetReq,
	}
}

// NewUserAPI creates a new UserAPI client instance with preconfigured execution pipelines.
func NewUserAPI(doer any, opts ...aoni.ClientOption) UserAPI {
	return newUserAPI(doer, opts...)
}

// R returns the underlying request.Requester used by the client.
func (c *userAPIClient) R() request.Requester {
	return c.r
}

func (c *userAPIClient) GetUser(ctx context.Context, id string, mods ...aoni.RequestModifier) (*UserDTO, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("id", id))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[UserDTO](ctx, c.r, "users/{id}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *userAPIClient) CreateUser(ctx context.Context, req CreateUserRequest, mods ...aoni.RequestModifier) (*UserDTO, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.PostTo[UserDTO](ctx, c.r, "users", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
