// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: 02_advanced_routing.go

package golden02

import (
	"context"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
)

type paymentAPIClient struct {
	r *aoni.Client
}

func newPaymentAPI(doer any, opts ...aoni.ClientOption) *paymentAPIClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	targetReq := aoni.NewClient(doer, append([]aoni.ClientOption{option.WithBaseURL("https://api.example.com/v1")}, baseOpts...)...)

	return &paymentAPIClient{
		r: targetReq,
	}
}

// NewPaymentAPI creates a new PaymentAPI client instance with preconfigured execution pipelines.
func NewPaymentAPI(doer any, opts ...aoni.ClientOption) PaymentAPI {
	return newPaymentAPI(doer, opts...)
}

// R returns the underlying *aoni.Client used by the client.
func (c *paymentAPIClient) R() *aoni.Client {
	return c.r
}

func (c *paymentAPIClient) GetInvoice(ctx context.Context, invoice_id string, mods ...aoni.RequestModifier) (*InvoiceDTO, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("invoice_id", invoice_id))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	allMods = append(allMods, mod.WithCoalesce())
	resp, err := c.r.Get[InvoiceDTO](ctx, "invoices/{invoice_id}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *paymentAPIClient) CreateCheckout(ctx context.Context, req CheckoutReq, mods ...aoni.RequestModifier) (*CheckoutSession, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	allMods = append(allMods, mod.WithIdempotencyKey())
	resp, err := c.r.Post[CheckoutSession](ctx, "checkout", req, allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
