// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: 03_advanced_formats.go

package golden03

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/fast"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"
)

type billingAPIClient struct {
	r request.Requester
}

func newBillingAPI(doer any, opts ...aoni.ClientOption) *billingAPIClient {
	if doer == nil {
		doer = fast.NewClient()
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	targetReq := request.Configure(doer, append([]aoni.ClientOption{option.WithBaseURL("https://api.fintech.com/v1")}, baseOpts...)...)

	return &billingAPIClient{
		r: targetReq,
	}
}

// NewBillingAPI creates a new BillingAPI client instance with preconfigured execution pipelines.
func NewBillingAPI(doer any, opts ...aoni.ClientOption) BillingAPI {
	return newBillingAPI(doer, opts...)
}

// R returns the underlying request.Requester used by the client.
func (c *billingAPIClient) R() request.Requester {
	return c.r
}

func (c *billingAPIClient) GetTransactions(ctx context.Context, from time.Time, to time.Time, statuses []string, categories []string, accountIDs []int64, includePending bool, compact bool, mods ...aoni.RequestModifier) (*TransactionList, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [256]byte
	qBytes := qBuf[:0]
	qBytes = append(qBytes, "from="...)
	qBytes = strconv.AppendInt(qBytes, from.UnixMilli(), 10)
	qBytes = append(qBytes, "&to="...)
	qBytes = append(qBytes, url.QueryEscape(to.Format("2006-01-02"))...)
	qBytes = append(qBytes, "&statuses="...)
	for idx, v := range statuses {
		if idx > 0 {
			qBytes = append(qBytes, ',')
		}
		qBytes = append(qBytes, url.QueryEscape(v)...)
	}
	qBytes = append(qBytes, "&categories="...)
	for idx, v := range categories {
		if idx > 0 {
			qBytes = append(qBytes, '|')
		}
		qBytes = append(qBytes, url.QueryEscape(v)...)
	}
	qBytes = append(qBytes, "&accountIDs="...)
	for idx, v := range accountIDs {
		if idx > 0 {
			qBytes = append(qBytes, ',')
		}
		qBytes = strconv.AppendInt(qBytes, int64(v), 10)
	}
	qBytes = append(qBytes, "&includePending="...)
	if includePending {
		qBytes = append(qBytes, '1')
	} else {
		qBytes = append(qBytes, '0')
	}
	qBytes = append(qBytes, "&compact="...)
	qBytes = append(qBytes, url.QueryEscape(fmt.Sprint(compact))...)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := request.GetTo[TransactionList](ctx, c.r, "transactions", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (r *TransactionList) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Total != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "total="...)
		dst = strconv.AppendInt(dst, int64(r.Total), 10)
	}

	return dst
}

func (r *TransactionList) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

func (r *TransactionList) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Total != 0 {
		vals.Set("total", strconv.FormatInt(int64(r.Total), 10))
	}
}
