// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func tls13_compute_nonce
TEXT ·tls13_compute_nonce(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	MOVL 0(DI), AX
	BSWAPQ SI
	XORQ 0x4(DI), SI
	MOVL AX, 0(DX)
	MOVQ SI, 0x4(DX)
	MOVQ AX, ret+48(FP)
	RET

