// Code generated by c2plan9. DO NOT EDIT.

//go:build arm64 && !purego

#include "textflag.h"

// func tls13_compute_nonce
TEXT ·tls13_compute_nonce(SB), NOSPLIT, $0-72
	MOVD arg0+0(FP), R0
	MOVD arg1+8(FP), R1
	MOVD arg2+16(FP), R2
	MOVD arg3+24(FP), R3
	MOVD arg4+32(FP), R4
	MOVD arg5+40(FP), R5
	MOVD arg6+48(FP), R6
	MOVD arg7+56(FP), R7

	MOVD 4(R0), R9
	MOVWU (R0), R8
	REV R1, R10
	EOR R10, R9, R9
	MOVW R8, (R2)
	MOVD R9, 4(R2)
	MOVD R0, ret+64(FP)
	RET

